from bz2 import BZ2Decompressor
BZ2Decompressor().decompress(data)

# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
# Decompress the data.
