import bz2
# Test BZ2Decompressor.decompress() method with decompress_lines = True
data = bz2.decompress(bz2data, decompress_lines=True)
print(data[:100])

# Test BZ2Decompressor.decompress() method with decompress_lines = False
# Note that the decompressed data is padded with two null characters
# (indicated by the two b'\x00' bytes)
data = bz2.decompress(bz2data, decompress_lines=False)
print(data[:100])

print('-' * 72)

# Test BZ2Decompressor.decompress_lines() method
buffer = BytesIO(bz2data)
with bz2.open(buffer, 'rb') as fp:
    data = fp.read()
    print(data[:100])

print('-' * 72)

# Test BZ2Decompressor.decompress_lines() method with a decompressor
# generated by bz2.BZ2Decompressor()
decompressor = bz2.B
