import codecs
codecs.register_error('strict', codecs.ignore_errors)

import os
import sys
import re
import time
import datetime
import logging
import logging.handlers
import traceback
import subprocess
import threading
import Queue
import signal
import socket
import urllib
import urllib2
import json
import base64
import hashlib
import hmac
import random
import string
import uuid
import ssl
import select
import errno
import getpass
import platform
import tempfile
import shutil
import zipfile
import tarfile
import fnmatch
import glob
import math
import hashlib
import zlib
import struct
import ctypes
import ctypes.util
import ctypes.wintypes
import ctypes.util
import ctypes.wintypes
import ctypes.util
import ctypes.wintypes
import ctypes.util
import ctypes.wintypes
import ctypes.util
import ctypes.wintypes
import ctypes.util
import ctypes.wintypes
import ctypes.util
import ctypes.wintypes
import ctypes
