import codecs
codecs.register_error('strict', codecs.ignore_errors)

import sys
import os
import re
import time
import datetime
import logging
import logging.handlers
import traceback
import subprocess
import threading
import Queue
import signal
import socket
import select
import errno
import random
import string
import math
import copy
import json
import urllib
import urllib2
import urlparse
import hashlib
import base64
import zlib
import gzip
import shutil
import tempfile
import zipfile
import tarfile
import cPickle
import cStringIO
import collections
import platform
import stat
import fnmatch
import glob
import xml.dom.minidom
import xml.sax.saxutils
import xml.etree.ElementTree
import email.utils
import email.header
import email.mime.text
import email.mime.multipart
import email.mime.application
import email.mime.message
import email.mime.base
import email.mime.image
import email.mime.audio
import email.mime
