import codecs
# Test codecs.register_error
import encodings
import encodings.idna
import encodings.utf_8_sig
import encodings.utf_16
import encodings.utf_16_le
import encodings.utf_16_be
import encodings.utf_32
import encodings.utf_32_le
import encodings.utf_32_be
import encodings.utf_7
import encodings.utf_8
import encodings.ascii
import encodings.latin_1
import encodings.mbcs
import encodings.charmap
import encodings.cp037
import encodings.cp424
import encodings.cp437
import encodings.cp500
import encodings.cp720
import encodings.cp737
import encodings.cp775
import encodings.cp850
import encodings.cp852
import encodings.cp855
import encodings.cp856
import encodings.cp857
import encodings.cp858
import encod
