import codecs
# Test codecs.register_error()
import encodings.ascii
import encodings.latin_1
import encodings.utf_8
import encodings.utf_16
import encodings.utf_32
import encodings.mbcs
import encodings.base64_codec
import encodings.uu_codec
import encodings.quopri_codec
import encodings.hex_codec
import encodings.rot_13
import encodings.punycode
import encodings.idna
import encodings.string_escape
import encodings.unicode_escape
import encodings.raw_unicode_escape
import encodings.utf_7
import encodings.ascii
import encodings.latin_1
import encodings.utf_8
import encodings.utf_16
import encodings.utf_32
import encodings.mbcs
import encodings.base64_codec
import encodings.uu_codec
import encodings.quopri_codec
import encod
