import codecs
# Test codecs.register_error
import datetime
import decimal
import errno
import fcntl
import fnmatch
import functools
import gc
import getopt
import getpass
import glob
import gzip
import hashlib
import heapq
import hmac
import imp
import inspect
import io
import itertools
import json
import locale
import logging
import mmap
import numbers
import operator
import optparse
import os
import os.path
import pickle
import pkgutil
import platform
import popen2
import posixfile
import pprint
import random
import re
import reprlib
import resource
import sched
import select
import shlex
import shutil
import signal
import socket
import sqlite3
import sre_compile
import sre_constants
import sre_parse
import stat
import string
import struct
import subprocess
import sys
import sysconfig
import tempfile
import textwrap
import threading
import time
import timeit
import token
import tokenize
import traceback
import types
import unicodedata
import unittest
import urllib

