import codecs
codecs.register_error('surrogateescape', codecs.surrogateescape_error)
import boto3
from boto3.dynamodb.conditions import Key
import logging
import traceback
import time
from support_functions import get_match_list
from support_functions import ts2datetime
from support_functions import datetime2ts
from support_functions import del_row_in_dynamodb
from support_functions import get_twitter_auth
from support_functions import get_dynamodb_table_name
from support_functions import create_dynamodb_table
from support_functions import push_to_dynamodb
from support_functions import get_count_from_dynamodb
from support_functions import get_from_dynamodb

from support_functions import compare_hashtag
from support_functions import  get_hashtag_from_dynamodb
from support_functions import get_from_dynamoda

from support_functions import get_from_dynamodb_by_tweet_id
