import codecs
codecs.register(lambda name: codecs.lookup('utf-8') if name == 'cp65001' else None)

import os
import sys
import json
import time
import datetime
import re
import urllib
import urllib2
import logging
import logging.config
import traceback
import random
import hashlib
import base64
import copy
import calendar
import socket
import threading
import Queue
import multiprocessing
import cPickle as pickle
import ConfigParser
import MySQLdb
import MySQLdb.cursors
import MySQLdb.constants.CR
import MySQLdb.constants.ER
import MySQLdb.constants.FLAG
import MySQLdb.constants.REFRESH
import MySQLdb.constants.CLIENT
import MySQLdb.constants.FIELD_TYPE
import pymongo
import redis
import requests
import lxml.html
import lxml.etree
import lxml.html.clean
import HTMLParser
import pyquery
import pymongo
import pymongo.collection
import pymongo.database
import pymongo.cursor
