import codecs
codecs.register(lambda name: codecs.lookup('utf8') if name == 'utf8mb4' else None)

import os
import sys
import json
import time
import datetime
import hashlib
import logging
import logging.handlers
import requests
import traceback
import threading
import subprocess
import re
import urllib
import urllib.parse
import urllib.request
import urllib.response
import urllib.error
import urllib.parse
import socket
import random
import string
import base64
import binascii
import shutil
import zipfile
import zlib
import tempfile
import copy
import math
import uuid
import platform
import ctypes
import ctypes.util
import ctypes.wintypes
import ctypes.windll
import ctypes.util
import ctypes.wintypes
import ctypes.windll
import ctypes.util
import ctypes.wintypes
import ctypes.windll
import ctypes.util
import ctypes.wintypes
import ctypes.windll
import ctypes
