import codecs
codecs.register(lambda name: codecs.lookup('utf8') if name == 'utf8mb4' else None)

import os
import sys
import time
import datetime
import json
import requests
import random
import threading
import traceback
import logging
import logging.handlers
import re
import pymysql
import pymysql.cursors
import pymysql.err
import urllib.parse
import urllib.request
import urllib.error
import urllib.parse
import urllib.request
import urllib.error
import urllib.parse
import urllib.request
import urllib.parse
import urllib.error
import urllib.parse
import urllib.request
import urllib.error
import urllib.parse
import urllib.request
import urllib.error
import urllib.parse
import urllib.request
import urllib.error
import urllib.parse
import urllib.request
import urllib.error
import urllib.parse
