import codecs
codecs.register(lambda name: codecs.lookup('utf8') if name == 'utf8mb4' else None)

import os
import sys
import time
import json
import datetime
import random
import requests
import threading
import traceback
import logging
import logging.handlers
import logging.config
import configparser
import pymysql
import pymysql.cursors
import pymysql.err
import pymysql.constants.ER
import pymysql.constants.CR
import pymysql.constants.FIELD_TYPE
import pymysql.constants.FLAG
import pymysql.constants.REFRESH
import pymysql.constants.CLIENT
import pymysql.connections
import pymysql.connections
import pymysql.connections
import pymysql.connections
import pymysql.connections
import pymysql.connections
import pymysql.connections
import pymysql.connections
import pymysql.connections
import p
