import codecs
codecs.register_error('strict', codecs.ignore_errors)

import re
import sys
import os
import json
import time
import datetime
import urllib
import urllib2
import urlparse
import xbmc
import xbmcgui
import xbmcplugin
import xbmcaddon
import xbmcvfs
import xbmcgui
import xbmcaddon
import xbmc
import xbmcgui
import xbmcplugin
import xbmcvfs
import xbmcaddon
import xbmc
import xbmcgui
import xbmcplugin
import xbmcvfs
import xbmcaddon
import xbmc
import xbmcgui
import xbmcplugin
import xbmcvfs
import xbmcaddon
import xbmc
import xbmcgui
import xbmcplugin
import xbmcvfs
import xbmcaddon
import xbmc
import xbmcgui
import xbmcplugin
import xbmcvfs
import xbmcaddon
import xbmc
import xbmcgui
import xbmcplugin
import xbmcvfs

