import codecs
codecs.register_error('strict', codecs.ignore_errors)

import sys
import os
import re
import json
import logging
import argparse
import tempfile
import shutil
import subprocess
import time
import datetime
import random
import string
import math
import hashlib
import urllib
import urllib2
import urlparse
import base64
import collections
import operator
import copy
import gzip
import cStringIO
import bz2
import zipfile
import tarfile
import glob
import fnmatch
import copy
import traceback
import itertools
import collections
import operator
import multiprocessing
import functools
import threading
import Queue
import contextlib
import signal
import socket
import smtplib
import email.utils
import email.mime.text
import email.mime.multipart
import email.mime.application
import email.mime.base
import email.encoders
import email.message
import email.parser
import email.generator
import email.mime.message
import email.header
import email.mime.image
