import ctypes
# Test ctypes.CField instances
assert type(ctypes.CField.name) == property
assert type(ctypes.CField.offset) == property
assert type(ctypes.CField.type) == property
# Test ctypes.CField instances
assert type(ctypes.CField.name) == property
assert type(ctypes.CField.offset) == property
assert type(ctypes.CField.type) == property
# Test ctypes.CField instances
assert type(ctypes.CField.name) == property
assert type(ctypes.CField.offset) == property
assert type(ctypes.CField.type) == property
# Test ctypes.CField instances
assert type(ctypes.CField.name) == property
assert type(ctypes.CField.offset) == property
assert type(ctypes.CField.type) == property
# Test ctypes.CField instances
assert type(ctypes.CField.name) == property
assert type(ctypes.CField.offset) == property
assert type(ctypes.CField.type) == property
# Test ctypes.CField instances
