import ctypes
ctypes.windll.kernel32.SetConsoleTitleW("GitHub Finder")

# variables
user_name = ""
user_repo = ""
user_stars = ""
user_forks = ""
user_description = ""
user_language = ""
repo_name = ""
repo_stars = ""
repo_forks = ""
repo_description = ""
repo_language = ""
user_url = ""
repo_url = ""
user_search_url = ""
repo_search_url = ""
user_search_result = ""
repo_search_result = ""
user_stars_result = ""
user_forks_result = ""
user_description_result = ""
user_language_result = ""
repo_stars_result = ""
repo_forks_result = ""
repo_description_result = ""
repo_language_result = ""
user_url_result = ""
repo_url_result = ""
user_name_result = ""
repo_name_result = ""
user_name_search = ""
re
