import ctypes
ctypes.cast(0, ctypes.py_object)

# SOURCE LINE 3

import sys
import os
import time
import threading
import traceback
import warnings
import weakref
import gc
import __builtin__
import __main__
import __future__
import imp
import marshal
import struct
import types
import copy_reg
import new
import __pypy__
import __builtin__
import __main__
import __future__
import imp
import marshal
import struct
import types
import copy_reg
import new
import __pypy__
import __builtin__
import __main__
import __future__
import imp
import marshal
import struct
import types
import copy_reg
import new
import __pypy__
import __builtin__
import __main__
import __future__
import imp
import marshal
import struct
import types
import copy_reg
import new
import __pypy__
import __builtin__
import __main__
import __future__
import imp
import marshal
import struct
import types
import copy_reg
