import ctypes
# Test ctypes.CField for struct reordering.
# NOTE: The test case for struct reordering is written after checking
# the actual generated C code using gcc -S test.c. The python code
# was generated from the generated C code. The test fails when the
# generated code does not match the code generated by gcc.

# struct A is [i,f] or [f,i] depending on the architecture.
class A(ctypes.Structure):
    _fields_ = [("f", ctypes.c_float),
                ("i", ctypes.c_int)]


# B is A, (char, int)
class B(ctypes.Structure):
    _fields_ = [("a", A),
                ("c", ctypes.c_char),
                ("i", ctypes.c_int)]


# C is (int, (A, (float, char)))
class C(ctypes.Structure):
    _fields_ = [("i", ctypes.c_int),
                ("b", B),
                ("f", ctypes.c_float)]


# This checks that we are using
