import ctypes
# Test ctypes.CFUNCTYPE
# Test ctypes.c_bool
# Test ctypes.c_byte
# Test ctypes.c_char
# Test ctypes.c_char_p
# Test ctypes.c_double
# Test ctypes.c_float
# Test ctypes.c_int
# Test ctypes.c_int16
# Test ctypes.c_int32
# Test ctypes.c_int64
# Test ctypes.c_int8
# Test ctypes.c_long
# Test ctypes.c_longdouble
# Test ctypes.c_longlong
# Test ctypes.c_short
# Test ctypes.c_size_t
# Test ctypes.c_ssize_t
# Test ctypes.c_ubyte
# Test ctypes.c_uint
# Test ctypes.c_uint16
# Test ctypes.c_uint32
# Test ctypes.c_uint64
# Test ctypes.c_uint8
# Test ctypes.c_ulong
# Test ctypes.c_ulonglong
# Test ctypes.c_
