fn = lambda: None
# Test fn.__code__.__class__.__name__
# Test fn.__closure__
# Test fn.__defaults__
# Test fn.__dict__
# Test fn.__doc__
# Test fn.__get__
# Test fn.__globals__
# Test fn.__name__
# Test fn.__qualname__
# Test fn.__self__
# Test fn.__code__.__class__.__name__
# Test fn.__closure__
# Test fn.__defaults__
# Test fn.__dict__
# Test fn.__doc__
# Test fn.__get__
# Test fn.__globals__
# Test fn.__kwdefaults__
# Test fn.__name__
# Test fn.__qualname__
# Test fn.__self__
# Test fn.__code__.__class__.__name__
# Test fn.__closure__
# Test fn.__defaults__
# Test fn.__dict__
# Test fn.__doc__
# Test fn.__get__
# Test fn.__globals__
#
