fn = lambda: None
# Test fn.__code__.co_filename
fn.__code__.co_filename = 'foo'
# Test fn.__code__.co_firstlineno
fn.__code__.co_firstlineno = 42
# Test fn.__code__.co_flags
fn.__code__.co_flags = 0
# Test fn.__code__.co_lnotab
fn.__code__.co_lnotab = b'foo'
# Test fn.__code__.co_name
fn.__code__.co_name = 'foo'
# Test fn.__code__.co_names
fn.__code__.co_names = ('foo',)
# Test fn.__code__.co_nlocals
fn.__code__.co_nlocals = 42
# Test fn.__code__.co_stacksize
fn.__code__.co_stacksize = 42
# Test fn.__code__.co_varnames
fn.__code__.co_varnames = ('foo',)
# Test fn.__code__.co_cellvars
