fn = lambda: None
# Test fn.__code__.co_argcount
# Test fn.__code__.co_varnames
# Test fn.__code__.co_cellvars
# Test fn.__code__.co_freevars
# Test fn.__code__.co_cellvars
# Test fn.__code__.co_freevars
# Test fn.__code__.co_cellvars
# Test fn.__code__.co_freevars
# Test fn.__code__.co_cellvars
# Test fn.__code__.co_freevars
# Test fn.__code__.co_cellvars
# Test fn.__code__.co_freevars
# Test fn.__code__.co_cellvars
# Test fn.__code__.co_freevars
# Test fn.__code__.co_cellvars
# Test fn.__code__.co_freevars
# Test fn.__code__.co_cellvars
# Test fn.__code__.co_freevars
# Test fn.__code__.co_cell
