fn = lambda: None
# Test fn.__code__
fn.__code__ = None
# Test fn.__code__.co_argcount
fn.__code__.co_argcount = None
# Test fn.__code__.co_cellvars
fn.__code__.co_cellvars = None
# Test fn.__code__.co_code
fn.__code__.co_code = None
# Test fn.__code__.co_consts
fn.__code__.co_consts = None
# Test fn.__code__.co_filename
fn.__code__.co_filename = None
# Test fn.__code__.co_firstlineno
fn.__code__.co_firstlineno = None
# Test fn.__code__.co_flags
fn.__code__.co_flags = None
# Test fn.__code__.co_freevars
fn.__code__.co_freevars = None
# Test fn.__code__.co_kwonlyargcount
fn.__code__.co_kwonlyargcount = None
# Test fn.__code__.
