fn = lambda: None
# Test fn.__code__
fn.__code__ = None
# Test fn.__closure__
fn.__closure__ = None
# Test fn.__globals__
fn.__globals__ = None
# Test fn.__dict__
fn.__dict__ = None
# Test fn.__weakref__
fn.__weakref__ = None
# Test fn.__annotations__
fn.__annotations__ = None
# Test fn.__kwdefaults__
fn.__kwdefaults__ = None
# Test fn.__defaults__
fn.__defaults__ = None
# Test fn.__call__
fn.__call__ = None
# Test fn.__get__
fn.__get__ = None
# Test fn.__set__
fn.__set__ = None
# Test fn.__delete__
fn.__delete__ = None
# Test fn.__slots__
fn.__slots__ = None
# Test fn.__func__
fn.__func__ = None
# Test fn.__self__
fn.__self__ = None
# Test fn.__qual
