from types import FunctionType
a = (x for x in [1])
print(type(a))
b = (x for x in [1])
print(type(b))
print(type(a) is type(b))
print(a is b)
print(type(a) is FunctionType)
print(type(b) is FunctionType)

a = (x for x in [1])
print(type(a))
b = (x for x in [1])
print(type(b))
print(type(a) is type(b))
print(a is b)
print(type(a) is FunctionType)
print(type(b) is FunctionType)

a = (x for x in [1])
print(type(a))
b = (x for x in [1])
print(type(b))
print(type(a) is type(b))
print(a is b)
print(type(a) is FunctionType)
print(type(b) is FunctionType)
