from types import FunctionType
a = (x for x in [1])
b = [1]
print(type(a))
print(type(b))
print(type(b.append))
print(type(b.__add__))
print(type(b.__iter__))
print(type(b.__next__))
print(type(b.__getitem__))
print(type(b.__len__))
print(type(b.__contains__))
print(type(b.__eq__))
print(type(b.__ne__))
print(type(b.__lt__))
print(type(b.__gt__))
print(type(b.__le__))
print(type(b.__ge__))
print(type(b.__getattr__))
print(type(b.__setattr__))
print(type(b.__delattr__))
print(type(b.__getattribute__))
print(type(b.__setitem__))
print(type(b.__delitem__))
print(type(b.__call__))
print(type(b.__re
