from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a==b)
print(a is b)
print(a.__next__())
print(b.__next__())
print(a.__next__())
print(b.__next__())
print(a==b)
print(a is b)
print(FunctionType)
print(type(a) is FunctionType)
print(type(a) is type(b))
print(type(a) is type)
print(type(a) is type)
print(type(a) is type(type))
print(type(type) is type)
print(type(type) is type(type))
print(type(type) is type(FunctionType))
print(type(FunctionType) is type)
print(type(FunctionType) is type(type))
print(type(FunctionType) is type(FunctionType))
print(type(FunctionType) is type(type(FunctionType)))
print(type(FunctionType) is type(type(type)))
print(type(FunctionType) is type(type(type(
