from types import FunctionType
a = (x for x in [1])
print(type(a))
print(type(a.__next__))
print(type(a.__iter__))
print(type(a.send))
print(type(a.throw))
print(type(a.close))
print(type(a.__await__))
print(type(a.__aiter__))
print(type(a.__anext__))
print(type(a.__aenter__))
print(type(a.__aexit__))

print(isinstance(a.__next__, FunctionType))
print(isinstance(a.__iter__, FunctionType))
print(isinstance(a.send, FunctionType))
print(isinstance(a.throw, FunctionType))
print(isinstance(a.close, FunctionType))
print(isinstance(a.__await__, FunctionType))
print(isinstance(a.__aiter__, FunctionType))
print(isinstance(a.__anext__, FunctionType))
print(isinstance(a.__aenter__, FunctionType))
print(isinstance
