from types import FunctionType
a = (x for x in [1])
print(type(a))
print(type(a.__iter__))
print(type(a.__iter__()) == a)
print(type(a.__iter__()) == a.__iter__())
print(type(a.__iter__()) == iter(a))
print(type(a.__iter__()) == iter(a.__iter__()))
print(type(a.__iter__()) == iter(iter(a)))
print(type(a.__iter__()) == iter(iter(a.__iter__())))
print(type(a.__iter__()) == iter(iter(iter(a))))
print(type(a.__iter__()) == iter(iter(iter(a.__iter__()))))
print(type(a.__iter__()) == iter(iter(iter(iter(a)))))
print(type(a.__iter__()) == iter(iter(iter(iter(a.__iter__())))))
print(type(a.__iter__()) == iter(iter(iter(iter(iter(a))))))
print(type(a
