from types import FunctionType
list(FunctionType(lambda: None, globals()))

# type
# type(1)
# type(1.0)
# type(1+2j)
# type('a')
# type(b'a')
# type(True)
# type(None)
# type(type)
# type(type(1))
# type(lambda: None)
# type(lambda: None())
# type(lambda: None)()
# type(lambda: None())()
# type(lambda: None())()()
# type(lambda: None())()()()

# type(type)
# type(type(type))
# type(type(type(type)))
# type(type(type(type(type))))
# type(type(type(type(type(type)))))

# type(1)(1)
# type(1)(1.0)
# type(1)(1+2j)
# type(1)('a')
# type(1)(b'a')
# type(1)(True)
# type(1)(None)
# type(1)(type)
