from types import FunctionType
a = (x for x in [1])
print(isinstance(a, GeneratorType))
print(isinstance(a, FunctionType))
print(isinstance(a, type(iter([1]))))
print(isinstance(a, type([1])))
print(isinstance(a, type({1: 1})))
print(isinstance(a, type(set([1]))))
print(isinstance(a, type(frozenset([1]))))
print(isinstance(a, type(dict([(1, 1)]))))
print(isinstance(a, type(1)))
print(isinstance(a, type(1.0)))
print(isinstance(a, type('1')))
print(isinstance(a, type(b'1')))
print(isinstance(a, type(True)))
print(isinstance(a, type(None)))
print(isinstance(a, type(object)))
print(isinstance(a, type(object())))
print(isinstance(a, type({})))
print(isinstance(a, type([])))
print(isinstance(a, type(())))
