from types import FunctionType
a = (x for x in [1])
print(type(a))
b = FunctionType
print(type(b))
print(type(b) == type(a))
print(type(b) is type(a))
print(type(b) == type(FunctionType))
print(type(b) is type(FunctionType))
print(type(b) == type(FunctionType()))
print(type(b) is type(FunctionType()))
print(type(b) == FunctionType)
print(type(b) is FunctionType)
print(type(b) == FunctionType())
print(type(b) is FunctionType())
print(type(b) == type)
print(type(b) is type)
print(type(b) == type())
print(type(b) is type())
print(type(b) == type(type))
print(type(b) is type(type))
print(type(b) == type(type()))
print(type(b) is type(type()))
print(type(b) == type(type(type)))
print(type(b) is type(
