import types
# Test types.FunctionType
# Test types.LambdaType
# Test types.GeneratorType
# Test types.ClassType
# Test types.TypeType
# Test types.BuiltinFunctionType
# Test types.BuiltinMethodType
# Test types.MethodType
# Test types.UnboundMethodType
# Test types.ModuleType
# Test types.InstanceType
# Test types.FileType
# Test types.XRangeType
# Test types.SliceType
# Test types.TracebackType
# Test types.FrameType
# Test types.BufferType
# Test types.DictProxyType
# Test types.NotImplementedType
# Test types.GetSetDescriptorType
# Test types.MemberDescriptorType
# Test types.DictType
# Test types.ListType
# Test types.TupleType
# Test types.StringType
# Test types.UnicodeType
# Test types.IntType
# Test types.LongType
# Test types.FloatType
# Test types.ComplexType
# Test types.NoneType
# Test types.BooleanType
# Test types.Ellips
