from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a == b)
print(id(a) == id(b))
print(type(a) == type(b))
print(isinstance(a, GeneratorType))
print(isinstance(a, FunctionType))
print(isinstance(a, tuple))
print(isinstance(a, list))
print(isinstance(a, dict))
print(isinstance(a, set))
print(isinstance(a, frozenset))
print(isinstance(a, str))
print(isinstance(a, bytes))
print(isinstance(a, bytearray))
print(isinstance(a, range))
print(isinstance(a, memoryview))
print(isinstance(a, type))
print(isinstance(a, object))

print(type(a) == type(b))
print(isinstance(a, type(b)))
print(isinstance(a, GeneratorType))
print(isinstance(a, FunctionType))
print(isinstance(a, tuple))
print(isinstance(a,
