from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a is b)
print(type(a))
print(type(b))
print(FunctionType)
print(type(FunctionType))
print(type(FunctionType) is type)
print(type(a) is type)
print(type(a) is type(b))
print(type(a) is type(FunctionType))
print(type(a) is type(type))
print(type(a) is type(type(a)))
print(type(a) is type(type(b)))
print(type(a) is type(type(FunctionType)))
print(type(a) is type(type(type)))
print(type(a) is type(type(type(a))))
print(type(a) is type(type(type(b))))
print(type(a) is type(type(type(FunctionType))))
print(type(a) is type(type(type(type))))
print(type(a) is type(type(type(type(a)))))
print(type(a) is type(
