from types import FunctionType
a = (x for x in [1])
print(type(a))
print(type(a.__iter__))
print(type(a.__next__))
print(type(a.__next__()))
print(type(iter([1])))
print(type(iter([])))
print(type(iter(set())))
print(type(iter(dict())))
print(type(iter(range(1))))
print(type(iter(FunctionType)))
print(type(iter(FunctionType.__call__)))
print(type(iter(FunctionType.__call__.__call__)))
print(type(iter(FunctionType.__call__.__call__.__call__)))
print(type(iter(FunctionType.__call__.__call__.__call__.__call__)))
print(type(iter(FunctionType.__call__.__call__.__call__.__call__.__call__)))
print(type(iter(FunctionType.__call__.__call__.__call__.__call__.__call__.__call__)))
print(type(iter(FunctionType.
