from types import FunctionType
list(FunctionType(lambda: None, globals(), 'foo'))

# __name__
# __qualname__
# __annotations__
# __kwdefaults__
# __defaults__
# __code__
# __globals__
# __closure__
# __dict__
# __doc__
# __module__
# __text_signature__
# __get__
# __call__
# __new__
# __init__
# __prepare__
# __subclasses__
# __init_subclass__
# __class_getitem__
# __instancecheck__
# __subclasscheck__
# __delattr__
# __dir__
# __format__
# __getattribute__
# __hash__
# __init_subclass__
# __new__
# __reduce__
# __reduce_ex__
# __repr__
# __setattr__
# __sizeof__
# __str__
# __subclasshook__
# __weakref__
# __get__
# __set__
# __delete__
# __set_name__
