from types import FunctionType
a = (x for x in [1])
print(type(a))
print(type(a.__iter__))
print(type(a.__iter__()) == a)
print(type(a.__next__))
print(type(a.__next__()) == int)
print(type(a.send))
print(type(a.send(None)) == int)
print(type(a.throw))
print(type(a.throw(StopIteration)) == int)
print(type(a.close))
print(type(a.close()) == None)
print(type(a.gi_frame))
print(type(a.gi_frame) == type(None))
print(type(a.gi_running))
print(type(a.gi_running) == bool)
print(type(a.gi_code))
print(type(a.gi_code) == type(None))
print(type(a.gi_yieldfrom))
print(type(a.gi_yieldfrom) == type(None))
print(type(a.__await__))
print(type(a.
