from types import FunctionType
a = (x for x in [1])
b = (x for x in [2])
print(a)
print(b)
print(type(a))
print(type(b))
print(a.gi_frame.f_lasti)
print(b.gi_frame.f_lasti)
print(a.gi_frame.f_locals)
print(b.gi_frame.f_locals)
print(a.gi_frame.f_locals == b.gi_frame.f_locals)
print(a.gi_frame.f_code.co_name)
print(b.gi_frame.f_code.co_name)
print(a.gi_frame.f_code.co_name == b.gi_frame.f_code.co_name)
print(type(a.gi_frame.f_code.co_code))
print(type(b.gi_frame.f_code.co_code))
print(a.gi_frame.f_code.co_code == b.gi_frame.f_code.co_code)
print(a.
