from types import FunctionType
a = (x for x in [1])
print(a)
print(type(a))
#print(type(a) == types.GeneratorType)
print(type(a) == GeneratorType)
print(type(a) == FunctionType)
print(type(a) == list)

print(type(a) == type(b))
print(type(a) == type(c))
print(type(a) == type(d))
print(type(a) == type(e))
print(type(a) == type(f))
print(type(a) == type(g))
print(type(a) == type(h))
print(type(a) == type(i))
print(type(a) == type(j))
print(type(a) == type(k))
print(type(a) == type(l))
print(type(a) == type(m))
print(type(a) == type(n))
print(type(a) == type(o))
print(type(a) == type(p))
print(type(a) == type(q))
print(
