from types import FunctionType
a = (x for x in [1])
print(a)
print(type(a))
print(type(a) == GeneratorType)
print(isinstance(a, GeneratorType))
print(type(a) == Iterator)
print(isinstance(a, Iterator))
print(type(a) == Iterable)
print(isinstance(a, Iterable))
print(type(a) == FunctionType)
print(isinstance(a, FunctionType))
print('-'*40)
b = [x for x in [1]]
print(b)
print(type(b))
print(type(b) == GeneratorType)
print(isinstance(b, GeneratorType))
print(type(b) == Iterator)
print(isinstance(b, Iterator))
print(type(b) == Iterable)
print(isinstance(b, Iterable))
print(type(b) == FunctionType)
print(isinstance(b, FunctionType))
print('-'*40)
c = {x for x in [1]}
print(c)
print(type(c))
print(type(c)
