from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
c = (x for x in [1])
print(a == b)
print(a == c)
print(a is b)
print(a is c)
print(type(a) == type(b))
print(type(a) == type(c))
print(type(a) is type(b))
print(type(a) is type(c))
print(FunctionType)
print(type(a))
print(type(b))
print(type(c))
print(type(a) == FunctionType)
print(type(b) == FunctionType)
print(type(c) == FunctionType)
print(type(a) is FunctionType)
print(type(b) is FunctionType)
print(type(c) is FunctionType)
