from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a == b)
print(a is b)
print(type(a))
print(type(b))
print(type(a) == type(b))
print(type(a) is type(b))
print(type(a) == type(x for x in [1]))
print(type(a) is type(x for x in [1]))
print(type(a) == type(x for x in [2]))
print(type(a) is type(x for x in [2]))
print(type(a) == type(x for x in [1, 2]))
print(type(a) is type(x for x in [1, 2]))
print(type(a) == type(x for x in [1, 2, 3]))
print(type(a) is type(x for x in [1, 2, 3]))
print(type(a) == type(x for x in [1, 2, 3, 4]))
print(type(a) is type(x for
