from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a == b)

print(type(a))
print(type(b))
print(type(print))
print(type(FunctionType))
print(type(lambda x: x))
print(type(abs))
print(type(__build_class__))
print(type(a) == type(b))
print(type(a) == type(print))
print(type(a) == type(FunctionType))
print(type(a) == type(lambda x: x))
print(type(a) == type(abs))
print(type(a) == type(__build_class__))
print(type(print) == type(FunctionType))
print(type(print) == type(lambda x: x))
print(type(print) == type(abs))
print(type(print) == type(__build_class__))
print(type(FunctionType) == type(lambda x: x))
print(type(FunctionType) == type(abs))
print(type(FunctionType) == type(__build_
