from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a == b)
print(a is b)
print(type(a))
print(type(b))
print(type(a) == type(b))
print(type(a) is type(b))
print(type(a) == FunctionType)
print(type(a) is FunctionType)
print(type(a) == type(b) == FunctionType)
print(type(a) is type(b) is FunctionType)
print(type(a) == type(b) is FunctionType)
print(type(a) is type(b) == FunctionType)
print(type(a) == type(b) is FunctionType is True)
print(type(a) is type(b) == FunctionType is True)
print(type(a) == type(b) is FunctionType is True is False)
print(type(a) is type(b) == FunctionType is True is False)
print(type(a) == type(b) is FunctionType is True is False is True)
print(type(a) is
