from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a == b)
print(a is b)
print(type(a))
print(isinstance(a, FunctionType))
print(isinstance(a, GeneratorType))
print(isinstance(a, GeneratorExp))
print(isinstance(a, Iterator))
print(isinstance(a, Iterable))
print(isinstance(a, Iterator))
print(isinstance(a, Iterable))
print(isinstance(a, Iterator))
print(isinstance(a, Iterable))
print(isinstance(a, Iterator))
print(isinstance(a, Iterable))
print(isinstance(a, Iterator))
print(isinstance(a, Iterable))
print(isinstance(a, Iterator))
print(isinstance(a, Iterable))
print(isinstance(a, Iterator))
print(isinstance(a, Iterable))
print(isinstance(a, Iterator))
print(isinstance(a, Iterable))
print(isinstance(a, Iterator))
print(
