from types import FunctionType
a = (x for x in [1])
b = (x for x in [1, 2])
c = (x for x in (1, 2))
d = (x for x in {1, 2})
e = (x for x in {1: 2})
f = (x for x in range(10))
g = (x for x in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
h = (x for x in range(1000))
i = (x for x in range(1000000))
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(type(e))
print(type(f))
print(type(g))
print(type(h))
print(type(i))

print(isinstance(a, GeneratorType))
print(isinstance(b, GeneratorType))
print(isinstance(c, GeneratorType))
print(isinstance(d, GeneratorType))
print(isinstance(e, GeneratorType))
print(isinstance(f, GeneratorType))
print(isinstance(g
