from types import FunctionType
a = (x for x in [1])
print(type(a))
print(type(a.__next__))
print(type(a.__next__) == FunctionType)
print(a.__next__())
print(a.__next__())
print(a.__next__.__name__)
print(a.__next__.__qualname__)
print(a.__next__.__module__)
print(a.__next__.__defaults__)
print(a.__next__.__kwdefaults__)
print(a.__next__.__annotations__)
print(a.__next__.__globals__)
print(a.__next__.__closure__)
print(a.__next__.__code__)
print(a.__next__.__code__.co_argcount)
print(a.__next__.__code__.co_consts)
print(a.__next__.__code__.co_varnames)
print(a.__next__.__code__.co_names)
print(a.__next__
