from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a == b)
print(type(a))
print(type(b))
print(type(a) == type(b))
print(type(a) == type([]))
print(type(a) == type(()))
print(type(a) == type(FunctionType))
print(type(a) == type(FunctionType()))
print(type(a) == type(FunctionType))
print(type(a) == type(FunctionType()))
print(type(a) == type(FunctionType))
print(type(a) == type(FunctionType()))
print(type(a) == type(FunctionType))
print(type(a) == type(FunctionType()))
print(type(a) == type(FunctionType))
print(type(a) == type(FunctionType()))
print(type(a) == type(FunctionType))
print(type(a) == type(FunctionType()))
print(type(a) == type(FunctionType))
print(type(a) == type(FunctionType
