from types import FunctionType
a = (x for x in [1])
# print(a)
# print(type(a))
# print(isinstance(a, GeneratorType))
# print(type(a) == GeneratorType)
# print(type(a) == FunctionType)
# print(isinstance(a, FunctionType))
# print(isinstance(a, object))
# print(type(a) == object)
# print(type(a) == type)
# print(isinstance(a, type))
# print(type(a) == type)
# print(type(a) == type(object))
# print(type(a) == type(type))
# print(type(a) == type(type(object)))
# print(type(a) == type(type(type)))
# print(type(a) == type(type(type(object))))
# print(type(a) == type(type(type(type))))
# print(type(a) == type(type(type(type(object)))))
# print(type(a) == type(type(type(type(type)))))
# print(type(a)
