from types import FunctionType
a = (x for x in [1])
b = (x for x in [2])
c = (x for x in [3])
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(type(c))
print(type(a) == type(b))
print(type(a) == type(c))
print(type(b) == type(c))
print(type(a) == FunctionType)
print(type(b) == FunctionType)
print(type(c) == FunctionType)
print(type(a) == type)
print(type(b) == type)
print(type(c) == type)
print(type(a) == type(type))
print(type(b) == type(type))
print(type(c) == type(type))
print(type(a) == type(type(a)))
print(type(b) == type(type(b)))
print(type(c) == type(type(c)))
print(type(a) == type(type(b)))
print(type(a
