from types import FunctionType
list(FunctionType(lambda a: a, globals(), 'lambda'))

# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__()
# CodeType.__new__
