from types import FunctionType
a = (x for x in [1])
print(type(a))
print(type(a.__next__))
print(type(a.__next__) == FunctionType)
print(type(a.__next__) == types.FunctionType)

print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a, types.GeneratorType))
print(isinstance(a,
