import types
# Test types.FunctionType
def f(): pass
def g(): pass
def h(): pass
def i(): pass
def j(): pass
def k(): pass
def l(): pass
def m(): pass
def n(): pass
def o(): pass
def p(): pass
def q(): pass
def r(): pass
def s(): pass
def t(): pass
def u(): pass
def v(): pass
def w(): pass
def x(): pass
def y(): pass
def z(): pass
def a1(): pass
def a2(): pass
def a3(): pass
def a4(): pass
def a5(): pass
def a6(): pass
def a7(): pass
def a8(): pass
def a9(): pass
def a10(): pass
def a11(): pass
def a12(): pass
def a13(): pass
def a14(): pass
def a15(): pass
def a16(): pass
def a17(): pass
def a18(): pass
def a19(): pass
def a20(): pass
def a21(): pass
def a22(): pass
def a23(): pass
def a24(): pass
def a25(): pass
