from types import FunctionType
a = (x for x in [1])
print(type(a))
print(type(a.__iter__))
print(type(a.__next__))
print(type(a.send))
print(type(a.throw))
print(type(a.close))
print(type(a.gi_frame))
print(type(a.gi_running))
print(type(a.gi_code))
print(type(a.gi_yieldfrom))
print(type(a.gi_frame.f_lasti))
print(type(a.gi_frame.f_lineno))
print(type(a.gi_frame.f_trace))
print(type(a.gi_frame.f_exc_traceback))
print(type(a.gi_frame.f_exc_type))
print(type(a.gi_frame.f_exc_value))
print(type(a.gi_frame.f_builtins))
print(type(a.gi_frame.f_globals))
print(type(a.gi_frame.f_locals))
print(type(
