from types import FunctionType
a = (x for x in [1])
print(a)
print(type(a))
print(type(a.__next__))
print(type(a.__next__) == types.MethodType)
print(type(a.__next__) == types.FunctionType)
print(type(a.__next__) == FunctionType)
print(type(a.__next__) == types.BuiltinFunctionType)
print(type(a.__next__) == types.MethodType)
print(type(a.__next__) == types.MethodType)
print(type(a.__next__) == types.MethodType)

print(type(a.__next__) == types.MethodType)
print(type(a.__next__) == types.MethodType)
print(type(a.__next__) == types.MethodType)
print(type(a.__next__) == types.MethodType)
print(type(a.__next__) == types.MethodType)
print(type(a.__next__) == types.MethodType)
print(type(a.__next__
