from types import FunctionType
a = (x for x in [1])
print(a, type(a))
b = int(1)
print(b, type(b))

print(a.__class__.__base__)
print(b.__class__.__base__)
print(dict.__class__.__base__)
print(int.__class__.__base__)
print(set.__class__.__base__)
print(str.__class__.__base__)
print(list.__class__.__base__)
print(tuple.__class__.__base__)
print((5).__class__)
print(type(a))
print(type(b))
print(type(5))
print(type({}))
print(type(int))
print(type(FunctionType))
print(type(b.__le__))
print(type(5).__base__)
print(type({}).__base__)
print(type(int).__base__)
print(type(FunctionType).__base__)
print(type(b.__le__).__base__)

