from types import FunctionType
list(FunctionType())

# @generated from tools/build/function-types.py
class Dict(dict):
    # def __new__(cls, *args: Any, **kwargs: Any) -> Any: ...
    # def __getattribute__(self, name: str) -> Any: ...
    # def __setattr__(self, name: str, value: Any) -> None: ...
    # def __delattr__(self, name: str) -> None: ...
    # def __dir__(self) -> List[str]: ...
    # def __eq__(self, other: Any) -> bool: ...
    # def __ge__(self, other: Any) -> bool: ...
    # def __getitem__(self, key: Any) -> Any: ...
    # def __gt__(self, other: Any) -> bool: ...
    # def __init__(
    #     self,
    #     /,
    #     *args: Any,
    #     **kwargs: Any
    # ) -> None: ...
    # def __le__(self, other
