from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a is b)
print(a == b)
print(type(a))
print(type(b))
print(type(a) is type(b))
print(isinstance(a, FunctionType))
print(isinstance(a, GeneratorType))
print(isinstance(b, GeneratorType))
print(isinstance(a, Iterator))
print(isinstance(b, Iterator))
print(isinstance(a, Iterable))
print(isinstance(b, Iterable))
print(isinstance(a, Sequence))
print(isinstance(b, Sequence))
print(isinstance(a, Mapping))
print(isinstance(b, Mapping))
print(isinstance(a, MappingView))
print(isinstance(b, MappingView))
print(isinstance(a, Set))
print(isinstance(b, Set))
print(isinstance(a, Set))
print(isinstance(b, Set))
print(isinstance(a, Hashable))
print(isinstance(b, Hashable
