from types import FunctionType
a = (x for x in [1])
print(type(a))
print(type(a.__iter__))
print(type(a.__next__))
print(type(a.__next__()))
print(type(a.__iter__()))
print(type(a.__iter__().__next__))
print(type(a.__iter__().__next__()))

print(isinstance(a, object))
print(isinstance(a, Iterator))
print(isinstance(a, Iterable))
print(isinstance(a, FunctionType))
print(isinstance(a, Generator))
print(isinstance(a, GeneratorType))
print(isinstance(a, GeneratorExp))
print(isinstance(a, GeneratorExpType))
print(isinstance(a, GeneratorExpType))
print(isinstance(a, GeneratorExpType))
print(isinstance(a, GeneratorExpType))
print(isinstance(a, GeneratorExpType))
print(isinstance(a, GeneratorExpType))
print(isinstance(a, GeneratorExpType))
print(isinstance(a, GeneratorExpType
