import types
# Test types.FunctionType
# Test types.MethodType
# Test types.BuiltinFunctionType
# Test types.BuiltinMethodType
# Test types.LambdaType
# Test types.GeneratorType
# Test types.CodeType
# Test types.TracebackType
# Test types.FrameType
# Test types.BufferType
# Test types.DictProxyType
# Test types.NotImplementedType
# Test types.GetSetDescriptorType
# Test types.MemberDescriptorType
# Test types.WrapperDescriptorType
# Test types.MethodDescriptorType
# Test types.ModuleType
# Test types.FileType
# Test types.XRangeType
# Test types.SliceType
# Test types.EllipsisType
# Test types.TracebackType
# Test types.FrameType
# Test types.BufferType
# Test types.DictProxyType
# Test types.NotImplementedType
# Test types.GetSetDescriptorType
# Test types.MemberDescriptorType
# Test types.WrapperDescriptorType
# Test types.MethodDescriptor
