from types import FunctionType
list(FunctionType(FunctionType.__code__, {}).__globals__)

# and that's how we get the following:
# ['__builtins__',
#  '__doc__',
#  '__file__',
#  '__name__',
#  '__package__',
#  '_getframe',
#  '_is_type_type',
#  '_thread',
#  'abc',
#  'abstractmethod',
#  'base_exec_function',
#  'base_exec_method',
#  'base_function',
#  'base_method',
#  'base_property',
#  'base_static_method',
#  'callable',
#  'classmethod',
#  'contextmanager',
#  'coroutine',
#  'coroutinefunction',
#  'coroutinemethod',
#  'coroutine_types',
#  'function',
#  'function_types',
#  'in_coroutine_wrapper',
#  'isawaitable',
#  'isfunction',
