from types import FunctionType
a = (x for x in [1])
b = (x for x in [1])
print(a is b)
print(a == b)
print(type(a))
print(type(b))
print(type(a) == type(b))
print(type(a) is type(b))
print(type(a) == type(b) == type(FunctionType))
print(type(a) is type(b) is type(FunctionType))
print(type(a) is type(FunctionType))
print(type(b) is type(FunctionType))
print(type(FunctionType) is type(FunctionType))
print(type(FunctionType) is type)
print(type(type) is type)
print(type(type) == type)
print(type(type) == type(type))
print(type(type) is type(type))
print(type(type) is type)
print(type(type) == type)
print(type(type) == type(type))
print(type(type) is type(type))
print(type(type) is type)
print(type(type)
