from types import FunctionType
a = (x for x in [1])
b = [x for x in [1]]
c = {x for x in [1]}
d = {x: x for x in [1]}
e = FunctionType(lambda: None, globals())
f = type(lambda: None)
g = type(lambda: None)()
h = type(lambda: None)
i = type(lambda: None)()
j = type(lambda: None)
k = type(lambda: None)()
l = type(lambda: None)
m = type(lambda: None)()
n = type(lambda: None)
o = type(lambda: None)()
p = type(lambda: None)
q = type(lambda: None)()
r = type(lambda: None)
s = type(lambda: None)()
t = type(lambda: None)
u = type(lambda: None)()
v = type(lambda: None)
w = type(lambda: None)()
x = type(lambda: None)
y = type(lambda: None)()
z = type(lambda: None)
A = type(lambda: None
