import gc, weakref
from . import _coconut_tco
from . import _coconut_igetitem
from . import _coconut_base_compose
from . import _coconut_forward_compose
from . import _coconut_back_compose
from . import _coconut_forward_star_compose
from . import _coconut_back_star_compose
from . import _coconut_pipe
from . import _coconut_star_pipe
from . import _coconut_back_pipe
from . import _coconut_back_star_pipe
from . import _coconut_bool_and
from . import _coconut_bool_or
from . import _coconut_none_coalesce
from . import _coconut_minus
from . import _coconut_map
from . import _coconut_partial
from . import _coconut_get_function_match_error
from . import _coconut_base_pattern_func
from . import _coconut_addpattern
from . import _c
