import gc, weakref
from collections import defaultdict

from . import _pytest
from . import config
from . import nodes
from . import runner
from . import hookspec
from . import main
from . import reporting
from . import python
from . import assertion
from . import deprecated
from . import fixtures
from . import monkeypatch
from . import skip
from . import capture
from . import loggingplugin
from . import exit
from . import debug
from . import __version__
from . import _code
from . import _outcomes
from . import _io
from . import _pluginmanager
from . import _pyfunc
from . import _version
from . import _multicall
from . import _argcomplete
from . import _argcomplete_util
from . import _pytest_argcomplete
from . import _terminal
from . import _pytestconfig
from . import _collectonly
from . import _nodes
from . import _fixtures
from . import _pytest_warnings
from . import _pytest_bdd
from . import _pytest_cache
from . import _pytest_capture
from .
