import gc, weakref, sys

from . import _util
from ._util import _get_docstring
from ._util import _get_docstring_all
from ._util import _get_docstring_all_brief
from ._util import _get_docstring_brief
from ._util import _get_docstring_parameters
from ._util import _get_docstring_returns
from ._util import _get_docstring_summary
from ._util import _get_docstring_title
from ._util import _get_docstring_type
from ._util import _get_docstring_usage
from ._util import _get_docstring_version
from ._util import _get_docstring_warnings
from ._util import _get_docstring_yields
from ._util import _get_docstring_yields_brief
from ._util import _get_docstring_yields_parameters
from ._util import _get_docstring_yields_returns
from ._util import _get_docstring_yields_summary
from ._util import _get_docstring_yields_title
