import gc, weakref
from collections import defaultdict

from . import _core
from . import _util
from . import _ffi
from . import _ffi_api
from . import _ffi_utils
from . import _types
from . import _weakref
from . import _weakref_proxy
from . import _weakref_backport
from . import _weakref_dict
from . import _weakref_finalize
from . import _weakref_list
from . import _weakref_weaklist
from . import _weakref_weakmethod
from . import _weakref_weakset
from . import _weakref_weakvalue
from . import _weakref_weakcallableproxy
from . import _weakref_weakproxy
from . import _weakref_finalize_ref
from . import _weakref_callbacks
from . import _weakref_proxy_ref
from . import _weakref_weakmethod_proxy
from . import _weakref_weakcallableproxy_ref
from . import _weakref_weakproxy_ref
from . import _weakref_weakkeydict
from . import _weakref
