import gc, weakref

from . import _core
from . import _util
from . import _compat
from . import _thread
from . import _weakref
from . import _weakrefset
from . import _weakkeydict
from . import _weakkeydefaultdict
from . import _weakrefdict
from . import _weakrefdefaultdict
from . import _weakcallableproxy
from . import _weakproxy
from . import _finalize
from . import _idle
from . import _make
from . import _test
from . import _tracemalloc
from . import _debug
from . import _dummy_thread
from . import _dummy_threading
from . import _dummy_threading_local
from . import _dummy_queue
from . import _dummy_subprocess
from . import _dummy_multiprocessing
from . import _dummy_win32api
from . import _dummy_win32pipe
from . import _dummy_win32event
from . import _dummy_win32file
from . import _dummy_win32security
from . import _
