import gc, weakref
from collections import defaultdict
from itertools import count

from . import _utils
from . import _compat
from . import _types
from . import _functions
from . import _classes
from . import _methods
from . import _attributes
from . import _properties
from . import _constructors
from . import _enums
from . import _flags
from . import _objects
from . import _signals
from . import _vfuncs
from . import _interfaces
from . import _classes
from . import _constants
from . import _errors
from . import _deprecated
from . import _version
from . import _overrides

from . import _utils
from . import _compat
from . import _types
from . import _functions
from . import _classes
from . import _methods
from . import _attributes
from . import _properties
from . import _constructors
from . import _enums
from . import _flags
from . import _objects
from . import _signals
from . import _vfuncs
from . import _interfaces
