import gc, weakref

from . import _pyglet
from . import compat_platform
from . import gl
from . import image
from . import resources
from . import sprite
from . import text
from . import window
from . import event
from . import media
from . import clock
from . import font
from . import glu
from . import app
from . import image
from . import resource
from . import sprite
from . import text
from . import window
from . import event
from . import media
from . import clock
from . import font
from . import glu
from . import app
from . import image
from . import resource
from . import sprite
from . import text
from . import window
from . import event
from . import media
from . import clock
from . import font
from . import glu
from . import app
from . import image
from . import resource
from . import sprite
from . import text
from . import window
from . import event
from . import media
from . import clock
from . import font
from . import glu
from . import app
from . import image
from . import resource
