import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()
gc.collect()
print(gc.collect())
# Test gc.get_objects()
print(gc.get_objects())
# Test gc.get_referrers()
print(gc.get_referrers(gc))
# Test gc.get_referents()
print(gc.get_referents(gc))
# Test gc.get_threshold()
print(gc.get_threshold())
# Test gc.set_threshold()
gc.set_threshold(700, 10, 10)
print(gc.get_threshold())
# Test gc.is_tracked()
print(gc.is_tracked(gc))
# Test gc.set_debug()
gc.set_debug(gc.DEBUG_UNCOLLECTABLE)
print(gc.get_debug())
gc.set_debug(gc.DEBUG_COLLECTABLE)
print(gc.get_debug())
gc.set_debug(gc.DEBUG_STATS)
print(gc.get_debug())
gc.set_debug(gc.DEBUG_LE
