import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()
class A:
    def __del__(self):
        print("del", self)

def callback(x):
    print("callback", x)

a = A()
a_id = id(a)
wref = weakref.ref(a, callback)
del a
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
gc.collect()
print("gc.collect")
