import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()
gc.collect()
# Test gc.get_stats()
gc.get_stats()
# Test gc.set_threshold()
gc.set_threshold()
gc.set_threshold(-1)
gc.set_threshold('a')
gc.set_threshold(1, 1, 1, 1)
gc.set_threshold(1, 1, 1)
gc.set_threshold(1, 1)
gc.set_threshold(1)
gc.set_threshold(1000, 1000, 1000, 1000)
gc.set_threshold(10, 1, 1, 1)
gc.set_threshold(10, 10, 10, 10)
weakref.ref(object())

# Test gc.get_threshold()
gc.get_threshold()
gc.set_threshold(1, 1, 1)
gc.get_threshold()
gc.set_threshold(1, 1)
gc.get_threshold()
gc.set_threshold(1)
gc.get_threshold()
# Test gc
