import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()
gc.collect()
# Test gc.disable() and gc.isenabled()
assert gc.isenabled()
gc.disable()
assert not gc.isenabled()
gc.enable()
assert gc.isenabled()
# Test gc.get_count()
gc.collect()
c1 = gc.get_count()
gc.collect()
c2 = gc.get_count()
assert c1 == c2
l = []
gc.collect()
c1 = gc.get_count()
l.append(l)
gc.collect()
c2 = gc.get_count()
assert c2 > c1
# Test gc.get_debug()
gc.collect()
gc.set_debug(gc.DEBUG_COLLECTABLE)
gc.collect()
gc.set_debug(gc.DEBUG_UNCOLLECTABLE)
gc.collect()
gc.set_debug(0)
gc.collect()
# Test gc.get_objects()
gc.collect()
l0 = gc.get_objects()
l = []
