import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()
gc.collect()
# Test gc.get_count()
gc.get_count()
# Test gc.get_threshold()
gc.get_threshold()
# Test gc.set_threshold()
gc.set_threshold(100, 10, 10)
# Test gc.get_objects()
print(len(gc.get_objects()))
# Test gc.get_referrers()
print(len(gc.get_referrers(gc)))
# Test gc.get_referents()
print(len(gc.get_referents(gc)))
# Test gc.is_tracked()
gc.is_tracked(gc)
# Test gc.collect()
gc.collect()
# Test gc.garbage
print(len(gc.garbage))
# Test gc.enable()
gc.enable()
# Test gc.disable()
gc.disable()
# Test gc.isenabled()
gc.isenabled()
# Test gc.set_debug()
gc.set_debug(gc.
