import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()
gc.collect()
# Test gc.get_referrers()
gc.get_referrers(gc)
# Test gc.get_referents()
gc.get_referents(gc)
# Test gc.get_objects()
gc.get_objects()
# Test gc.get_stats()
gc.get_stats()
# Test gc.garbage
gc.garbage
# Test gc.get_threshold()
gc.get_threshold()
# Test gc.set_threshold()
gc.set_threshold(1000, 10, 10)
gc.get_threshold()
# Test gc.enable()
gc.enable()
# Test gc.disable()
gc.disable()
# Test gc.isenabled()
gc.isenabled()
# Test gc.set_debug()
gc.set_debug(gc.DEBUG_LEAK)
# Test gc.get_debug()
gc.get_debug()
# Test gc.set_debug()
gc.set_debug(gc.DEBUG_ST
