import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()
# Test gc.disable()
# Test gc.enable()
# Test gc.isenabled()
# Test gc.collect()

# Test gc.get_threshold()
# Test gc.set_threshold()
# Test gc.get_count()
# Test gc.set_debug()
# Test gc.get_debug()
# Test gc.set_debug()
# Test gc.get_referrers()
# Test gc.get_objects()
# Test gc.get_stats()
# Test gc.is_tracked()
# Test gc.set_threshold()
# Test gc.get_threshold()

# Test gc.get_objects()

# Test gc.get_stats()
# Test gc.get_referents()
# Test gc.garbage()
# Test gc.set_debug()
# Test gc.is_tracked()
# Test gc.get_debug()
# Test gc.set_debug()
# Test gc.is_tr
