import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect() in all the ways it can be called.
gc.collect()
gc.collect(2)
gc.collect(1)
gc.collect(0)
gc.collect(generation=0)
gc.collect(generation=1)
gc.collect(generation=2)
gc.collect(0, 2)
gc.collect(0, 1)
gc.collect(1, 2)
gc.collect(0, 1, 2)
gc.collect(generation=(0,1))
gc.collect(generation=(0,1),0)
gc.collect(generation=(0,1),1)
gc.collect(generation=(0,1),2)
gc.collect(generation=(0,1),0,1)
gc.collect(generation=(0,1),0,1,2)
gc.collect(generation=(0,1),1,2)
gc.collect(0, generation=(0,1))
gc.collect(1, generation=(0,1))
gc.collect(2, generation=(0,1))
gc.collect(0, 1, generation=(0,1))
gc.
