import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()

class A:
    def __init__(self):
        self.b = B(self)
        self.c = C(self)
        self.d = D(self)
        self.e = E(self)
        self.f = F(self)
        self.g = G(self)
        self.h = H(self)
        self.i = I(self)
        self.j = J(self)
        self.k = K(self)
        self.l = L(self)
        self.m = M(self)
        self.n = N(self)
        self.o = O(self)
        self.p = P(self)
        self.q = Q(self)
        self.r = R(self)
        self.s = S(self)
        self.t = T(self)
        self.u = U(self)
        self.v = V(self)
        self.w = W(self)
        self.x = X(self)
        self.y = Y(self)
