import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()
gc.collect()
gc.collect()
# Test gc.garbage
#gc.garbage.append(1)
#gc.garbage.append(2)
#gc.garbage.append(3)
#gc.garbage.append(4)
#gc.garbage.append(5)
#gc.garbage.append(6)
#gc.garbage.append(7)
#gc.garbage.append(8)
#gc.garbage.append(9)
#gc.garbage.append(10)
#gc.garbage.append(11)
#gc.garbage.append(12)
#gc.garbage.append(13)
#gc.garbage.append(14)
#gc.garbage.append(15)
#gc.garbage.append(16)
#gc.garbage.append(17)
#gc.garbage.append(18)
#gc.garbage.append(19)
#gc.garbage.append(20)
#gc.garbage.append(21)
#gc.gar
