import gc, weakref
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.collect()
gc.collect()
# Test gc.garbage
gc.garbage
# Test gc.get_debug()
gc.get_debug()
# Test gc.get_threshold()
gc.get_threshold()
# Test gc.set_debug()
gc.set_debug(gc.DEBUG_LEAK)
gc.set_debug(gc.DEBUG_UNCOLLECTABLE)
gc.set_debug(gc.DEBUG_SAVEALL)
gc.set_debug(gc.DEBUG_STATS)
gc.set_debug(gc.DEBUG_COLLECTABLE)
# Test gc.set_threshold()
gc.set_threshold(1, 2, 3)
# Test gc.get_count()
gc.get_count()
# Test gc.set_threshold()
gc.set_threshold(1, 2, 3)
# Test gc.get_referrers()
gc.get_referrers(1)
# Test gc.get_referents()
gc.get_referents(1)
# Test
