gi = (i for i in ())
# Test gi.gi_code
# Test gi.gi_frame
# Test gi.gi_running
# Test gi.gi_yieldfrom
# Test gi.gi_name
# Test gi.gi_qualname
# Test gi.gi_weakreflist
# Test gi.gi_exc_state
# Test gi.gi_exc_traceback
# Test gi.gi_exc_type
# Test gi.gi_exc_value
# Test gi.gi_frame.f_code
# Test gi.gi_frame.f_lasti
# Test gi.gi_frame.f_trace
# Test gi.gi_frame.f_back
# Test gi.gi_frame.f_builtins
# Test gi.gi_frame.f_globals
# Test gi.gi_frame.f_lasti
# Test gi.gi_frame.f_lineno
# Test gi.gi_frame.f_locals
# Test gi.gi_frame.f_restricted
# Test gi.gi_frame.f_trace
