gi = (i for i in ())
# Test gi.gi_code
# Test gi.gi_frame
# Test gi.gi_running
# Test gi.gi_yieldfrom
# Test gi.gi_frame.f_lasti
# Test gi.gi_frame.f_lineno
# Test gi.gi_frame.f_trace
# Test gi.gi_frame.f_trace_lines
# Test gi.gi_frame.f_trace_opcodes
# Test gi.gi_frame.f_code.co_name
# Test gi.gi_frame.f_code.co_filename
# Test gi.gi_frame.f_code.co_firstlineno
# Test gi.gi_frame.f_code.co_flags
# Test gi.gi_frame.f_code.co_code
# Test gi.gi_frame.f_code.co_consts
# Test gi.gi_frame.f_code.co_names
# Test gi.gi_frame.f_code.co_varnames
# Test gi.gi_frame.f_code
