gi = (i for i in ())
# Test gi.gi_code
# Test gi.gi_frame
# Test gi.gi_running
# Test gi.gi_yieldfrom
# Test gi.gi_yieldfrom
# Test gi.gi_name
# Test gi.gi_name
# Test gi.gi_name
# Test gi.gi_qualname
# Test gi.gi_weakreflist
# Test gi.gi_finalizer
# Test gi.gi_weakreflist
# Test gi.gi_weakreflist
l = list(gi)
l = list(gi)
# Test gi.gi_code
# Test gi.gi_frame
# Test gi.gi_running
# Test gi.gi_yieldfrom
# Test gi.gi_yieldfrom
# Test gi.gi_name
# Test gi.gi_name
# Test gi.gi_name
# Test gi.gi_qualname
# Test gi.gi_weakreflist
# Test gi.gi_finalizer
# Test gi.gi_weakre
