gi = (i for i in ())
# Test gi.gi_code
# Test gi.gi_frame
# Test gi.gi_running
# Test gi.gi_yieldfrom
# Test gi.__name__
# Test gi.__qualname__
# Test gi.__module__
# Test gi.__annotations__
# Test gi.__dict__
# Test gi.__code__
# Test gi.__weakref__
# Test gi.send
# Test gi.throw
# Test gi.close
# Test gi.gi_frame.f_lasti
# Test gi.gi_frame.f_lineno
# Test gi.gi_frame.f_trace
# Test gi.gi_frame.f_exc_traceback
# Test gi.gi_frame.f_exc_type
# Test gi.gi_frame.f_exc_value
# Test gi.gi_frame.f_restricted
# Test gi.gi_frame.f_builtins
# Test gi.gi_frame.f_back
# Test gi.gi_frame.f_
