gi = (i for i in ())
# Test gi.gi_code.co_filename
# Test gi.gi_frame.f_code.co_filename
# Test gi.gi_code.co_name
# Test gi.gi_frame.f_code.co_name
# Test gi.gi_frame.f_lineno
# Test gi.gi_code.co_filename
# Test gi.gi_frame.f_code.co_filename
# Test gi.gi_code.co_name
# Test gi.gi_frame.f_code.co_name
# Test gi.gi_frame.f_lineno
# Test gi.gi_code.co_filename
# Test gi.gi_frame.f_code.co_filename
# Test gi.gi_code.co_name
# Test gi.gi_frame.f_code.co_name
# Test gi.gi_frame.f_lineno
# Test gi.gi_code.co_filename
# Test gi.gi_frame.f_code.co_filename
# Test gi.gi_code.co_
