import io.reactivex.Observable
import io.reactivex.Single
import io.reactivex.android.schedulers.AndroidSchedulers
import io.reactivex.functions.BiFunction
import io.reactivex.schedulers.Schedulers
import net.samystudio.beaver.data.manager.UserManager
import net.samystudio.beaver.data.model.User
import net.samystudio.beaver.data.remote.auth.AuthInterface
import net.samystudio.beaver.data.remote.user.UserInterface
import net.samystudio.beaver.di.qualifier.ActivityDisposable
import net.samystudio.beaver.di.scope.FragmentScope
import net.samystudio.beaver.ext.addTo
import net.samystudio.beaver.ui.base.fragment.BaseViewModelFragment
import net.samystudio.beaver.ui.base.viewmodel.BaseViewModel
import net.samystudio.be
