import io.reactivex.Observable
import io.reactivex.Single
import io.reactivex.android.schedulers.AndroidSchedulers
import io.reactivex.disposables.CompositeDisposable
import io.reactivex.functions.Consumer
import io.reactivex.schedulers.Schedulers
import ru.mos.polls.base.ui.ViewModelFragment
import ru.mos.polls.databinding.FragmentCalendarBinding
import ru.mos.polls.databinding.FragmentMonthCalendarBinding
import ru.mos.polls.databinding.FragmentWeekCalendarBinding
import ru.mos.polls.event.gui.adapter.DayAdapter
import ru.mos.polls.event.gui.adapter.EventAdapter
import ru.mos.polls.event.gui.adapter.WeekAdapter
import ru.mos.polls.event.model.Event
import ru.mos.polls.event.model.EventList
import ru.mos.polls.event.model
