import io.reactivex.Observable
import io.reactivex.Single
import io.reactivex.disposables.CompositeDisposable
import io.reactivex.disposables.Disposable
import io.reactivex.rxkotlin.addTo
import io.reactivex.rxkotlin.subscribeBy
import io.reactivex.schedulers.Schedulers
import io.reactivex.subjects.PublishSubject
import io.reactivex.subjects.Subject
import kotlinx.coroutines.experimental.launch
import net.dankito.deepthought.data.model.DeepThought
import net.dankito.deepthought.data.model.DeepThoughtApplication
import net.dankito.deepthought.data.model.Entry
import net.dankito.deepthought.data.model.Tag
import net.dankito.deepthought.data.persistence.db.BaseEntity
import net.dankito.deepthought.data.persistence.db.TableConfig
import net.dankito
