import io.quarkus.panache.common.Sort;
//import io.quarkus.resteasy.common.ResteasyRecorder;
//import io.quarkus.vertx.http.runtime.security.AuthenticationRedirectHandler;
//import io.quarkus.vertx.http.runtime.security.CachingAuthenticationMechanism;
//import io.quarkus.vertx.http.runtime.security.ChallengeData;
//import io.quarkus.vertx.http.runtime.security.HttpAuthenticator;
//import io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder;
import io.quarkus.vertx.http.runtime.security.QuarkusHttpUser;
//import io.quarkus.vertx.http.runtime.security.QuarkusPrincipal;
//import io.quarkus.vertx.http.runtime.security.QuarkusSecurityIdentity;
//import io.quarkus.vertx.http.runtime.security.SecurityPathMatcher;
//import io.quarkus.vertx.http
