import io.vertigo.core.lang.Assertion;
import io.vertigo.core.node.Node;
import io.vertigo.core.node.component.Connector;
import io.vertigo.core.node.component.aop.Aspect;
import io.vertigo.core.node.component.aop.AspectMethodInvocation;
import io.vertigo.core.node.config.ModuleConfig;
import io.vertigo.core.node.config.NodeConfig;
import io.vertigo.core.node.definition.Definition;
import io.vertigo.core.node.definition.DefinitionSpace;
import io.vertigo.core.node.definition.DefinitionSupplier;
import io.vertigo.core.node.definition.DefinitionUtil;
import io.vertigo.core.node.definition.Injectable;
import io.vertigo.core.node.definition.ModuleDefinition;
import io.vertigo.core.node.definition.ProxyAspectDefinition;
import io.vertigo.core.node.definition.SimpleDefinitionProvider;
import io.vertigo.core.
