import io
# Test io.RawIOBase
# Test io.BufferedIOBase
# Test io.TextIOBase
# Test io.BytesIO
# Test io.StringIO
# Test io.BytesIO
# Test io.StringIO
# Test io.FileIO
# Test io.RawIOBase
# Test io.BufferedIOBase
# Test io.TextIOBase
# Test io.BytesIO
# Test io.StringIO
# Test io.BytesIO
# Test io.StringIO
# Test io.FileIO
# Test io.RawIOBase
# Test io.BufferedIOBase
# Test io.TextIOBase
# Test io.BytesIO
# Test io.StringIO
# Test io.BytesIO
# Test io.StringIO
# Test io.FileIO
# Test io.RawIOBase
# Test io.BufferedIOBase
# Test io.TextIOBase
# Test io.BytesIO
# Test io.StringIO
# Test io.BytesIO
# Test io.StringIO
# Test io.FileIO
# Test io.RawIOBase
# Test io.BufferedIOBase
# Test io.Text
