import io
# Test io.RawIOBase
# io.RawIOBase
# io.RawIOBase.close
# io.RawIOBase.closed
# io.RawIOBase.fileno
# io.RawIOBase.flush
# io.RawIOBase.isatty
# io.RawIOBase.read
# io.RawIOBase.readable
# io.RawIOBase.readinto
# io.RawIOBase.readline
# io.RawIOBase.readlines
# io.RawIOBase.seek
# io.RawIOBase.seekable
# io.RawIOBase.tell
# io.RawIOBase.truncate
# io.RawIOBase.writable
# io.RawIOBase.write
# io.RawIOBase.writelines
# io.RawIOBase.__init__
# io.RawIOBase.__repr__
# io.RawIOBase.__str__
# io.RawIOBase.detach
# io.RawIOBase.readall
# io.RawIOBase.readinto1
# io.RawIOBase.read1
# io.RawIOBase.pe
