import io
# Test io.RawIOBase
import pickle
import sre_parse
import sre_constants
import _markupbase
import collections
import keyword
import operator
import os
import posixpath
import re
import shlex
import stat
import threading
import time
import unicodedata
import functools
import ntpath
import _bisect
import _bootlocale
import _codecs
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _collections
import _csv
import _heapq
import _io
import _locale
import _lsprof
import _multibytecodec
import _multiprocessing
import _random
import _sha1
import _sha256
import _sha512
import _socket
import _sre
import _strptime
import _struct
import _symtable
import _testcapi
import _threading_local
import _weakref
import array
import binasci
