import io
# Test io.RawIOBase
# Test io.BufferedIOBase
# Test io.TextIOBase
# Test io.BytesIO
# Test io.StringIO
# Test io.FileIO
# Test io.BufferedReader
# Test io.BufferedWriter
# Test io.BufferedRWPair
# Test io.BufferedRandom
# Test io.TextIOWrapper
# Test io.StringIO
# Test io.BytesIO
# Test io.open
# Test io.BytesIO.read
# Test io.BytesIO.readline
# Test io.BytesIO.readlines
# Test io.BytesIO.write
# Test io.BytesIO.writelines
# Test io.BytesIO.truncate
# Test io.BytesIO.seek
# Test io.BytesIO.tell
# Test io.BytesIO.close
# Test io.BytesIO.getvalue
# Test io.BytesIO.getbuffer
# Test io.BytesIO.fileno
# Test io.BytesIO.isatty
# Test io.BytesIO.readable
# Test io.BytesIO.writable
# Test io.BytesIO
