import io
class File(io.RawIOBase):
    def read(self, n=-1):
        # ...
        return b""
    def readinto(self, buf):
        # ...
        return 0
    def write(self, b):
        # ...
        return len(b)
    def fileno(self):
        # ...
        return -1
    def seek(self, pos, whence=0):
        # ...
        return 0
    def tell(self):
        # ...
        return 0
    def truncate(self, pos=None):
        # ...
        return 0
    def flush(self):
        # ...
        return 0
    def close(self):
        # ...
        pass
    def detach(self):
        # ...
        return self
    def readline(self, size=-1):
        # ...
        return b""
    def readlines(self, hint=-1):
        # ...
        return []
    def __iter__(self):
        # ...
        return iter([])
    def writelines(self, lines):
        # ...
        return None
    def
