import io
class File(io.RawIOBase):
    def read(self, size=-1):
        ...
    def write(self, b):
        ...
    def flush(self):
        ...
    def close(self):
        ...

class BufferedIOBase(io.RawIOBase):
    def read(self, n=-1):
        ...
    def write(self, b):
        ...
    def raw(self):
        ...
    def flush(self):
        ...
    def detach(self):
        ...
    def close(self):
        ...

class BytesIO(BufferedIOBase):
    def getvalue(self):
        ...
    def read(self, n=-1):
        ...
    def read1(self, n=-1):
        ...
    def write(self, b):
        ...
    def truncate(self, pos=None):
        ...
    def seek(self, pos, whence=0):
        ...
    def tell(self):
        ...

class BufferedReader(BufferedIOBase):
    def read(self, n=-1):
       
