import lzma
lzma.LZMADecompressor().decompress(open("data.lzma", "rb").read())
f = open("data.lzma", "rb")
decomp = lzma.LZMADecompressor()
decomp.decompress(f.read()[0])
f.close()
f = open("data.lzma", "rb")
decomp = lzma.LZMADecompressor()
decomp.decompress(f.read())
f.close()
f = open("data.lzma", "rb")
decomp = lzma.LZMADecompressor()
decomp.decompress(f.read(), max_length=38)
f.close()
f = open("data.lzma", "rb")
decomp = lzma.LZMADecompressor()
decomp.decompress(f.read(), max_length=36)
f.close()
f = open("data.lzma", "rb")
decomp = lzma.LZM
