from lzma import LZMADecompressor
LZMADecompressor()

# LZMA_OK
# LZMA_STREAM_END
# LZMA_NO_CHECK
# LZMA_UNSUPPORTED_CHECK
# LZMA_GET_CHECK
# LZMA_MEM_ERROR
# LZMA_MEMLIMIT_ERROR
# LZMA_FORMAT_ERROR
# LZMA_OPTIONS_ERROR
# LZMA_DATA_ERROR
# LZMA_BUF_ERROR
# LZMA_PROG_ERROR
# lzma.LZMAError
# lzma.LZMAFile
# lzma.open
# lzma.LZMACompressor
# lzma.LZMADecompressor

# LZMA_CHECK_NONE
# LZMA_CHECK_CRC32
# LZMA_CHECK_CRC64
# LZMA_CHECK_SHA256
# LZMA_CHECK_ID_MAX
