import lzma
lzma.open

import os
import sys
import time
import json
import shutil
import subprocess
import threading
import traceback
import zipfile
import tempfile
import platform
import re
import urllib.request
import urllib.parse
import urllib.error
import urllib.request
import urllib.error
import urllib.parse
import hashlib
import base64
import socket
import ssl
import http.client
import http.server
import socketserver
import webbrowser
import tkinter
import tkinter.messagebox
import tkinter.filedialog
import tkinter.ttk
import tkinter.font
import tkinter.scrolledtext
import tkinter.simpledialog
import tkinter.colorchooser
import tkinter.tix
import tkinter.ttk
import tkinter.constants
import tkinter.dialog
import tkinter.tix
import tkinter.ttk
import tkinter.constants
import tkinter.dialog
import tk
