import lzma
lzma.LZMAFile

import os
import sys
import time
import shutil
import subprocess
import tempfile
import zipfile
import tarfile
import urllib.request
import urllib.parse
import urllib.error
import hashlib
import logging
import platform
import re
import stat
import io
import json
import fnmatch
import collections
import functools
import contextlib
import distutils.spawn
import distutils.version
import distutils.dir_util
import distutils.file_util
import distutils.errors
import distutils.util
import distutils.log
import distutils.sysconfig
import distutils.ccompiler
import distutils.command.build_ext
import distutils.command.build_clib
import distutils.command.build_scripts
import distutils.command.install_data
import distutils.command.install_lib
import distutils.command.install_scripts
import distutils.command.sdist
import distutils.command.clean
import distutils.command.upload
import distutils.command.register
import distutils.
