from lzma import LZMADecompressor
LZMADecompressor.__module__ = 'lzma'

from . import _regex
from . import _regex_core
from . import _sre
from . import _sre_compile
from . import _sre_constants
from . import _sre_parse
from . import _sre_py_compile
from . import _sre_utils
from . import _string
from . import _unicodedata
from . import _warnings
from . import abc
from . import atexit
from . import base64
from . import binascii
from . import bz2
from . import calendar
from . import codecs
from . import collections
from . import copyreg
from . import copy
from . import csv
from . import dataclasses
from . import datetime
from . import enum
from . import errno
from . import faulthandler
from . import filecmp
from . import fileinput
from . import fnmatch
from . import gc
from . import glob
from . import grp
from . import gzip
from . import hashlib
from . import heap
