from lzma import LZMADecompressor
LZMADecompressor
from lzma import LZMACompressor
LZMACompressor
from lzma import COMPRESS_STANDARD, COMPRESS_FAST, COMPRESS_MAXIMUM
from lzma import DECOMPRESS_STANDARD, DECOMPRESS_CONSERVATIVE
from lzma import FORMAT_AUTO, FORMAT_XZ, FORMAT_ALONE, FORMAT_RAW

from lzma import CHECK_NONE, CHECK_CRC32, CHECK_CRC64, CHECK_SHA256
from lzma import FILTER_ARM, FILTER_ARMTHUMB, FILTER_DELTA, FILTER_IA64, FILTER_POWERPC, FILTER_SPARC, FILTER_X86
from lzma import FILTER_LZMA1, FILTER_LZMA2
from lzma import FILTER_X86, FILTER_IA64, FILTER_POWERPC, FILTER_ARM, FILTER_ARMTHUMB, FILTER_SPARC, FILTER_DELTA
from lzma import PRESET_DEFAULT
