import mmap
# Test mmap.mmap(0, 100)
# Test mmap.mmap(0, 100, access=mmap.ACCESS_READ)
# Test mmap.mmap(0, 100, access=mmap.ACCESS_WRITE)
# Test mmap.mmap(0, 100, access=mmap.ACCESS_COPY)
# Test mmap.mmap(-1, 100)
# Test mmap.mmap(0, 0)
# Test mmap.mmap(-1, 0)
# Test mmap.mmap(-1, 0, access=mmap.ACCESS_READ)
# Test mmap.mmap(-1, 0, access=mmap.ACCESS_WRITE)
# Test mmap.mmap(-1, 0, access=mmap.ACCESS_COPY)
# Test mmap.mmap(0, -1)
# Test mmap.mmap(-1, -1)
# Test mmap.mmap(-1, -1, access=mmap.ACCESS_READ)
# Test mmap.mmap(-1, -1, access
