import mmap
# Test mmap.mmap(0, 256)
print('mmap.mmap(0, 256)')
m = mmap.mmap(0, 256)
print('m.write(b"abcdefghijkl")')
m.write(b"abcdefghijkl")
print('m.seek(0)')
m.seek(0)
print('m.read(1)')
print(m.read(1))
print('m.read(10)')
print(m.read(10))
print('-------------------')

# Test mmap.mmap(0, 256, "w")
print('Test mmap.mmap(0, 256, "w")')
m = mmap.mmap(0, 256, "w")
print('m.write(b"abcdefghijkl")')
m.write(b"abcdefghijkl")
print('m.seek(0)')
m.seek(0)
print('m.read(1)')
print(m.read(1))
print('m.read(10)')
print(m.read(
