import mmap
# Test mmap.mmap()
len(mmap.mmap(-1, 1))
# Test io.BytesIO.getvalue()
len(io.BytesIO().getvalue())
# Test io.BufferedReader.peek()
len(io.BufferedReader(io.BytesIO()).peek(10))
# Test mmap.mmap.read_byte()
mmap.mmap(io.BytesIO().fileno(), 1).read_byte()
# Test io.BytesIO.read()
len(io.BytesIO().read(10))
# Test io.BytesIO.readline()
len(io.BytesIO().readline())
# Test io.BufferedReader.read()
len(io.BufferedReader(io.BytesIO()).read())
# Test io.BufferedReader.readline()
len(io.BufferedReader(io.BytesIO()).readline())
# Test io.TextIOWrapper.read()
len(io.TextIOWrapper(io.BufferedReader(io.BytesIO())).read())
# Test io.TextIOWrapper.readline
