import mmap
# Test mmap.mmap()
# Test mmap.mmap(fd)
# Test mmap.mmap(fd, length)
# Test mmap.mmap(fd, length, flags)
# Test mmap.mmap(fd, length, flags, prot)
# Test mmap.mmap(fd, length, flags, prot, offset)
# Test mmap.mmap(length)
# Test mmap.mmap(length, flags)
# Test mmap.mmap(length, flags, prot)
# Test mmap.mmap(length, flags, prot, access)
# Test mmap.mmap(length, flags, prot, access, offset)
# Test mmap.mmap(length, flags, prot, access, offset, fileno)
# Test mmap.mmap(length, flags, prot, access, offset, fileno, closefd)
# Test mmap.mmap(-1)
# Test mmap.mmap(-1, length)
# Test mmap.mmap(-1, length, flags)
# Test mmap.mmap(-1, length, flags, prot)

