import mmap
# Test mmap.mmap.__doc__
# Test mmap.mmap.__new__
# Test mmap.mmap.__del__
# Test mmap.mmap.size
# Test mmap.mmap.tell
# Test mmap.mmap.seek
# Test mmap.mmap.read
# Test mmap.mmap.read_byte
# Test mmap.mmap.readline
# Test mmap.mmap.readlines
# Test mmap.mmap.write
# Test mmap.mmap.write_byte
# Test mmap.mmap.writelines
# Test mmap.mmap.resize
# Test mmap.mmap.flush
# Test mmap.mmap.close
# Test mmap.mmap.find
# Test mmap.mmap.rfind
# Test mmap.mmap.rfind
# Test mmap.mmap.move
# Test mmap.mmap.move
# Test mmap.mmap.move
# Test mmap.mmap.move
# Test mmap.mmap.move
# Test mmap.mm
