fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__qualname__ = 'fn'
fn.__module__ = '__main__'
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__defaults__ = ()
fn.__globals__ = globals()
fn.__closure__ = None
fn.__dict__ = {}
fn.__doc__ = None
fn.__text_signature__ = None
fn.__get__ = None
fn.__set__ = None
fn.__delete__ = None
fn.__slots__ = ()
fn.__weakref__ = None
fn.__dict__ = {}
fn.__func__ = fn
fn.__self__ = None
fn.__class__ = <class 'function'>
fn.__call__ = <method-wrapper '__call__' of function object at 0x7f8d9c7f3d08>
fn.__get__ = <method-wrapper '__get__' of function object at 0x7f8d9c7
