fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__qualname__ = 'fn'
fn.__module__ = '__main__'
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__defaults__ = ()
fn.__dict__ = {}
fn.__closure__ = None
fn.__doc__ = None
fn.__globals__ = {}
fn.__get__ = None
fn.__set__ = None
fn.__delete__ = None
fn.__slots__ = ()
fn.__self__ = None
fn.__func__ = None
fn.__bases__ = ()
fn.__mro__ = ()
fn.__subclasshook__ = None
fn.__init_subclass__ = None
fn.__class__ = function
fn.__init__ = None
fn.__new__ = None
fn.__delattr__ = None
fn.__setattr__ = None
fn.__getattribute__ = None
fn.__eq__ = None
fn.__ne__ =
