fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__module__ = '__main__'
fn.__defaults__ = ()
fn.__globals__ = {}
fn.__kwdefaults__ = None
fn.__closure__ = None
fn.__annotations__ = {}
fn.__dict__ = {}
fn.__doc__ = None
fn.__setattr__ = lambda self, name, value: None
fn.__delattr__ = lambda self, name: None
fn.__lt__ = lambda self, other: False
fn.__le__ = lambda self, other: False
fn.__eq__ = lambda self, other: False
fn.__ne__ = lambda self, other: True
fn.__gt__ = lambda self, other: False
fn.__ge__ = lambda self, other: False
fn.__hash__ = lambda self: 0
fn.__str__ = lambda self: '<function fn at 0x7f8f7f6c0d08>'
fn.__repr__ = lambda self: '<function fn at
