fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__qualname__ = 'fn'
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__defaults__ = ()
fn.__globals__ = {}
fn.__closure__ = None
fn.__dict__ = {}
fn.__doc__ = None
fn.__text_signature__ = None
fn.__module__ = '__main__'
fn.__class__ = &lt;class 'function'&gt;
fn.__dict__ = {}
fn.__get__ = &lt;method-wrapper '__get__' of function object at 0x7f5a8f5c4d40&gt;
fn.__set__ = &lt;method-wrapper '__set__' of function object at 0x7f5a8f5c4d40&gt;
fn.__delete__ = &lt;method-wrapper '__delete__' of function object at 0x7f5a8f5c4d40&gt;
fn.__
