fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__doc__ = 'fn'
fn.__module__ = 'fn'
fn.__dict__ = {}
fn.__defaults__ = ()
fn.__kwdefaults__ = None
fn.__annotations__ = {}
fn.__closure__ = None
fn.__globals__ = {}
fn.__dict__ = {}
fn.__qualname__ = 'fn'
fn.__get__ = lambda *args: None
fn.__set__ = lambda *args: None
fn.__delete__ = lambda *args: None
fn.__slots__ = ()
fn.__weakref__ = None
fn.__self__ = None
fn.__func__ = None
fn.__class__ = type
fn.__subclasshook__ = lambda *args: None
fn.__init_subclass__ = lambda *args: None
fn.__prepare__ = lambda *args: None
fn.__instancecheck__ = lambda *args: None
fn.__subclasscheck__ = lambda *args:
