fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__qualname__ = 'fn'
fn.__module__ = '__main__'
fn.__dict__ = {}
fn.__defaults__ = None
fn.__closure__ = None
fn.__kwdefaults__ = None
fn.__annotations__ = {}
fn.__globals__ = None
fn.__doc__ = None
fn.__text_signature__ = None
fn.__get__ = lambda *args, **kwargs: None
fn.__set__ = lambda *args, **kwargs: None
fn.__delete__ = lambda *args, **kwargs: None
fn.__call__ = lambda *args, **kwargs: None
fn.__len__ = lambda *args, **kwargs: None
fn.__length_hint__ = lambda *args, **kwargs: None
fn.__getitem__ = lambda *args, **kwargs: None
fn.__missing__ = lambda *args, **kwargs: None
fn.__setitem__ = lambda *args
