fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__qualname__ = 'fn'
fn.__module__ = '__main__'
fn.__dict__ = {}
fn.__defaults__ = None
fn.__kwdefaults__ = None
fn.__closure__ = None
fn.__annotations__ = {}
fn.__globals__ = {}
fn.__doc__ = None
fn.__text_signature__ = None
fn.__get__ = None
fn.__set__ = None
fn.__delete__ = None
fn.__slots__ = ()
fn.__weakref__ = None
fn.__dict__ = {}
fn.__module__ = '__main__'
fn.__qualname__ = 'fn'
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__defaults__ = None
fn.__globals__ = {}
fn.__closure__ = None
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'

