fn = lambda: None
gi = (i for i in ())
fn.__code__ = compile("foo", "bar", "exec")
fn.__globals__ = {'__builtins__': gi}
fn.__doc__ = fn
fn.__name__ = fn
fn.__defaults__ = fn
fn.__kwdefaults__ = fn
fn.__qualname__ = fn
fn.__annotations__ = fn
fn.__closure__ = fn
fn.__code__ = fn
fn.__globals__ = fn
fn.__dict__ = fn
fn.__module__ = fn
fn.__weakref__ = fn
fn.__slots__ = fn
fn.__call__ = fn
fn.__get__ = fn
fn.__set__ = fn
fn.__delete__ = fn
fn.__prepare__ = fn
fn.__init_subclass__ = fn
fn.__new__ = fn
fn.__init__ = fn
fn.__class__ = fn
fn.__getattr__ = fn
fn.__getattribute__ = fn
fn.__setattr__ = fn
fn.__delattr__ = fn

