fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = '<lambda>'
fn.__qualname__ = '<lambda>'
fn.__module__ = '__main__'
fn.__defaults__ = ()
fn.__kwdefaults__ = None
fn.__annotations__ = {}
fn.__closure__ = None
fn.__doc__ = None
fn.__globals__ = {}
fn.__dict__ = {}
fn.__get__ = lambda self, obj, typ: self
fn.__set__ = lambda self, obj, val: None
fn.__delete__ = lambda self, obj: None
fn.__call__ = lambda self, *args, **kw: None
fn.__all__ = None
fn.__dir__ = lambda self: []
fn.__class__ = type
fn.im_class = None
fn.im_self = None
fn.im_func = fn
fn.__func__ = fn
fn.__self__ = None
fn.__eq__ = lambda self, other: self is other
fn.__ne__ = lambda
