fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__module__ = '__main__'
fn.__defaults__ = None
fn.__globals__ = globals()
fn.__closure__ = None
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__doc__ = None
fn.__qualname__ = 'fn'
fn.__dict__ = {}
fn.__text_signature__ = '()'
fn.__get__ = <method-wrapper '__get__' of function object at 0x7f0d6f7f2b70>
fn.__set__ = <method-wrapper '__set__' of function object at 0x7f0d6f7f2b70>
fn.__delete__ = <method-wrapper '__delete__' of function object at 0x7f0d6f7f2b70>
fn.__slots__ = ()
fn.__dict__ = {}
fn.__weakref__ = None
fn.__class__ = <class 'function
