fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__qualname__ = 'fn'
fn.__module__ = '__main__'
fn.__defaults__ = ()
fn.__kwdefaults__ = None
fn.__closure__ = ()
fn.__annotations__ = {}
fn.__dict__ = {}
fn.__globals__ = {}
fn.__doc__ = None
fn.__text_signature__ = None
fn.__get__ = None
fn.__set__ = None
fn.__delete__ = None
fn.__slots__ = ()
fn.__weakref__ = None
fn.__func__ = None
fn.__self__ = None
fn.__class__ = None
fn.__delattr__ = None
fn.__dir__ = None
fn.__eq__ = None
fn.__format__ = None
fn.__ge__ = None
fn.__getattribute__ = None
fn.__gt__ = None
fn.__hash__ = None
fn.__init__ = None
fn.
