fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__doc__ = 'doc'
fn.__dict__ = {}
fn.__defaults__ = ()
fn.__closure__ = ()
fn.__globals__ = {}
fn.__module__ = 'module'
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__get__ = lambda: None
fn.__set__ = lambda: None
fn.__delete__ = lambda: None
fn.__init__ = lambda: None
fn.__new__ = lambda: None
fn.__prepare__ = lambda: None
fn.__eq__ = lambda: None
fn.__ne__ = lambda: None
fn.__lt__ = lambda: None
fn.__le__ = lambda: None
fn.__gt__ = lambda: None
fn.__ge__ = lambda: None
fn.__hash__ = lambda: None
fn.__bool__ = lambda: None
fn.__call__ = lambda: None
fn.__len__ = lambda: None
fn.__
