fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__qualname__ = 'fn'
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__defaults__ = ()
fn.__globals__ = {}
fn.__closure__ = None
fn.__doc__ = None
fn.__text_signature__ = None
fn.__module__ = '__main__'
fn.__dict__ = {}
fn.__self__ = None
fn.__func__ = None
fn.__bases__ = ()
fn.__mro__ = ()
fn.__subclasses__ = ()
fn.__init_subclass__ = None
fn.__class__ = <class 'function'>
fn.__get__ = <method-wrapper '__get__' of function object at 0x7f7f1f2a8c80>
fn.__set__ = <method-wrapper '__set__' of function object at 0x7f7f1f2a8c80>
fn.__delete__ = <method
