fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__qualname__ = 'fn'
fn.__module__ = '__main__'
fn.__dict__ = {}
fn.__defaults__ = ()
fn.__kwdefaults__ = None
fn.__annotations__ = {}
fn.__closure__ = None
fn.__globals__ = {}
fn.__doc__ = None
fn.__text_signature__ = None
fn.__get__ = lambda: None
fn.__set__ = lambda: None
fn.__delete__ = lambda: None
fn.__init__ = lambda: None
fn.__new__ = lambda: None
fn.__prepare__ = lambda: None
fn.__subclasshook__ = lambda: None
fn.__init_subclass__ = lambda: None
fn.__class__ = type
fn.__delattr__ = lambda: None
fn.__dir__ = lambda: None
fn.__eq__ = lambda: None
fn.__format__ = lambda: None
fn.__ge__ = lambda
