fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi
fn.__code__.co_code = gi
fn.__code__.co_code = 'a'
fn.__code__.co_code = b'a'
fn.__code__.co_code = bytearray(b'a')
fn.__code__.co_code = b'a'
fn.__code__.co_code = 'a'
fn.__code__.co_code = b'a'
fn.__code__.co_code = bytearray(b'a')
fn.__code__.co_code = 'a'
fn.__code__.co_code = b'a'
fn.__code__.co_code = bytearray(b'a')
fn.__code__.co_code = 'a'
fn.__code__.co_code = b'a'
fn.__code__.co_code = bytearray(b'a')
fn.__code__.co_code = 'a'
fn.__code__.co_code = b'a'
