fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi
fn.__name__ = "foo"
fn.__qualname__ = "foo"
fn.__module__ = "foo"
fn.__defaults__ = ()
fn.__kwdefaults__ = None
fn.__annotations__ = {}
fn.__closure__ = None
fn.__globals__ = {}
fn.__dict__ = {}
fn.__doc__ = ""
fn.__text_signature__ = ""
fn.__get__ = lambda: None
fn.__set__ = lambda: None
fn.__delete__ = lambda: None
fn.__init__ = lambda: None
fn.__new__ = lambda: None
fn.__prepare__ = lambda: None
fn.__getattr__ = lambda: None
fn.__getattribute__ = lambda: None
fn.__setattr__ = lambda: None
fn.__delattr__ = lambda: None
fn.__dir__ = lambda: None
fn.__class__ = type
fn.__mro__ = (type,)
fn.__subclasses__ = lambda: None
fn.__
