fn = lambda: None
gi = (i for i in ())
fn.__code__ = fn.func_code = gi.gi_code = type(gi.gi_code)()
fn.__code__.co_varnames = ('',)
fn.__code__.co_argcount = 1
fn.__code__.co_flags = 0x0004
fn.__code__.co_consts = ()
fn.__code__.co_names = ()
fn.__code__.co_cellvars = ()
fn.__code__.co_freevars = ()
fn.__code__.co_stacksize = 0
fn.__code__.co_lnotab = ''
fn.__code__.co_filename = ''
fn.__code__.co_name = ''
fn.__code__.co_firstlineno = 0
fn.__code__.co_lnotab = ''
fn.__code__.co_zombieframe = None
fn.__code__.co_weakreflist = []
fn.__code__.co_extra = ()
fn.__code__.co_nlocals = 0
