fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi

# Crash
fn()

# Error
fn.__code__.__next__()
```

```
python3 -m crash_on_ipy
```

```
[1]    27843 segmentation fault (core dumped)  python3 -m crash_on_ipy
```

```
$ gdb -p 27843
Reading symbols from python3...(no debugging symbols found)...done.
[New LWP 27843]
Core was generated by `python3 -m crash_on_ipy'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f6b8d6c7f6d in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
(gdb) bt
#0  0x00007f6b8d6c7f6d in ?? () from /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
#1  0x00007f6
