fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'foo'
fn.__module__ = 'bar'
fn.__doc__ = 'doc'
fn.__dict__ = {'a': 1}
fn.__defaults__ = (1,)
fn.__closure__ = (1,)
fn.__annotations__ = {'a': 1}
fn.__kwdefaults__ = {'a': 1}
fn.__globals__ = globals()
fn.__get__ = lambda: None
fn.__set__ = lambda: None
fn.__delete__ = lambda: None
fn.__slots__ = ('a',)
fn.__qualname__ = 'foo'
fn.__self__ = None
fn.__text_signature__ = '()'
fn.__self__ = None
fn.__module__ = 'bar'
fn.__name__ = 'foo'
fn.__qualname__ = 'foo'
fn.__doc__ = 'doc'
fn.__annotations__ = {'a': 1}
fn.__dict__ =
