fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'test'
fn.__doc__ = 'test'
fn.__dict__ = {}
fn.__defaults__ = ()
fn.__closure__ = None
fn.__module__ = ''
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__globals__ = {}
fn.__get__ = lambda: None
fn.__set__ = lambda: None
fn.__del__ = lambda: None
fn.__init__ = lambda: None
fn.__new__ = lambda: None
fn.__repr__ = lambda: None
fn.__str__ = lambda: None
fn.__bytes__ = lambda: None
fn.__hash__ = lambda: None
fn.__bool__ = lambda: None
fn.__call__ = lambda: None
fn.__len__ = lambda: None
fn.__length_hint__ = lambda: None
fn.__getitem__ = lambda: None
fn.__setitem__ = lambda: None
fn.__delitem__ = lambda: None
