fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__qualname__ = 'fn'
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__defaults__ = None
fn.__globals__ = {}
fn.__closure__ = None
fn.__dict__ = {}
fn.__doc__ = None
fn.__text_signature__ = None
fn.__module__ = '__main__'
fn.__class__ = function
fn.__closure__ = None
fn.__code__ = &lt;code object &lt;lambda&gt; at 0x7f7b3a8b7c70, file "&lt;stdin&gt;", line 1&gt;
fn.__defaults__ = None
fn.__dict__ = {}
fn.__doc__ = None
fn.__name__ = '&lt;lambda&gt;'
fn.__qualname__ = '&lt;lambda&gt;'
fn.__globals__ = {'__name__': '__main__
