fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = 'fn'
fn.__dict__ = {}
fn.__doc__ = ''
fn.__module__ = '__main__'
fn.__defaults__ = None
fn.__kwdefaults__ = None
fn.__closure__ = None
fn.__annotations__ = {}
fn.__globals__ = {}
fn.__dict__ = {}
fn.__qualname__ = 'fn'
fn.__get__ = lambda: None
fn.__set__ = lambda: None
fn.__delete__ = lambda: None
fn.__slots__ = ()
fn.__weakref__ = None
fn.__self__ = None
fn.__func__ = None
fn.__bases__ = ()
fn.__mro__ = ()
fn.__subclasshook__ = lambda: None
fn.__init_subclass__ = lambda: None
fn.__class__ = type
fn.__init__ = lambda: None
fn.__new__ = lambda: None
fn.__del__ = lambda: None

