import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

import sys
import os
import time
import threading
import subprocess
import json
import re
import traceback
import logging
import logging.handlers
import argparse
import socket
import struct
import fcntl
import random
import string
import hashlib
import base64
import urllib
import urllib2
import httplib
import urlparse
import ssl
import tempfile
import shutil
import zipfile
import Queue
import ConfigParser
import StringIO
import xml.etree.ElementTree as ET

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Gdk', '3.0')
gi.require_version('GdkPixbuf', '2.0')
gi.require_version('GObject', '2.0')
gi.require_version('GLib', '2.0')
gi.require_version('Gio', '2.0')
gi.require_version('GtkSource', '
