import socket
# Test socket.if_indextoname()
print('1.1)', socket.if_indextoname(2))
print('1.2)', socket.if_indextoname(1))
print('1.3)', socket.if_indextoname(0))
print('1.4)', socket.if_indextoname(3))
print('1.5)', socket.if_indextoname(4))
print('1.6)', socket.if_indextoname(5))
print('1.7)', socket.if_indextoname(6))
print('1.8)', socket.if_indextoname(7))
print('1.9)', socket.if_indextoname(8))
print('1.10)', socket.if_indextoname(9))
print('1.11)', socket.if_indextoname(10))
print('1.12)', socket.if_indextoname(11))
print('1.13)', socket.if_indextoname(12))
print('1.14)
