import socket
socket.if_indextoname()
socket.if_nameindex()
socket.if_nametoindex()
socket.inet_aton()
socket.inet_ntoa()
socket.gethostbyaddr()
socket.gethostbyname_ex()
socket.gethostbyname()
socket.gethostname()
socket.getaddrinfo()
socket.gethostbyaddr()
socket.gethostbyname()
socket.gethostbyname_ex()
socket.getnameinfo()
socket.getprotobyname()
socket.getservbyname()
socket.getservbyport()
socket.ntohl()
socket.ntohs()
socket.htonl()
socket.htons()
socket.inet_aton()
socket.inet_ntoa()
socket.inet_pton()
socket.inet_ntop()
socket.getaddrinfo()
socket.getfqdn()

# os模块
os.uname()
os.getlogin()
os.getppid()
os.getcwd()
os.getcwdb()
os.getenv()
os.get
