import socket
# Test socket.if_indextoname()
print("if_indextoname(15):", socket.if_indextoname(15))
# Test socket.if_nameindex()
print("if_nameindex():", socket.if_nameindex())
# Test socket.getaddrinfo()
print("getaddrinfo(localhost):", socket.getaddrinfo("localhost", 80))
# Test socket.getdefaulttimeout()
print("getdefaulttimeout():", socket.getdefaulttimeout())
# Test socket.gethostname()
print("gethostname():", socket.gethostname())
# Test socket.gethostbyaddr()
print("gethostbyaddr(127.0.0.1):", socket.gethostbyaddr("127.0.0.1"))
# Test socket.gethostbyname()
print("gethostbyname(localhost):", socket.gethostbyname("localhost"))
# Test socket.gethostbyname_ex()
print("gethostbyname_ex(localhost):", socket.gethostbyname_ex("localhost"))
# Test socket.getfqdn()
print("getfqdn():", socket.
