import socket
# Test socket.if_indextoname()
print socket.if_indextoname(2)
print socket.if_indextoname(1)
# Test socket.if_nameindex()
print socket.if_nameindex()
# Test socket.if_nameindex()
print socket.if_nameindex()
# Test socket.if_nametoindex()
print socket.if_nametoindex('lo')
print socket.if_nametoindex('eth0')
# Test socket.getaddrinfo()
print socket.getaddrinfo('localhost', 80, socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
# Test socket.getdefaulttimeout()
print socket.getdefaulttimeout()
# Test socket.gethostbyaddr()
print socket.gethostbyaddr('127.0.0.1')
# Test socket.gethostbyname()
print socket.gethostbyname('localhost')
# Test socket.gethostbyname_ex()
print socket.gethostbyname_ex('localhost')
# Test socket.gethostname()
print socket.gethostname()
#
