import ctypes
import ctypes.util
import threading
import sqlite3
# Test sqlite3.connect("file:examples.db?mode=ro", uri=True)


JDB_ERR_FATAL = -1
JDB_ERR_SUCCESS = 0
JDB_ERR_NOFILE = 1
JDB_ERR_CANTOPEN = 2
JDB_ERR_NOMEM = 4
JDB_ERR_READ_DENIED = 8
JDB_ERR_INV_HANDLE = 16
JDB_ERR_INV_DATA = 32
JDB_ERR_INV_CHANNEL = 64
JDB_ERR_NO_SIGNAL = 128
JDB_ERR_INV_SIGNAL = 256
JDB_ERR_INV_CYCLE = 512
JDB_ERR_INV_ARG = 1024
JDB_ERR_INV_CHANLIST = 2048
JDB_ERR_INV_RANGELIST = 4096
JDB_ERR_INV_RANGE_LENGTH = 8192
JDB_ERR_RANGE_OVERLAP = 16
