import ctypes
import ctypes.util
import threading
import sqlite3
import os
import sys
import datetime
import json
import collections
import requests
import time
import socket
import traceback
import time
import hashlib
import math

import dns.resolver
import dns.query
import dns.zone
import dns.rdatatype
import dns.rdataclass
import dns.rdtypes.ANY.NS
import dns.rdtypes.ANY.SOA
import dns.rdtypes.IN.A
import dns.rdtypes.IN.AAAA
import dns.rdtypes.IN.MX
import dns.rdtypes.IN.TXT
import dns.rdtypes.IN.CNAME
import dns.rdtypes.IN.NS
import dns.rdtypes.IN.SOA
import dns.rdtypes.IN.SRV
import dns.rdtypes.ANY.NS
import dns.rdtypes.ANY.SOA
import dns.rdtypes.ANY.TXT
import dns.rdtypes.ANY.CNAME
import dns.rdtypes.ANY.MX
import dns.
