import ctypes
import ctypes.util
import threading
import sqlite3
# Test sqlite3.connect("/home/pi/Desktop/GPS.db")

# GPSD_API_MAJOR_VERSION = 5
# GPSD_API_MINOR_VERSION = 0
# GPSD_API_PATCH_VERSION = 0

# GPSD_CONNECT_VERSION = "?GPSD"

# GPSD_CONNECT_VERSION_SIZE = len(GPSD_CONNECT_VERSION)

# GPSD_CONNECT_VERSION_SIZE = len(GPSD_CONNECT_VERSION)

# GPSD_CONNECT_VERSION_SIZE = len(GPSD_CONNECT_VERSION)

# GPSD_CONNECT_VERSION_SIZE = len(GPSD_CONNECT_VERSION)

# GPSD_CONNECT_VERSION_SIZE = len(GPSD_CONNECT_VERSION)

# GPSD_CONNECT_VERSION_SIZE = len(GPSD_CONNECT_VERSION)

# GPSD_CONNECT_VERSION_SIZE = len(GPSD_CONNECT_VERSION)

# GPSD_CONNECT_VERSION_SIZE = len(G
