import ctypes
import ctypes.util
import threading
import sqlite3
import glob
import json
import os

# names
TR_TORRENT_PREFIX = 'magnet:?xt=urn:btih:'
TR_FIELD_NAME = 0
TR_FIELD_HASH = 1
TR_FIELD_STATUS = 2
TR_STATUS_STOPPED = 0
TR_STATUS_CHECK_WAIT = 1
TR_STATUS_CHECK = 2
TR_STATUS_DOWNLOAD_WAIT = 3
TR_STATUS_DOWNLOAD = 4
TR_STATUS_SEED_WAIT = 5
TR_STATUS_SEED = 6

# fields
TR_DEFAULT_PORT = 51413
TR_TORRENT_INFO_NAME = 0
TR_TORRENT_INFO_HASH = 1
TR_TORRENT_INFO_COMPLETED = 2
TR_TORRENT_INFO_SIZE = 3
TR_TORRENT_INFO_STATUS = 4
TR_TORRENT_INFO_SEEDS = 5

# priorities
TR_PRI_LOW = -1
TR_PRI_NOR
