import ctypes
import ctypes.util
import threading
import sqlite3
# Test sqlite3.connect(":memory:")

# Exit codes
EXIT_CODE_OK = 0
EXIT_CODE_UNKNOWN_ERROR = 1
EXIT_CODE_INVALID_PARAMETERS = 2
EXIT_CODE_OUT_OF_MEMORY = 3
EXIT_CODE_INVALID_INPUT_FILE = 4
EXIT_CODE_INVALID_OUTPUT_FILE = 5
EXIT_CODE_INVALID_INPUT_FORMAT = 6
EXIT_CODE_INVALID_OUTPUT_FORMAT = 7
EXIT_CODE_INVALID_INPUT_FILE_FORMAT = 8
EXIT_CODE_INVALID_OUTPUT_FILE_FORMAT = 9
EXIT_CODE_INVALID_INPUT_FILE_PARAMETERS = 10
EXIT_CODE_INVALID_OUTPUT_FILE_PARAMETERS = 11
EXIT_CODE_INPUT_FILE_NOT_FOUND = 12
EXIT_CODE_OUTPUT_FILE_
