import _struct
import _socket
import _time
import _signal
import _thread
import _ctypes
import _ssl
import _hashlib
import _random
import _bisect
import _heapq
import _collections
import _ssl
import _weakref
import _winreg
import _functools
import _operator
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _json
import _md5
import _sha
import _sha256
import _sha512
import _sre
import _pickle
import _pyio
import _imp
import _io
import _winxptheme
import _hotshot
import _win32sysloader
import _msi
import _locale
import _multibytecodec
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr

