import _struct
import _heapq
import _random
import _bisect
import _hashlib
import _io
import _csv
import _sre
import _codecs
import _socket
import _ssl
import _select
import _thread
import _asyncio
import _ast
import _contextvars
import _datetime
import _imp
import _weakref
import _operator
import _collections
import _functools
import _signal
import _stat
import _pathlib
import _faulthandler
import _resource
import _posixsubprocess
import _copyreg
import _frozen_importlib
import _json
import _tracemalloc
import _locale
import _site
import _posixshutil
import _msi
import _uuid
import _posixpath
import _sysconfigdata
import _quopri
import _gzip
import _lzma
import _socket
import _bz2
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs
