import _struct
import _thread
import _threading
import _tracemalloc
import _tracemalloc_impl
import _tracemodule
import _traitlets
import _trashcan
import _tty
import _turtle
import _types
import _typing
import _ucnhash
import _uid
import _urllib
import _uuid
import _uuid_impl
import _venv
import _warnings
import _weakref
import _weakrefset
import _webbrowser
import _winapi
import _winreg
import _winsound
import _winxptheme
import _xml
import _xmlplus
import _xmlrpc
import _xrange
import _yaml
import _zlib
import _zmq
import aifc
import antigravity
import argparse
import ast
import asynchat
import asyncore
import base64
import bdb
import binascii
import binhex
import bisect
import bsddb
import bsddb.db
import buildtools
import builtins
import bz2
