import _struct
import _sys
import _thread
import _time
import _traceback
import _types
import _unicodedata
import _warnings
import _weakref
import _winreg
import _xxsubinterpreters
import array
import audioop
import binascii
import cPickle
import cStringIO
import cmath
import ctypes
import datetime
import errno
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fpectl
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import hotshot
import hotshot.stats
import htmlentitydefs
import htmllib
import httplib
import ihooks
import imaplib
import imghdr
import imp
import inspect
import itertools
import jpeg
import keyword
import lib2to3
import linecache
import locale
import macpath
import macurl2path
import mailbox
import mailcap
