import _struct
import _thread
import _threading
import _time
import _traceback
import _warnings
import _weakref
import _weakrefset
import array
import atexit
import binascii
import builtins
import cmath
import collections
import copy
import copyreg
import datetime
import errno
import fcntl
import filecmp
import fileinput
import fnmatch
import fpectl
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import grp
import gzip
import hashlib
import heapq
import hmac
import imp
import importlib
import inspect
import io
import itertools
import keyword
import linecache
import locale
import logging
import macpath
import macurl2path
import mailbox
import math
import mimetypes
import mmap
import msilib
import msvcrt
import netrc
import nntplib
import ntpath
import nturl2path
import numbers
import opcode
import operator
import optparse
import os
import os2emxpath
import parser
