import _struct
from collections import deque
from collections import Counter
from collections import namedtuple
from collections import OrderedDict
from collections import defaultdict
from collections import abc
from collections import UserDict
from collections import UserList
from collections import UserString
from collections import ChainMap
from collections import Counter
from contextlib import contextmanager
from contextlib import closing
from contextlib import suppress
from contextlib import redirect_stdout
from contextlib import redirect_stderr
from contextlib import ExitStack
from functools import wraps
from functools import partial
from functools import reduce
from functools import update_wrapper
from functools import partialmethod
from functools import lru_cache
from timeit import timeit
from timeit import repeat
from functools import singledispatch
from dis import dis
from types import FunctionType
from types import MethodType
from types import BuiltinFunctionType
from types import BuiltinMethodType
from types import ModuleType
from types import TracebackType
from types import FrameType
from types import CodeType
from types import GeneratorType
from types import get_closure_
