import _struct
import _thread
import _threading_local
import _warnings
import _weakref
import _weakrefset
import array
import atexit
import bisect
import builtins
import bz2
import cmath
import collections
import copyreg
import crypt
import csv
import datetime
import dbm
import decimal
import difflib
import dis
import doctest
import errno
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import html
import http
import idlelib
import imaplib
import imghdr
import imp
import importlib
import inspect
import io
import ipaddress
import itertools
import json
import keyword
import lib2to3
import linecache
import locale
import logging
import lzma
import macpath
import macurl2path
import mailbox
import mailcap
import marshal
import math
