import _struct
import _sys
import _sysconfig
import _testcapi
import _thread
import _threading_local
import _tkinter
import _tracemalloc
import _warnings
import _weakref
import abc
import aifc
import antigravity
import anydbm
import argparse
import ast
import asynchat
import asyncore
import base64
import bdb
import binascii
import binhex
import bisect
import builtins
import bz2
import cProfile
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codeop
import colorsys
import compileall
import concurrent
import configparser
import contextlib
import contextvars
import copy
import copyreg
import crypt
import csv
import ctypes
import curses
import dataclasses
import datetime
import dbm
import decimal
import difflib
import dis
import distutils
import doctest
import dummy_threading
import easy_install
import email
import encodings
import ensurepip
import enum
import errno
