import _struct
import _thread
import _threading
import _time
import _warnings
import _weakref
import _weakrefset

# Import all builtin modules
import _ast
import _bisect
import _codecs
import _collections
import _csv
import _datetime
import _functools
import _heapq
import _io
import _json
import _locale
import _lsprof
import _md5
import _operator
import _signal
import _socket
import _sre
import _stat
import _string
import _struct
import _symtable
import _thread
import _tracemalloc
import _warnings
import _weakref

# Import all builtin modules
import _ast
import _bisect
import _codecs
import _collections
import _csv
import _datetime
import _functools
import _heapq
import _io
import _json
import _locale
import _lsprof
import _md5
import _operator
import _signal
import _socket
import _sre
import _stat
import _string
