import _struct
import _sys
import _thread
import _time
import _types
import _warnings
import _weakref
import _weakrefset
import _xxsubinterpreters
import abc
import audioop
import binascii
import builtins
import bz2
import cmath
import ctypes
import datetime
import errno
import faulthandler
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import grp
import gzip
import hashlib
import heapq
import hmac
import html
import http
import idlelib
import imaplib
import imghdr
import imp
import importlib
import inspect
import io
import ipaddress
import itertools
import json
import keyword
import lib2to3
import linecache
import locale
import logging
import lzma
import macpath
import macurl2path
import mailbox
import mailcap
import mimetypes
import modulefinder
import multiprocess
