import _struct
+import _socket
+import _futures
+import _json
+import _codecs_hk
+import _codecs_iso2022
+import _codecs_jp
+import _codecs_kr
+import _codecs_tw
+import _weakref
+import _testcapi
+import _locale
+import _operator
+import _collections
+import _pickle
+import _symtable
+import _fileio
+import _winapi
+import _lsprof
+import _multibytecodec
+import _codecs_cn
+import _codecs_hk
+import _codecs_iso2022
+import _codecs_jp
+import _codecs_kr
+import _codecs_tw
+import _subprocess
+import _bisect
+import _heapq
+import _random
+import _socket
+import _sre
+import _ssl
+import _struct
+import _symtable
+import _warnings
+import _weakref
