import _struct
import _thread
import _threading
import _turtle
import _uuid
import _weakref
import _weakrefset
import _winreg
import abc
import aifc
import antigravity
import argparse
import array
import ast
import asynchat
import asyncore
import atexit
import audiodev
import base64
import bdb
import binascii
import binhex
import bisect
import bz2
import calendar
import cgitb
import chunk
import cmath
import cmd
import code
import codeop
import codecs
import codeop
import colorsys
import commands
import compileall
import compiler
import contextlib
import Cookie
import cookielib
import copy
import copyreg
import cProfile
import crypt
import csv
import ctypes
import curses
import curses.ascii
import curses.panel
import curses.textpad
import datetime
import dbhash
import dbm
import decimal
import difflib
import dis
import distutils
import doctest
import dummy_threading
import email
import encodings
import errno
