import _struct
import _sys
import _thread
import _time
import _unicodedata
import _weakref
import _winreg
import _xdrlib
import abc
import audioop
import binascii
import bz2
import cPickle
import cStringIO
import calendar
import cd
import cgi
import cgitb
import chunk
import cmd
import code
import codeop
import colorsys
import commands
import compileall
import compiler
import contextlib
import cookielib
import copy
import copy_reg
import crypt
import csv
import ctypes
import curses
import datetime
import difflib
import dircache
import dis
import distutils
import doctest
import dummy_thread
import dummy_threading
import email
import encodings
import filecmp
import fileinput
import fnmatch
import formatter
import fpformat
import fractions
import ftplib
import functools
import gc
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import hotshot
import hot
