import _struct
+import _ctypes
+import _socket
+import _ssl
+import _hashlib
+import _random
+import _io
+import _codecs
+import _json
+import _collections
+import _weakref
+import _abc
+import _symtable
+import _testcapi
+import _locale
+import _stat
+import _opcode
+import _pickle
+import _datetime
+import _bisect
+import _heapq
+import _array
+import _weakrefset
+import _types
+import _functools
+import _contextvars
+import _collections_abc
+import _weakref
+import _sitebuiltins
+import _warnings
+import _string
+import _posixsubprocess
+import _multibytecodec
+import _thread
+import _codecs_cn
+import _codecs_hk
+import _codecs_iso2022
+import _codecs_jp
+import _codecs_kr
+import _cod
