import _struct
import _string
import _time
import _locale
import _codecs
import _weakref
import _random
import _bisect
import _heapq
import _collections
import _symtable
import _socket
import _ssl
import _hashlib
import _csv
import _sre
import _struct
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _winreg
import _multibytecodec
import _subprocess
import _ast
import _io
import _pickle
import _testcapi
import _msi
import _winxptheme
import _hotshot
import _lsprof
import _md5
import _sha
import _sha256
import _sha512
import _sre
import _ssl
import _tkinter
import _uuid
import _ctypes
import _decimal
import _elementtree
import _functools
import _json
import _lsprof
