import _struct
# Test _struct.Struct's alignment and size features.
structs = [
    _struct.Struct('x'),
    _struct.Struct('b'),
    _struct.Struct('bx'),
    _struct.Struct('bxx'),
    _struct.Struct('bxxx'),
    _struct.Struct('h'),
    _struct.Struct('hx'),
    _struct.Struct('hxx'),
    _struct.Struct('hxxx'),
    _struct.Struct('i'),
    _struct.Struct('ix'),
    _struct.Struct('ixx'),
    _struct.Struct('ixxx'),
    _struct.Struct('l'),
    _struct.Struct('lx'),
    _struct.Struct('lxx'),
    _struct.Struct('lxxx'),
    _struct.Struct('q'),
    _struct.Struct('qx'),
    _struct.Struct('qxx'),
    _struct.Struct('qxxx'),
    _struct.Struct('f'),
    _struct.Struct('fx'),
    _struct.Struct('fxx'),
    _struct.Struct('fxxx'),
    _struct
