import _struct
import _sre
import _codecs
import _weakref
import _random
import _bisect
import _heapq
import _socket
import _sqlite3
import _ssl
import _testcapi
import _bz2
import _lzma
import _hashlib
import _io
import _winreg
import _testbuffer
import _ast
import _elementtree
import _pickle
import _datetime
import _msi
import _contextvars
import _testimportmultiple
import _testcapimodule
import _testmultiphase
import _testinternalcapi
import _testcapi
import _testbuffer
import _testcapi
import _testmultiphase
import _testinternalcapi
import _testcapi
import _testbuffer
import _testcapi
import _testmultiphase
import _testinternalcapi
import _testcapi
import _testbuffer
import _testcapi
import _testmultiphase
import _testinternalcapi
import _testcapi
import _testbuffer
import _testcapi
import _testmult
