import _struct
import _testcapi
import _thread
import _threading_local
import _tracemalloc
import _warnings
import _weakref
import array
import atexit
import audioop
import binascii
import bz2
import cmath
import ctypes
import datetime
import dbm
import errno
import faulthandler
import fcntl
import filecmp
import fnmatch
import formatter
import fpectl
import fractions
import ftplib
import functools
import gc
import getopt
import getpass
import gettext
import glob
import grp
import gzip
import hashlib
import heapq
import hmac
import html
import http
import idlelib
import imaplib
import imghdr
import imp
import importlib
import inspect
import io
import ipaddress
import itertools
import json
import keyword
import lib2to3
import linecache
import locale
import logging
import lzma
import macpath
import macurl2path
import mailbox
import mailcap
import marshal
import math
import mim
