import _struct
import _thread
import _threading_local
import _time
import _weakref
import _weakrefset
import _winapi
import abc
import aifc
import antigravity
import anydbm
import argparse
import ast
import asynchat
import asyncore
import atexit
import audiodev
import base64
import bdb
import binascii
import binhex
import bisect
import bz2
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import colorsys
import compileall
import concurrent
import configparser
import contextlib
import contextvars
import copy
import copyreg
import crypt
import csv
import ctypes
import curses
import dataclasses
import datetime
import dbm
import decimal
import difflib
import dis
import distutils
import doctest
import dummy_threading
import email
import encodings
import ensurepip
import enum
import errno
import fcntl
import filecmp
import fileinput
import fn
