import _struct
import re
import _thread
import _threading_local
import time
import sys
import weakref
import collections
import _weakref
import binascii
import operator
import pickle
import _codecs
import _collections
import _collections_abc
import itertools
import heapq
import _bisect
import _heapq
import _random
import _sre
import array
import contextlib
import numbers
import functools
import _functools
import atexit
import _weakref
import _weakrefset
import _operator
import _stat
import _string
import _locale
import zlib
import _compression
import _json
import _io
import _fileio
import _pyio as io
import faulthandler
import _tracemalloc
import _symtable
import _testcapi
import _testbuffer
import _testimportmultiple
import _xxsubinterpreters
import _xxlimitedapi
import _xxsubtype
import errno
import _md5
import _sha1
import _sha256
import _sha512

