import _struct
import _structseq
import abc
import atexit
import base64
import binascii
import bisect
import calendar
import codecs
import collections
import copy
import csv
import dataclasses
import datetime
import decimal
import difflib
import dis
import doctest
import enum
import errno
import fcntl
import filecmp
import fileinput
import fnmatch
import functools
import fpectl
import fractions
import gc
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import html
import http
import idlelib
import imaplib
import imghdr
import imp
import importlib
import inspect
import io
import ipaddress
import itertools
import json
import keyword
import lib2to3
import linecache
import locale
import logging
import lzma
import macpath
import macurl2path
import mailbox
import mailcap
import marshal
import math
import mimetypes
import mmap
import modulefinder
import msilib
import msv
