import _struct
import _xml.etree.ElementTree as etree

__all__ = ["ExpatError", "error", "errors", "XML_PARAM_ENTITY_PARSING_ALWAYS",
           "XML_PARAM_ENTITY_PARSING_NEVER", "XML_PARAM_ENTITY_PARSING_UNLESS_STANDALONE",
           "XML_CQUANT_NONE", "XML_CQUANT_OPT", "XML_CQUANT_REP", "XML_CQUANT_PLUS",
           "XML_CTYPE_EMPTY", "XML_CTYPE_ANY", "XML_CTYPE_MIXED", "XML_CTYPE_NAME",
           "XML_CTYPE_CHOICE", "XML_CTYPE_SEQ", "XML_EVENT_NONE", "XML_EVENT_START_ELEMENT",
           "XML_EVENT_END_ELEMENT", "XML_EVENT_PROCESSING_INSTRUCT
