import _struct
import _sys
import _thread
import _threading
import _time
import _token
import _tokenize
import _traceback
import _tracemalloc
import _traceop
import _types
import _typing
import _warnings
import _weakref
import _weakrefset
import _weakref_helper
import _winapi
import _winreg
import _wstring
import abc
import aifc
import antigravity
import argparse
import ast
import asynchat
import asyncore
import audioop
import base64
import bdb
import binascii
import binhex
import bisect
import builtins
import bz2
import cProfile
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import collections
import colorsys
import compileall
import concurrent
import configparser
import contextlib
import contextvars
import copy
import copyreg
import crypt
import csv
import ctypes
import curses
import dataclasses
import datetime
import dbm
