from _struct import Struct
s = Struct.__new__(Struct)
s.format = '>hh'
s.size = Struct.calcsize(s.format)
print(s.size)
print(bytes(s))
print(bytes(s))
print(repr(bytes(s)))
print(bytes(s))
print(list(bytes(s)))
print(list(l))
print(bytes(s).strip(b'\x00'))
print(bytes(s))
print(b'\x00\x00\x00\x00'.strip(b'\x00'))
print(b'\x00\x00\x00\x00'.strip(b'\x00'))
print(Struct.pack(s.format))
bytes(s)
dir(s)
s = Struct.__new__(Struct, '>hh')
s.format = '>hh'
s.size = Struct.calcsize(s.format)
bytes(s)
s = Struct.__new__(Struct, '>hh')
bytes(s)
print(bytes(s))
filesize = Struct('>L
