import _struct
import _thread
import _threading
import _time
import _token
import _tokenize
import _traceback
import _tracemalloc
import _turtle
import _typing
import _unicodedata
import _unittest
import _urllib
import _uu
import _uuid
import _warnings
import _wave
import _weakref
import _webbrowser
import _winreg
import _wsgiref
import _xdrlib
import _xml
import _xmlrpc
import _zipfile
import _zipimport
import _zlib

# Standard library modules that are not imported by default.
import _aifc
import _al
import _anydbm
import _bsddb
import _bz2
import _cd
import _cl
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _collections_abc
import _compat_pickle
import _contextv
