import _struct
import _time
import _thread
import _weakref
import _warnings
import _weakrefset
import _testcapi
import errno
import itertools
import math
import operator
import _operator
import reprlib
import sys
import _collections
import _abc
import _codecs
import _functools
import _imp
import _io
import _locale
import _random
import _socket
import _sre
import _string
import _struct
import _symtable
import _thread
import _tracemalloc
import _warnings
import _weakref
import _weakrefset
import array
import atexit
import audioop
import binascii
import builtins
import cmath
import datetime
import faulthandler
import fractions
import gc
import imageop
import imghdr
import itertools
import marshal
import math
import mmap
import msvcrt
import nt
import ntpath
import operator
import parser
import sys
import time
import timeit
import unicodedata
import xxsubtype
import zip
