import _struct
import _thread
import _threading
import _time
import _token
import _tokenize
import _traceback
import _traceback_data
import _tracemalloc
import _tty
import _types
import _typing
import _unicodedata
import _unittest
import _urllib
import _uuid
import _warnings
import _weakref
import _weakrefset
import _webbrowser
import _winapi
import _winreg
import _winsound
import _xmlrpc
import _zipapp
import _zipfile
import _zlib
