import _struct
import _sys
import _time
import _types
import _warnings

# now, the c modules which have c extensions.
import _curses
import _curses_panel
import _bisect
import _bytesio
import _codecs
import _collections
import _csv
import _datetime
import _elementtree
import _functools
import _hashlib
import _heapq
import _io
import _json
import _locale
import _lsprof
import _md5
import _multibytecodec
import _multiprocessing
import _random
import _sha
import _sha256
import _sha512
import _socket
import _sre
import _ssl
import _stat
import _string
import _struct
import _symtable
import _thread
import _tracemalloc
import _weakref
import _winreg
import array
import audioop
import binascii
import cmath
import errno
import fcntl
import future_builtins
import math
import mmap
import operator
import parser
import select
import st
