import _struct
import _sys
import _thread
import _time
import _types
import _unittest
import _warnings
import _weakref
import _weakrefset
import _winreg
import _xmlrpclib
import _zipfile
import _zlib

# Modules that are not built-in but are always present
import _codecs
import _sre
import _symtable
import _threading
import _weakref
import _weakrefset
import _winreg
import _functools
import _operator
import _collections
import _abc
import _io
import _sitebuiltins
import _pickle
import _json
import _csv
import _struct
import _datetime
import _heapq
import _bisect
import _random
import _sha
import _md5
import _sha256
import _sha512
import _sre
import _codecs
import _weakref
import _functools
import _operator
import _collections
import _abc
import _io
import _sitebuiltins
import _pickle
import _json
import _
