import _struct
import _sys
import _thread
import _time
import _traceback
import _types
import _warnings
import _weakref
import _xxsubinterpreters
import _zipimport
import _zlib
import builtins
import errno
import faulthandler
import gc
import imp
import marshal
import posix
import pwd
import pyexpat
import select
import signal
import sys
import time
import unicodedata
import xxsubtype

# These modules are not built by default, but we want to make sure they are
# always available.
import _bz2
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _collections
import _csv
import _ctypes
import _decimal
import _elementtree
import _functools
import _hashlib
import _heapq
import _io
import _json
import _locale
import _lsprof
import _lz
