import _struct
import _thread
import _threading_local
import _warnings
import _weakref
import _weakrefset
import array
import atexit
import binascii
import builtins
import collections
import contextlib
import copyreg
import datetime
import errno
import faulthandler
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import html
import http
import idlelib
import imaplib
import imghdr
import imp
import importlib
import inspect
import io
import ipaddress
import itertools
import json
import keyword
import lib2to3
import linecache
import locale
import logging
import lzma
import macpath
import mailbox
import mailcap
import mimetypes
import modulefinder
import msilib
import msvcrt
import netrc
import nntplib
import ntpath
import nturl2
