import _struct
import _time
import _thread
import _threading
import _weakref
import _sre
import _codecs
import _collections
import _functools
import _random
import _heapq
import _bisect
import _symtable
import _weakref
import _io
import _marshal
import _imp
import _string
import _stat
import _locale
import _sha1
import _sha256
import _sha512
import _md5
import _blake2
import _sha3
import _hmac
import _json
import _uuid
import _operator
import _pickle
import _datetime
import _functools
import _collections
import _weakref
import _copyreg
import _types
import _warnings
import _contextlib
import _abc
import _tracemalloc
import _pathlib
import _statistics
import _decimal
import _symtable
import _testcapi
import _testbuffer
import _testimportmultiple
import _testmultiphase
import _ctypes
import _testcapimodule

