import _struct
from . import _struct
from . import _struct_str

_fields_ = [('a', 'I'),
            ('b', 'I'),
            ('c', 'I'),
            ('d', 'I'),
            ('e', 'I'),
            ('f', 'I'),
            ('g', 'I'),
            ('h', 'I'),
            ('i', 'I'),
            ('j', 'I'),
            ('k', 'I'),
            ('l', 'I'),
            ('m', 'I'),
            ('n', 'I'),
            ('o', 'I'),
            ('p', 'I'),
            ('q', 'I'),
            ('r', 'I'),
            ('s', 'I'),
            ('t', 'I'),
            ('u', 'I'),
            ('v', 'I'),
            ('w', 'I'),
            ('x', 'I'),
            ('y', 'I'),
            ('z', 'I'),
            ('aa', 'I'),
            ('ab', 'I'),
            ('ac', 'I'),
            ('ad
