import _struct
import _thread
import _threading
import _tracemalloc
import _tracemalloc_test
import _types
import _weakref
import _weakrefset
import array
import audioop
import binascii
import builtins
import bz2
import cmath
import ctypes
import datetime
import faulthandler
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import imaplib
import imghdr
import imp
import importlib
import inspect
import io
import ipaddress
import itertools
import json
import lib2to3
import linecache
import locale
import logging
import lzma
import macpath
import macurl2path
import mailbox
import mailcap
import mimetypes
import modulefinder
import multiprocessing
import netrc
import nntplib
import ntpath
