import types
types.FunctionType = types.MethodType

import sys
import types
import traceback

from pydev_imports import _pydev_saved_modules
from pydev_imports import _pydev_saved_meta_path
from pydev_imports import _pydev_saved_sys_path
from pydev_imports import _pydev_saved_sys_modules
from pydev_imports import _pydev_saved_sys_meta_path
from pydev_imports import _pydev_saved_sys_path_hooks
from pydev_imports import _pydev_saved_sys_path_importer_cache
from pydev_imports import _pydev_saved_get_loader
from pydev_imports import _pydev_saved_path_hooks
from pydev_imports import _pydev_saved_path_importer_cache
from pydev_imports import _pydev_importer
from pydev_imports
