import weakref

from . import _base
from . import _compat
from . import _util
from . import _pool
from . import _types
from . import _unix
from . import _windows
from . import _posix
from . import _posixsubprocess
from . import _multiprocessing
from . import _posixshmem
from . import _winapi
from . import _overlapped
from . import _winapi_pipe
from . import _winapi_memoryview
from . import _winapi_wait
from . import _winapi_event
from . import _winapi_semaphore
from . import _winapi_cond
from . import _winapi_mutex
from . import _winapi_sharedmem
from . import _winapi_queues
from . import _winapi_pipe_connection
from . import _winapi_connection
from . import _winapi_reduction
from . import _winapi_socket
from . import _winapi_socket_connection
from . import _winapi_socket_listener
from . import _winapi_socket_tr
