import weakref
# Test weakref.ref(obj)
# Test weakref.ref(obj, callback)
# Test weakref.proxy(obj)
# Test weakref.proxy(obj, callback)
# Test weakref.getweakrefcount(obj)
# Test weakref.getweakrefs(obj)
# Test weakref.WeakKeyDictionary()
# Test weakref.WeakValueDictionary()
# Test weakref.WeakSet()
# Test weakref.finalize(obj, func, *args, **kwargs)
# Test weakref.WeakMethod()
# Test weakref.WeakMethod(func, *args, **kwargs)
# Test weakref.WeakMethod(obj, func_name)
# Test weakref.WeakMethod(obj, func_name, *args, **kwargs)
# Test weakref.WeakMethodType()
# Test weakref.WeakMethodType(func, callback)
# Test weakref.WeakMethodType(obj, func_name, callback)
# Test weakref.WeakMethodType(obj, func_name, *args, **kwargs, callback)
# Test weakref.WeakMethodType(
