import weakref
from collections import defaultdict

from . import util
from . import config
from . import exceptions
from . import log
from . import types
from . import validators
from . import validators_types
from . import validators_extra
from . import validators_builtins
from . import validators_collections
from . import validators_dataclasses
from . import validators_typing
from . import validators_attrs
from . import validators_marshmallow
from . import validators_pydantic
from . import validators_custom
from . import validators_extras
from . import validators_fastapi
from . import validators_starlette
from . import validators_starlette_extra
from . import validators_requests
from . import validators_websockets
from . import validators_websockets_extra
from . import validators_mimes
from . import validators_mimes_extra
from . import validators_httpx
from . import validators_httpx_extra
from . import validators_uvicorn
from . import validators_uv
