import weakref
# Test weakref.ref(obj)
# Test weakref.ref(obj, callback)
# Test weakref.proxy(obj)
# Test weakref.proxy(obj, callback)
# Test weakref.getweakrefcount(obj)
# Test weakref.getweakrefs(obj)
# Test weakref.WeakKeyDictionary()
# Test weakref.WeakValueDictionary()
# Test weakref.WeakSet()
# Test weakref.finalize(obj, callback)
# Test weakref.finalize(obj, callback, args, kwargs)
# Test weakref.WeakMethod(method)
# Test weakref.WeakMethod(method, callback)
# Test weakref.WeakMethod(method, callback, kwargs)
# Test weakref.WeakMethod(method, callback, kwargs, method_name)
# Test weakref.WeakMethod(method, callback, kwargs, method_name, class_name)
# Test weakref.WeakMethod(method, callback, kwargs, method_name, class_name, module_name)
# Test weakref.WeakMethod(method, callback,
