import weakref
# Test weakref.ref(obj)
weakref.ref(1)
# Test weakref.ref(obj, callback)
weakref.ref(1, lambda: None)
# Test weakref.ref(obj, callback)
weakref.ref(1, lambda x: None)
# Test weakref.ref(obj, callback)
weakref.ref(1, lambda x: None)
# Test weakref.ref(obj, callback)
weakref.ref(1, lambda x: None)
# Test weakref.ref(obj, callback)
weakref.ref(1, lambda x: None)
# Test weakref.ref(obj, callback)
weakref.ref(1, lambda x: None)
# Test weakref.ref(obj, callback)
weakref.ref(1, lambda x: None)
# Test weakref.ref(obj, callback)
weakref.ref(1, lambda x: None)
# Test weakref.ref(obj, callback)
weakref.ref(1, lambda x: None)
# Test weakref.ref(obj, callback)
weakref.ref(1,
