import weakref
# Test weakref.ref(obj)
# Test weakref.ref(obj, callback)
# Test weakref.ref(obj, callback, key)
# Test weakref.ref(obj, callback, key, **kwargs)
# Test weakref.proxy(obj)
# Test weakref.proxy(obj, callback)
# Test weakref.proxy(obj, callback, key)
# Test weakref.proxy(obj, callback, key, **kwargs)
# Test weakref.getweakrefcount(obj)
# Test weakref.getweakrefs(obj)
# Test weakref.finalize(obj, callback, key, **kwargs)
# Test weakref.finalize(obj, callback, key)
# Test weakref.finalize(obj, callback)
# Test weakref.finalize(obj)
# Test weakref.WeakKeyDictionary()
# Test weakref.WeakKeyDictionary(dict)
# Test weakref.WeakValueDictionary()
# Test weakref.WeakValueDictionary(dict)
# Test weakref.WeakSet()
# Test weakref.WeakSet(iterable)

