import weakref

__all__ = [
    "QtCore",
    "QtGui",
    "QtWidgets",
    "QtSvg",
    "QtSvg",
    "QtXml",
    "QtXmlPatterns",
    "QtOpenGL",
    "QtNetwork",
    "QtPrintSupport",
    "QtScript",
    "QtScriptTools",
    "QtSql",
    "QtTest",
    "QtWebKit",
    "QtWebKitWidgets",
    "QtXml",
    "QtXmlPatterns",
    "QtUiTools",
    "QtDesigner",
    "QtHelp",
    "QtMultimedia",
    "QtQuick",
    "QtQuickWidgets",
    "QtPositioning",
    "QtLocation",
    "QtClipboard",
    "QtNfc",
    "QtSerialPort",
    "QtSensors",
   
