import weakref

from . import (
    _core, _util, _props, _tree, _dataproxy, _api,
    _decorators,
    _widget_utils,
    _widget_layout,
    _widget_box,
    _widget_selectioncontainer,
    _widget_floatlayout,
    _widget_group,
    _widget_scatter,
    _widget_label,
    _widget_button,
    _widget_image,
    _widget_slider,
    _widget_progressbar,
    _widget_switch,
    _widget_textinput,
    _widget_textinputlayout,
    _widget_checkbox,
    _widget_radiobuttons,
    _widget_rstdocument,
    _widget_scrollview,
    _widget_gridlayout,
    _widget_boxlayout,
    _widget_modalview,
    _widget_dropdown,
    _widget_spinner,
    _widget_splitter,
    _widget_filechooser,
    _widget_tabbedpanel,
    _
