import weakref

from . import _core
from . import _util
from . import _errors
from . import _types
from . import _constants
from . import _compat
from . import _lib
from . import _ffi
from . import _raw
from . import _cdata
from . import _cffi_backend
from . import _cffi_include
from . import _cffi_errors
from . import _cffi_ext
from . import _cffi_opcode
from . import _cffi_parse
from . import _cffi_setup
from . import _cffi_utils
from . import _embedding
from . import _backend
from . import _callbacks
from . import _pythonapi
from . import _pointer
from . import _rawffi
from . import _unions
from . import _enum
from . import _ctypeobj
from . import _cfield
from . import _cdataobj
from . import _cdataptr
from . import _cdatares
from . import _cdataarg
from . import _c
