import weakref
# Test weakref.ref
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
f = weakref.ref(lambda: None)
f()
