import weakref

from . import _core
from . import _util
from . import _event
from . import _window
from . import _control
from . import _gdi
from . import _menu
from . import _dialog
from . import _image
from . import _icon
from . import _cursor
from . import _accelerator
from . import _resource
from . import _timer
from . import _clipboard
from . import _dragdrop
from . import _ole
from . import _ole2
from . import _ole2con
from . import _ole2txt
from . import _ole2txtcon
from . import _ole2txtsrv
from . import _ole2txtsrvcon
from . import _ole2txtsrvdoc
from . import _ole2txtsrvdoccon
from . import _ole2txtsrvdocvw
from . import _ole2txtsrvdocvwcon
from . import _ole2txtsrvdocvwdoc
from . import _ole2txtsrvdocvwdoccon
from . import _ole2txtsrvdocv
