import codecs
# Test codecs.register_error('test', codecs.replace_errors)
# codecs.register_error('test', codecs.replace_errors)
# codecs.register_error('test', codecs.ignore_errors)
# codecs.register_error('test', codecs.xmlcharrefreplace_errors)
# codecs.register_error('test', codecs.backslashreplace_errors)
# codecs.register_error('test', codecs.namereplace_errors)
# codecs.register_error('test', codecs.strict_errors)
# codecs.register_error('test', codecs.surrogateescape_errors)
# codecs.register_error('test', codecs.surrogatepass_errors)
# codecs.register_error('test', codecs.ignore_errors)
# codecs.register_error('test', codecs.xmlcharrefreplace_errors)
# codecs.register_error('test', codecs.backslashreplace_errors)
# codecs.register_error('test', codecs.namereplace_errors)
# codecs.register_error
