import ctypes
# Test ctypes.CFUNCTYPE() with more than 16 arguments
#
# CPython issue14339:  http://bugs.python.org/issue14339
#
# This test runs into the implementation limit of the call
# wrapper function that is generated by the function type
# constructor CFUNCTYPE().  The wrapper function exceeds 64k.
#
# On X86 machines the maximum number of arguments is 20.
# Other architectures may have less
#
# For example, on x86-64 machine, the following error is raised:
#   ctypes.ArgumentError: argument 2: <class 'OverflowError'>: int too big to
#   convert
#

import platform
import unittest
from ctypes import *

#
# The following code is inspired from a post of Armin Rigo (arigo)
#
# Get the number of arguments that can be passed to a ctypes function
# This code is based on a test of the PyPy project
#
# The limit depends on the architecture.

def _get_arg_limit():
    _testfunc = CFUNCTYPE(c_int)
    _int_
