import ctypes
# Test ctypes.CFUNCTYPE()
func = ctypes.CFUNCTYPE(ctypes.c_int, ctypes.c_int)(lambda x: x)
print(func(42))
# Test ctypes.byref()
buf = ctypes.create_string_buffer(8)
ctypes.memset(ctypes.byref(buf), 0, 8)
print(buf.raw)
ctypes.memset(ctypes.byref(buf), 0xff, 8)
print(buf.raw)
# Test ctypes.pointer()
buf = ctypes.create_string_buffer(8)
ptr = ctypes.pointer(buf)
ctypes.memset(ptr, 0, 8)
print(buf.raw)
ctypes.memset(ptr, 0xff, 8)
print(buf.raw)
# Test ctypes.string_at()
print(ctypes.string_at(ctypes.pointer(buf), len(buf)))
print(ctypes.string_at(ctypes.pointer(buf), len(buf) - 1))
