import sys, threading

def run():
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
    sys.stdout.write("\n")
