import io
# Test io.RawIOBase()
io.RawIOBase()
# Test io.BufferedIOBase()
io.BufferedIOBase()
# Test io.TextIOBase()
io.TextIOBase()

# Test io.FileIO()
fp = io.FileIO(__file__, "r")
fp.__enter__()
fp.isatty()
fp.fileno()
# Test seekable()
fp.seekable()
# Test readable()
fp.readable()
# Test seek()
fp.seek(0, io.SEEK_SET)
