import io
# Test io.RawIOBase
# io.RawIOBase.read(self, n=-1)
# io.RawIOBase.readall(self)
# io.RawIOBase.readinto(self, b)
# io.RawIOBase.readinto1(self, b)
# io.RawIOBase.write(self, b)
# io.RawIOBase.detach(self)
# io.RawIOBase.seek(self, pos, whence=0)
# io.RawIOBase.tell(self)
# io.RawIOBase.truncate(self, pos=None)
# io.RawIOBase.fileno(self)
# io.RawIOBase.isatty(self)
# io.RawIOBase.readable(self)
# io.RawIOBase.seekable(self)
# io.RawIOBase.writable(self)
# io.RawIOBase.close(self)
# io.RawIOBase.flush(self)
# io.RawIOBase.readinto1(self, b)
# io.RawIOBase.__init__(self, *
