import io
# Test io.RawIOBase

import unittest
import io
import os
import sys
import tempfile
import weakref
import warnings
import errno
import functools
import contextlib
import pickle
import gc
import random
import struct
import shutil
import stat
import time
import mmap
import itertools
import collections
import threading
import subprocess
import platform
import socket
import select
import array
import atexit
import textwrap
import locale
import re
import abc
import numbers
import collections.abc
import _pyio as pyio
import _testcapi
import _thread
import _collections
import _multiprocessing
