import io
# Test io.RawIOBase

import unittest
import os
import sys
import io
import tempfile
import errno
import stat
import weakref
import functools
import contextlib
import warnings
import pickle
import gc
import random
import shutil
import struct
import subprocess
import threading
import time
import select
import socket
import mmap
import array
import collections
import abc
import atexit
import textwrap
import locale
import re
import platform
import sysconfig
import itertools
import numbers
import collections.abc
import _testcapi
import _thread
import _collections
import _multibytecodec
import _pyio
import _pyio as pyio
