import io
# Test io.RawIOBase
# Test io.BufferedIOBase
# Test io.TextIOBase
# Test io.IOBase
# Test io.FileIO
# Test io.BytesIO
# Test io.StringIO
# Test io.BufferedReader
# Test io.BufferedWriter
# Test io.BufferedRWPair
# Test io.BufferedRandom
# Test io.TextIOWrapper
# Test io.UnsupportedOperation
# Test io.SEEK_SET
# Test io.SEEK_CUR
# Test io.SEEK_END
# Test io.DEFAULT_BUFFER_SIZE
# Test io.open
# Test io.BytesIO.__init__
# Test io.BytesIO.__getattr__
# Test io.BytesIO.close
# Test io.BytesIO.closed
# Test io.BytesIO.detach
# Test io.BytesIO.fileno
# Test io.BytesIO.flush
# Test io.BytesIO.getvalue
# Test io.BytesIO.isatty
# Test io.BytesIO.read
# Test io.BytesIO.readable
# Test
