import io
# Test io.RawIOBase
# Test io.BufferedIOBase
# Test io.TextIOBase
# Test io.IOBase
# Test io.FileIO
# Test io.BytesIO
# Test io.StringIO
# Test io.BufferedReader
# Test io.BufferedWriter
# Test io.BufferedRWPair
# Test io.BufferedRandom
# Test io.TextIOWrapper
# Test io.UnsupportedOperation
# Test io.SEEK_SET
# Test io.SEEK_CUR
# Test io.SEEK_END
# Test io.DEFAULT_BUFFER_SIZE
# Test io.open
# Test io.IOError
# Test io.BlockingIOError
# Test io.UnsupportedOperation
# Test io.FileExistsError
# Test io.FileNotFoundError
# Test io.InterruptedError
# Test io.IsADirectoryError
# Test io.NotADirectoryError
# Test io.PermissionError
# Test io.ProcessLookupError
# Test io.TimeoutError
# Test io.__doc__
# Test io.__all__
#
