import io
# Test io.RawIOBase
import io
import sys
import unittest
import weakref
import _pyio as pyio
import _testcapi
import os
import errno
import select
import socket
import struct
import time
import threading
import subprocess
import tempfile
import warnings
import contextlib
import gc
import re
import shutil
import stat
import sysconfig
import platform
import traceback
import pickle
import collections
import abc
import atexit
import functools
import operator
import locale
import copy
import array
import gzip
import zlib
import bz2
import lzma
import zipfile
import tarfile
import unicodedata
import unittest.mock
