import io
# Test io.RawIOBase
# Test io.BufferedIOBase
# Test io.TextIOBase
# Test io.BytesIO
# Test io.StringIO
# Test io.BufferedReader
# Test io.BufferedWriter
# Test io.BufferedRWPair
# Test io.BufferedRandom
# Test io.FileIO
# Test io.FileIO.readinto
# Test io.FileIO.readinto1
# Test io.FileIO.write
# Test io.FileIO.writelines
# Test io.FileIO.fileno
# Test io.FileIO.close
# Test io.FileIO.closed
# Test io.FileIO.seek
# Test io.FileIO.tell
# Test io.FileIO.truncate
# Test io.FileIO.flush
# Test io.FileIO.isatty
# Test io.FileIO.readall
# Test io.FileIO.read
# Test io.FileIO.read1
# Test io.FileIO.readline
# Test io.FileIO.readlines
# Test io.FileIO.readlines1
# Test io.File
