import lzma
# Test LZMADecompressor.decompress()

# This test is to make sure that the decompressor doesn't
# get stuck in a loop if the stream is truncated.

# Test data is generated by first compressing a 1 MB file
# with the xz command line tool, and then truncating the
# compressed stream at the end of the first block.

# The test data is not included in the repo because
# it is too big.

