from lzma import LZMADecompressor
LZMADecompressor = LZMADecompressor
from lzma import FORMAT_AUTO, FORMAT_XZ, FORMAT_ALONE, FORMAT_RAW, CHECK_NONE, CHECK_CRC32, CHECK_CRC64, CHECK_SHA256
FORMAT_AUTO = FORMAT_AUTO
FORMAT_XZ = FORMAT_XZ
FORMAT_ALONE = FORMAT_ALONE
FORMAT_RAW = FORMAT_RAW
CHECK_NONE = CHECK_NONE
CHECK_CRC32 = CHECK_CRC32
CHECK_CRC64 = CHECK_CRC64
CHECK_SHA256 = CHECK_SHA256
from lzma import FILTER_LZMA1, FILTER_LZMA2, FILTER_DELTA, FILTER_X86, FILTER_IA64, FILTER_ARM, FILTER_ARMTHUMB, FILTER_POWERPC, FILTER_SPARC
FILTER_LZMA1 = FILTER_LZMA1
FILTER_LZMA2 = FILTER_LZMA2
