import lzma
lzma.open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
from lzma import open
