import mmap
# Test mmap.mmap()
#
# This test is based on the test_mmap.py test module from the Python
# standard library.

import os
import sys
import unittest
import mmap
import struct
import tempfile
import array
import warnings
import contextlib
import io
import random
import shutil
import stat
import time
import errno
import functools
import platform
import subprocess
import sysconfig
import textwrap
import threading
import weakref
import gc
import re
import io
import select
import socket
import signal
import atexit
import os
import sys
import unittest
import mmap
import struct
import tempfile
import array
import warnings
import contextlib
import io
import random
import shutil
import stat
import time
import errno
import functools
import platform
import subprocess
import sysconfig
import textwrap
import threading
import weakref
import gc
import re
import io
import select
import socket
import signal
import atexit
import os
import sys
import unittest
import mmap
import struct
import temp
