import mmap
# Test mmap.mmap()
f = open('./tmp/test.txt', 'r+b')
m = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_WRITE)
m.write('Hello world')
m.close()
f.close()
# Test mmap.mmap(-1)
f = open('./tmp/test2.txt', 'r+b')
m = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_WRITE)
m.write('Hello world')
m.close()
f.close()
# Test mmap.mmap(0)
f = open('./tmp/test3.txt', 'r+b')
m = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_WRITE)
m.write('Hello world')
m.close()
f.close()
