import mmap
# Test mmap.mmapfilebuffer.write()
f = open("dummyfile", "wb")
f.seek(1024*1024-1)
f.write(b'\0')
f.close()
f = open("dummyfile", "r+b")
b = mmap.mmapfilebuffer(f)
b.write(b"hello")
f.seek(1024*1024-6)
print(f.read(5))
b.close()
f.close()

f = open("dummyfile", "wb")
f.seek(1024*1024-1)
f.write(b'\0')
f.seek(0)
f.close()
f = open("dummyfile", "r+b")
b = mmap.mmapfilebuffer(f)
b.write(b"hello")
f.seek(1024*1024-6)
print(f.read(5))
b.close()
