import mmap
# Test mmap.mmap.resize
from mmap import ACCESS_DEFAULT, ACCESS_READ, ACCESS_WRITE, ACCESS_COPY
from mmap import ALLOCATIONGRANULARITY, ALLOCATIONGRANULARITY_HINT
from mmap import MAP_SHARED, MAP_PRIVATE, MAP_ANON
from mmap import MAP_ANONYMOUS, MAP_DENYWRITE, MAP_EXECUTABLE, MAP_GROWSDOWN
from mmap import MAP_HASSEMAPHORE, MAP_LOCKED, MAP_NONBLOCK, MAP_NORESERVE
