import mmap
# Test mmap.mmap(-1,0)
m = mmap.mmap(-1,0)
m.close()
# Test mmap.mmap(0,0)
m = mmap.mmap(0,0)
m.close()
# Test mmap.mmap(0,1)
m = mmap.mmap(0,1)
m.close()
# Test mmap.mmap(1,0)
m = mmap.mmap(1,0)
m.close()
# Test mmap.mmap(1,1)
m = mmap.mmap(1,1)
m.close()
# Test mmap.mmap(1,1,0)
m = mmap.mmap(1,1,0)
m.close()
# Test mmap.mmap(1,1,mmap.MAP_SHARED)
m = mmap.mmap(1,1,mmap.MAP_SHARED)
m.close()
# Test mmap.mmap(1,1,mmap.MAP_PRIVATE)
