import mmap
# Test mmap.mmap.write
m = mmap.mmap(-1, 1)
m.write(b"a")
m.write(b"b")
m.write(b"c")
m.write(b"d")
m.write(b"e")
m.write(b"f")
m.write(b"g")
m.write(b"h")
m.write(b"i")
m.write(b"j")
m.write(b"k")
m.write(b"l")
m.write(b"m")
m.write(b"n")
m.write(b"o")
m.write(b"p")
m.write(b"q")
m.write(b"r")
m.write(b"s")
m.write(b"t")
m.write(b"u")
m.write(b"v")
m.write(b"w")
m.write(b"x")
