import mmap
# Test mmap.mmap()
# mmap.mmap(fileno, length, flags=ACCESS_DEFAULT, prot=PROT_DEFAULT, access=ACCESS_DEFAULT, offset=0) -> mmap object
# mmap.ACCESS_COPY (0)
# mmap.ACCESS_READ (1)
# mmap.ACCESS_WRITE (2)
# mmap.ACCESS_DEFAULT (3)
# mmap.MAP_SHARED (1)
# mmap.MAP_PRIVATE (2)
# mmap.MAP_DENYWRITE (32)
# mmap.MAP_EXECUTABLE (64)
# mmap.MAP_ANONYMOUS (256)
# mmap.MAP_32BIT (8192)
# mmap.MAP_NORESERVE (16384)
# mmap.MAP_GROWSDOWN (131072)
# mmap.MAP_POPULATE (32768)
# mmap.MAP_NONBLOCK (65536)
# mmap.MAP_STACK (134217728)
