import mmap
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc__
# Test mmap.mmap.__doc
