import mmap
# Test mmap.mmap()
a = mmap.mmap(0, 100)
# Test mmap.mmap().close()
a.close()
# Test mmap.mmap().find()
a = mmap.mmap(0, 100)
x = a.find('\x00')
y = a.find('\x00', x+1)
a.close()
# Test mmap.mmap().flush()
a = mmap.mmap(0, 100)
a.flush()
a.close()
# Test mmap.mmap().find()
a = mmap.mmap(0, 100)
x = a.find('\x00')
y = a.find('\x00', x+1)
a.close()
# Test mmap.mmap().move()
a = mmap.mmap(0, 100)
a.move(10, 20, 40)

test_support.run_unittest(MmapTests)

