import mmap
# Test mmap.mmap()
f = open("/home/sree/Desktop/test.txt", "r+")
m = mmap.mmap(f.fileno(), 0)
m.write("Hello")
m.close()
f.close()
# Test mmap.mmap()
f = open("/home/sree/Desktop/test.txt", "r+b")
m = mmap.mmap(f.fileno(), 0)
m.write("Hello")
m.close()
f.close()
# Test mmap.mmap()
f = open("/home/sree/Desktop/test.txt", "r+b")
m = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_WRITE)
m.write("Hello")
m.close()
f.close()
# Test mmap.mmap()
f = open("/home/sree/Desktop/test.txt", "r+b")
m = mmap.mmap(f.fileno(), 0, access=mmap.ACCESS_READ)
