import mmap
# Test mmap.mmap.read_byte()
# Test mmap.mmap.read()
# Test mmap.mmap.read_byte()
# Test mmap.mmap.write_byte()
# Test mmap.mmap.write()
# Test mmap.mmap.find()
# Test mmap.mmap.rfind()
# Test mmap.mmap.tell()
# Test mmap.mmap.seek()
# Test mmap.mmap.size()
# Test mmap.mmap.move()
# Test mmap.mmap.close()
# Test mmap.mmap.closed()
# Test mmap.mmap.flush()
# Test mmap.mmap.find()
# Test mmap.mmap.rfind()
# Test mmap.mmap.tell()
# Test mmap.mmap.seek()
# Test mmap.mmap.size()
# Test mmap.mmap.move()
# Test mmap.mmap.close()
# Test mmap.mmap.closed()
# Test mmap.mmap.flush()
#
