import mmap
# Test mmap.mmap()
print(mmap.mmap(-1,1024))
# Test mmap.mmap(fileno)
tmp = open('tmp','w+b')
tmp.write(b'\x01\x02\x03\x04')
m = mmap.mmap(tmp.fileno(),4)
print('mmap(fileno) =',m)
m.close()
# Test mmap.mmap(fileno, 4096)
tmp = open('tmp','w+b')
tmp.write(b'\x01\x02\x03\x04')
m = mmap.mmap(tmp.fileno(),4096)
print('mmap(fileno, 4096) =',m)
m.close()
# Test mmap.mmap(fileno, 0)
tmp = open('tmp','w+b')
tmp.write(b'\x01\x02\x03\x04')
