fn = lambda: None
gi = (i for i in ())
fn.__code__ = gi.gi_code
fn.__name__ = '<lambda>'
fn.__qualname__ = '<lambda>'
fn.__module__ = '__main__'
fn.__annotations__ = {}
fn.__kwdefaults__ = None
fn.__defaults__ = ()
