import selectors
import socket
import sys
import time

from pymodbus.client.sync import ModbusTcpClient as ModbusClient
from pymodbus.exceptions import ConnectionException
from pymodbus.constants import Endian
from pymodbus.payload import BinaryPayloadDecoder
from pymodbus.payload import BinaryPayloadBuilder
from pymodbus.register_read_message import ReadInputRegistersResponseBase
from pymodbus.register_read_message import ReadHoldingRegistersResponseBase
from pymodbus.register_write_message import WriteMultipleRegistersRequest
from pymodbus.register_write_message import WriteSingleRegisterRequest
from pymodbus.bit_read_message import ReadCoilsResponseBase
from pymodbus.bit_read_message import ReadDiscreteInputsResponseBase
from pymodbus.bit_write_message import WriteMultipleCoilsRequest
from pymodbus.bit_write_message import WriteSingleCoilRequest

from pymodbus.constants import Defaults
