import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from ui_mainwindow import Ui_MainWindow
from ui_aboutdialog import Ui_AboutDialog
from ui_settingsdialog import Ui_SettingsDialog
from ui_preferencesdialog import Ui_PreferencesDialog
from ui_addbookmarkdialog import Ui_AddBookmarkDialog
from ui_bookmarksdialog import Ui_BookmarksDialog
from ui_bookmarkwidget import Ui_BookmarkWidget
from ui_bookmarkwidget_dialog import Ui_BookmarkWidgetDialog
from ui_bookmarkwidget_dialog_edit import Ui_BookmarkWidgetDialogEdit
from ui_bookmarkwidget_dialog_delete import Ui_BookmarkWidgetDialogDelete
from ui_bookmarkwidget_dialog_move import Ui_BookmarkWidgetDialogMove
