import signal
# Test signal.setitimer
signal.setitimer(signal.ITIMER_REAL, 0.1, 0.1)
time.sleep(0.2)
signal.setitimer(signal.ITIMER_REAL, 0.1, 0.1)
time.sleep(0.2)
signal.setitimer(signal.ITIMER_REAL, 0.1, 0.1)
time.sleep(0.2)
signal.setitimer(signal.ITIMER_REAL, 0.1, 0.1)
time.sleep(0.2)
signal.setitimer(signal.ITIMER_REAL, 0.1, 0.1)
time.sleep(0.2)
signal.setitimer(signal.ITIMER_REAL, 0.1, 0.1)
time.sleep(0.2)
signal.setitimer(signal.ITIMER_REAL, 0.1, 0.1)
time.sleep(0.2)
