import socket
# Test socket.if_indextoname()

def test_if_indextoname():
    print("Testing socket.if_indextoname()...")
    print("If you don't see any errors, it's working.")
    print("If you see an error, it's not working.")
    print("")
    print("This test will take a while, as it will test all possible interface indexes.")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
