import socket
# Test socket.if_indextoname()
print(socket.if_indextoname(1))
# Test socket.if_nameindex()
print(socket.if_nameindex())
# Test socket.if_nametoindex()
print(socket.if_nametoindex('lo'))
# Test socket.getaddrinfo()
print(socket.getaddrinfo('www.baidu.com', 80))
# Test socket.getfqdn()
print(socket.getfqdn('www.baidu.com'))
# Test socket.gethostbyaddr()
print(socket.gethostbyaddr('8.8.8.8'))
# Test socket.gethostbyname()
print(socket.gethostbyname('www.baidu.com'))
# Test socket.gethostbyname_ex()
print(socket.gethostbyname_ex('www.baidu.com'))
# Test socket.gethostname()
print(socket.gethostname())
# Test socket.getnameinfo()
