import socket
# Test socket.if_indextoname()
print(socket.if_indextoname(13))
print(socket.if_indextoname(14))
print(socket.if_indextoname(15))
print(socket.if_indextoname(16))
print(socket.if_indextoname(17))
print(socket.if_indextoname(18))
print(socket.if_indextoname(19))
print(socket.if_indextoname(20))
print(socket.if_indextoname(21))
print(socket.if_indextoname(22))
print(socket.if_indextoname(23))
print(socket.if_indextoname(24))
print(socket.if_indextoname(25))
print(socket.if_indextoname(26))
print(socket.if_indextoname(27))
print(socket.if_indextoname(28))
print(socket.if_indextoname(29))
print(socket.if_indextoname(30))
print
