import socket
# Test socket.if_indextoname()
if_indextoname('5')
if_indextoname(5)
# Test socket.if_nameindex()
if_nameindex()
# Test socket.if_nametoindex()
if_nametoindex('lo')
if_nametoindex(b'lo')
# Test socket.gethostbyname()
gethostbyname('localhost')
gethostbyname(b'localhost')
# Test socket.gethostbyname_ex()
gethostbyname_ex('localhost')
gethostbyname_ex(b'localhost')
# Test socket.gethostbyaddr()
gethostbyaddr('127.0.0.1')
gethostbyaddr(b'127.0.0.1')
# Test socket.gethostname()
gethostname()
# Test socket.getfqdn()
getfqdn()
# Test socket.getprotobyname()
getprotobyname('tcp')
getprotobyname(b'tcp')
# Test socket.getservbyname()
getservbyname('http')
getservbyname
