import socket
# Test socket.if_indextoname
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))
sock.bind(('', 0))

