import ctypes
import ctypes.util
import threading
import sqlite3
import time
import os.path

#constants for hardware abstraction
TIMER_TICKS_PER_SECOND = 64.0
PI_DEGREES_PER_PULSE = 1024.0
PI_DEGREES_PER_SECOND = PI_DEGREES_PER_PULSE * TIMER_TICKS_PER_SECOND
PI_SECONDS_PER_PULSE = 1/PI_DEGREES_PER_PULSE
PI_SECONDS_PER_DEGREE = 1/PI_DEGREES_PER_SECOND

# constants for core library
LOCAL_TIMER_TICKS_PER_SECOND = 2.0
PIGPIO_DEGREES_PER_PULSE = 4096.0
PIGPIO_DEGREES_PER_SECOND = PIGPIO_DEGREES_PER_PULSE * LOCAL_TIMER_TICKS_PER_SECOND
PIGPIO_SECONDS_PER_PULSE = 1/PIGP
