import _struct
import _thread
import _threading
import _time
import _traceback
import _types
import _warnings
import _weakref
import _weakrefset
import _winreg
import _xxsubinterpreters
import array
import audioop
import binascii
import cPickle
import cStringIO
import cmath
import collections
import contextlib
import copy
import copy_reg
import datetime
import errno
import exceptions
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fpectl
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import hotshot
import hotshot.stats
import htmlentitydefs
import htmllib
import httplib
import idlelib
import imaplib
import imghdr
import imp
import inspect
import keyword
import linecache
import locale
import macpath
import macurl2path
import mailbox
import mailcap

