import _struct
import _sys
import _thread
import _threading
import _time
import _traceback
import _types
import _warnings
import _weakref

# Import the built-in modules.
import _aifc
import _anydbm
import _asynchat
import _asyncio
import _asyncore
import _audioop
import _binascii
import _cmath
import _codecs
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _collections
import _colorsys
import _compileall
import _compiler
import _contextvars
import _crypt
import _csv
import _ctypes
import _curses
import _curses_panel
import _datetime
import _dbm
import _decimal
import _difflib
import _dummy_thread
import _email
import _encodings
import _functools
import _gc
import _hashlib
