import _struct
import _sys
import _sysconfig
import _testcapi
import _thread
import _threading
import _tkinter
import _tokenize
import _tracemalloc
import _uuid
import _warnings
import _weakref
import array
import atexit
import audioop
import binascii
import cmath
import cPickle
import cProfile
import cStringIO
import ctypes
import curses
import datetime
import dbhash
import dbm
import decimal
import errno
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fpformat
import fractions
import ftplib
import gc
import getopt
import getpass
import gettext
import glob
import gzip
import heapq
import hmac
import hotshot
import htmlentitydefs
import htmllib
import httplib
import idlelib
import imaplib
import imghdr
import imp
import inspect
import itertools
import jpeg
import keyword
import lib2to3
import linecache
import locale
import logging
