import _struct
import _syslog
import _testcapi
import _testbuffer
import _testimportmultiple
import _testinternalcapi
import _testmultiphase
import _thread
import _tkinter
import _warnings
import _weakref
import array
import audioop
import binascii
import cmath
import cPickle
import cStringIO
import csv
import datetime
import dbm
import dl
import errno
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fpectl
import fractions
import ftplib
import gc
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import hotshot
import htmlentitydefs
import htmllib
import httplib
import imageop
import imaplib
import imghdr
import imp
import inspect
import io
import keyword
import lib2to3
import linecache
import locale
import logging
import macpath
import macurl2path
import mailcap
import mailbox

