import _struct
# Test _struct.Struct.__repr__
print(_struct.Struct('h'))
print(_struct.Struct('i'))
print(_struct.Struct('q'))
print(_struct.Struct('H'))
print(_struct.Struct('I'))
print(_struct.Struct('Q'))
print(_struct.Struct('f'))
print(_struct.Struct('d'))
print(_struct.Struct('s'))
print(_struct.Struct('p'))
print(_struct.Struct('P'))
print(_struct.Struct('s'))
print(_struct.Struct('x'))
print(_struct.Struct('c'))
print(_struct.Struct('b'))
print(_struct.Struct('B'))
print(_struct.Struct('?'))
print(_struct.Struct('hhi'))
print(_struct.Struct('fdfsPxcbB?'))
print(_struct.Struct('=hhi'))
print(_struct.Struct('@hhi'))
print(_struct.Struct('<hhi'))
print(_struct.Struct('>hhi'))
