import _struct
import _thread
import _threading
import _time
import _warnings
import _weakref
import array
import atexit
import binascii
import builtins
import codecs
import collections
import contextlib
import copy
import ctypes
import datetime
import decimal
import dis
import errno
import faulthandler
import filecmp
import fnmatch
import functools
import gc
import getopt
import getpass
import gettext
import glob
import grp
import gzip
import hashlib
import heapq
import hmac
import http
import idlelib
import imaplib
import imghdr
import imp
import importlib
import inspect
import io
import ipaddress
import json
import keyword
import lib2to3
import linecache
import locale
import logging
import lzma
import macpath
import macurl2path
import mailbox
import mailcap
import marshal
import math
import mimetypes
import mmap
import modulefinder
import msilib
import msvcrt
import netrc
import nntplib
import ntpath
