import _struct
import _thread
import _threading_local
import _time
import _tracemalloc
import _warnings
import _weakref
import _weakrefset
import array
import atexit
import audioop
import binascii
import builtins
import bz2
import cmath
import codecs
import codeop
import collections
import colorsys
import contextlib
import copyreg
import crypt
import csv
import datetime
import dbm
import decimal
import difflib
import dis
import doctest
import dummy_threading
import email
import encodings
import enum
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import html
import http
import idlelib
import imaplib
import imghdr
import imp
import importlib
import inspect
