import _struct
import _thread
import _threading_local
import _warnings
import _weakref
import _weakrefset
import array
import atexit
import audioop
import binascii
import builtins
import cmath
import collections
import cPickle
import cStringIO
import csv
import datetime
import errno
import exceptions
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fpectl
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import hotshot
import hotshot.stats
import htmlentitydefs
import htmllib
import httplib
import idlelib
import imaplib
import imghdr
import imp
import importlib
import inspect
import io
import keyword
import lib2to3
import linecache
import locale
import logging
import macpath
import macurl2path
import mailbox
import mailcap
import markupbase
import marshal

