import _struct
import _codecs
import _weakref
import _random
import _bisect
import _heapq
import _collections
import _ssl
import _hashlib
import _socket
import _io
import _json
import _hmac
import _md5
import _sha1
import _sha256
import _sha512
import _sha3
import _blake2
import _sha3
import _gzip
import _bz2
import _lzma
import _select
import _thread
import _threading
import _multiprocessing

# Extensions
import _curses
import _curses_panel
import _testcapi
import _tkinter
import _uuid
import _ctypes
import _sqlite3
import _elementtree
import _posixsubprocess
import _asyncio
import _multibytecodec
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _
