import _struct
import _thread
import _threading
import _time
import _tkinter
import _traceback
import _types
import _warnings
import _weakref
import array
import audioop
import binascii
import cPickle as pickle
import cStringIO as StringIO
import cmath
import collections
import copy
import datetime
import dis
import errno
import exceptions
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fpectl
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import heapq
import hmac
import hotshot
import hotshot.stats
import htmlentitydefs
import htmllib
import httplib
import ic
import imageop
import imghdr
import imp
import importlib
import inspect
import io
import keyword
import linecache
import locale
import logging
import logging.config
import logging.handlers
import macpath
import macurl2path
import mailbox
