from _struct import Struct
s = Struct.__new__(Struct)
s.__init__('<i', 4)
print(s.size)
print(s.pack(1))
print(s.pack(2))
print(s.pack(3))
print(s.pack_into(bytearray(4), 0, 4))
print(s.pack_into(bytearray(4), 0, 5))
print(s.pack_into(bytearray(4), 0, 6))
print(s.pack_into(bytearray(4), 0, 7))
print(s.pack_into(bytearray(4), 0, 8))
print(s.pack_into(bytearray(4), 0, 9))
print(s.pack_into(bytearray(4), 0, 10))
print(s.pack_into(bytearray(4), 0, 11))
print(s.pack_into(bytearray(4), 0, 12))
print(s.pack_into(bytearray(4), 0, 13))
