import _struct
import _thread
import _threading_local
import _tracemalloc
import _tracemalloc_impl
import _warnings
import _weakref
import abc
import aifc
import antigravity
import argparse
import ast
import asyncio
import asynchat
import asyncore
import atexit
import audioop
import base64
import bdb
import binascii
import binhex
import bisect
import builtins
import bz2
import cProfile
import cStringIO
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import collections
import colorsys
import compileall
import concurrent
import configparser
import contextlib
import contextvars
import copy
import copyreg
import crypt
import csv
import ctypes
import curses
import dataclasses
import datetime
import dbm
import decimal
import difflib
import dis
import distutils
import doctest
import dummy_threading
import email
import encodings
import ensurepip
import enum

