import _struct
import _string
import _random
import _re
import _curses
import _curses_panel
import _codecs
import _socket
import _ssl
import _hashlib
import _io
import _ast
import _bisect
import _heapq
import _weakref
import _collections
import _symtable
import _symtable_build
import _symtable_clinic
import _symtable_desc
import _symtable_eval
import _symtable_import
import _symtable_lookup
import _symtable_mod
import _symtable_sym
import _symtable_sym_clinic
import _symtable_sym_desc
import _symtable_sym_eval
import _symtable_sym_mod
import _symtable_sym_sym
import _symtable_test
import _testcapi
import _testbuffer
import _testcapimodule
import _testimportmultiple
import _testmultiphase
import _testpackage
import _testshared
import _testembed
import _testinternalcapi
import _testwindowserrno
import _thread
