import _struct
import _thread
import _threading
import _time
import _traceback
import _warnings
import _weakref
import _weakrefset
import _winapi
import _winreg
import _wintypes
import _xmlrpc_client
import _xmlrpc_server
import _zipfile
import abc
import aifc
import antigravity
import anydbm
import argparse
import ast
import asynchat
import asyncore
import audioop
import base64
import bdb
import binascii
import binhex
import bisect
import bsddb
import bz2
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import collections
import colorsys
import compileall
import concurrent
import configparser
import contextlib
import contextvars
import copy
import copyreg
import crypt
import csv
import ctypes
import curses
import datetime
import dbm
import decimal
import difflib
import dis
import distutils
