import _struct
import _thread
import _threading
import _time
import _warnings
import _weakref

import _ctypes
import _ctypes_test
import _testcapi
import _testbuffer
import _testimportmultiple
import _testinternalcapi
import _testmultiphase
import _testcapimodule
import _testcapi
import _testconsole
import _testwinreg
import _test_threading_local
import _test_threading
import _test_subprocess
import _test_io
import _test_sys_streams
import _test_sys
import _test_codecs
import _test_locale
import _test_site
import _test_types
import _test_zipimport
import _test_zipfile
import _test_gzip
import _test_bz2
import _test_lzma
import _test_tarfile
import _test_shutil
import _test_tempfile
import _test_shelve
import _test_hashlib
import _test_hmac
import _test_md5
import _test_
