import _struct
import _string
import _random
import _codecs
import sys
import _weakref
import _functools
import _operator
import _collections
import itertools
import _collections
import operator
import math
import _heapq
import _bisect
import _symtable
import array
import _types
import _localeconv
import _io
import marshal
import _imp
import _warnings
import errno
import _thread
import _locale
import _stat
import _sre
import _socket
import binascii
import _md5
import _sha1
import _sha256
import _sha512
import faulthandler
import _tracemalloc
import _sha3
import _blake2
import _hmac
import _hashlib
import _json
import _uuid
import _bz2
import _lzma
import _quopri
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs
