import _struct
import _sys
import _thread
import _threading
import _time
import _token
import _tokenize
import _traceback
import _traceback_data
import _tracemalloc
import _tuple
import _type_gen
import _types
import _typing
import _warnings
import _weakref
import abc
import audioop
import binascii
import builtins
import bz2
import calendar
import codecs
import collections
import collections.abc
import contextlib
import copyreg
import csv
import datetime
import decimal
import errno
import faulthandler
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import html
import http
import http.client
import imaplib
import imghdr
import imp
import importlib
import importlib.abc
import importlib.machinery
