import _struct
import _thread
import _threading_local
import _tracemalloc
import _tracemodule
import _trashcan
import _types
import _warnings
import _weakref
import abc
import aifc
import argparse
import ast
import asyncio
import asynchat
import asyncore
import base64
import bdb
import binhex
import bisect
import builtins
import bz2
import cProfile
import cStringIO
import calendar
import cgi
import chunk
import cmath
import cmd
import code
import codeop
import collections
import colorsys
import compileall
import concurrent
import configparser
import contextlib
import copy
import copyreg
import crypt
import csv
import ctypes
import curses
import datetime
import decimal
import difflib
import dis
import distutils
import doctest
import dummy_threading
import email
import encodings
import enum
import errno
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import ftplib
