import _struct
import _string
import _time
import _xxsubinterpreters
import _io
import _pickle
import _random
import _imp
import _cmath
import _operator
import _collections
import _elementtree
import _socket
import _sqlite3
import _ssl
import _weakref
import _testcapi
import _codecs
import _json
import _ctypes
import _abc
import _bisect
import _heapq
import _posixsubprocess
import _posixshmem
import _posixsemaphore
import _posixmultiprocessing
import _posixsubprocess
import _msi
import _lzma
import _winreg
import _lsprof
import _multiprocessing
import _hotshot
import _csv
import _ctypes
import _testbuffer
import _testimportmultiple
import _testcapimodule
import _tkinter
import _testcapi
import _testinternalcapi
import _ctypes_test
import _testmultiphase
import _testcodedirs
import _testimportstar
import _
