import _struct
import _thread
import _threading
import _time
import _warnings
import _weakref
import _weakrefset
import _winreg
import array
import audioop
import binascii
import bz2
import cPickle
import cStringIO
import cmath
import collections
import colorsys
import compiler
import contextlib
import copy
import copy_reg
import csv
import datetime
import decimal
import difflib
import dircache
import dis
import distutils
import doctest
import dumbdbm
import dummy_thread
import dummy_threading
import email
import encodings
import errno
import exceptions
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fpformat
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import hotshot
import hotshot.stats
