import _struct
import _thread
import _threading
import _time
import _traceback
import _types
import _warnings
import _weakref
import _weakrefset
import _winreg
import _xmlrpclib
import _zipfile
import _zlib
import _zmq
import __builtin__
import __future__
import __main__
import __phello__.foo
import __phello__.spam
import _abc
import _codecs
import _collections
import _csv
import _dummy_thread
import _functools
import _hashlib
import _heapq
import _io
import _json
import _locale
import _lsprof
import _md5
import _multibytecodec
import _multiprocessing
import _operator
import _pickle
import _posixsubprocess
import _random
import _sha
import _sha256
import _sha512
import _socket
import _sqlite3
import _sre
import _ssl
import _struct
import _symtable
import _thread
import _threading
