import _struct
import _thread
import _threading_local
import _weakref

import _collections
import _collections_abc
import _functools
import _heapq
import _imp
import _io
import _locale
import _operator
import _pickle
import _random
import _socket
import _sre
import _stat
import _string
import _symtable
import _tracemalloc
import _warnings
import _weakref

import _abc
import _ast
import _bisect
import _codecs
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _contextvars
import _csv
import _datetime
import _functools
import _hashlib
import _heapq
import _json
import _locale
import _lsprof
import _lzma
import _md5
import _multibytecodec
import _multiprocessing
import _op
