import _struct
import _time
import _thread
import _threading
import _traceback
import _types
import _warnings
import _weakref
import _weakrefset
import _winreg

# The following modules are not builtin, but are included in the standard
# library.
import _ast
import _bisect
import _codecs
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _collections
import _csv
import _datetime
import _functools
import _heapq
import _hotshot
import _io
import _json
import _locale
import _lsprof
import _md5
import _multibytecodec
import _multiprocessing
import _random
import _sha
import _sha256
import _sha512
import _socket
import _sre
import _ssl
import _struct
import _symtable
import _threading_local
import _weakref
