import _struct
import _thread
import _threading
import _time
import _warnings
import _weakref
import _weakrefset
import array
import audioop
import binascii
import cmath
import cPickle
import cStringIO
import csv
import datetime
import errno
import exceptions
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fpectl
import fractions
import ftplib
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import gzip
import hashlib
import heapq
import hmac
import hotshot
import hotshot.stats
import htmlentitydefs
import htmllib
import httplib
import idlelib.TreeWidget
import imaplib
import imghdr
import imp
import inspect
import io
import keyword
import linecache
import locale
import macpath
import macurl2path
import mailbox
import mailcap
import marshal
import math
import md5
import mhlib
import mimetools
import mimetypes
