import _struct
import _thread
import _threading
import _time
import _warnings
import _weakref
import _weakrefset
import abc
import ast
import asyncio
import collections
import contextlib
import copy
import copyreg
import dis
import enum
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import functools
import genericpath
import getopt
import getpass
import gettext
import glob
import grp
import gzip
import hashlib
import heapq
import hmac
import html
import http
import idlelib
import imaplib
import imghdr
import imp
import importlib
import inspect
import io
import ipaddress
import itertools
import json
import keyword
import lib2to3
import linecache
import locale
import logging
import macpath
import mailcap
import mailbox
import modulefinder
import multiprocessing
import netrc
import nntplib
import ntpath
import numbers
import opcode
import operator
import optparse
import os
import pdb
import pickle
import pickletools
