import _struct
import _string
import _collections
import _weakref
import _heapq
import _bisect
import _random
import _io
import _pickle
import _imp
import _thread
import _warnings
import _weakref
import _abc
import _functools
import _operator
import _contextvars
import _testcapi
import _locale
import _stat
import _asyncio
import _signal
import _faulthandler
import _tracemalloc
import _posixsubprocess
import _multiprocessing
import _ast
import _sitebuiltins
import _py_abc
import _pyio
import _encodings
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _winapi
import _lsprof
import _testbuffer
import _ctypes
import _testcapi
import _testimportmultiple
import _decimal
import _datetime
import _
