import _struct
import _thread
import _threading
import _time
import _warnings
import _weakref
import _weakrefset
import _winreg
import _winxptheme
import _xxsubinterpreters
import abc
import array
import ast
import asynchat
import asyncore
import atexit
import audioop
import base64
import bdb
import binascii
import binhex
import bisect
import bsddb
import bz2
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import colorsys
import commands
import compileall
import compiler
import contextlib
import cookielib
import copy
import copy_reg
import cPickle
import crypt
import csv
import cStringIO
import ctypes
import curses
import datetime
import dbhash
import decimal
import difflib
import dircache
import dis
import distutils
import doctest
import dumbdbm
import dummy_thread
import dummy_threading
import email
import encodings

