from _struct import Struct
s = Struct.__new__(Struct)
s.__setattr__('format', 'NNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNldaNNLdaNNL')
n = 0
