import _struct
import _string
import _sys
import _thread
import _time
import _traceback
import _types
import _weakref
import _warnings
import _weakrefset
import _winreg
import _xxsubinterpreters
import _zipimport
import _zlib

# These modules are not built-in, but we know they are always present.
import _codecs
import _weakref
import _random
import _bisect
import _heapq
import _lsprof
import _collections
import _symtable
import _socket
import _ssl
import _hashlib
import _io
import _ast
import _md5
import _sha
import _sha256
import _sha512
import _winreg
import _sre
import _pickle
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _subprocess
import _multibytecodec
import _struct
import _datetime
