import _struct
import _strptime
import _socket
import _ssl
import _symtable
import _symtable_build
import _testcapi
import _thread
import _threading_local
import _tkinter
import _warnings
import _weakref
import _weakrefset
import _winapi
import array
import atexit
import audioop
import binascii
import cPickle
import cStringIO
import cmath
import collections
import copy
import ctypes
import datetime
import errno
import exceptions
import fcntl
import filecmp
import fileinput
import fnmatch
import formatter
import fractions
import ftplib
import functools
import gc
import getopt
import getpass
import gettext
import glob
import gzip
import heapq
import hmac
import hotshot
import hotshot.log
import hotshot.stats
import htmlentitydefs
import htmllib
import httplib
import ic
import imageop
import imaplib
import imghdr
import imp
import imputil
import inspect
import io
import keyword

