import _struct
import _string
import _random
import _math
import _io
import _time
import _datetime
import _hashlib
import _select
import _socket
import _ssl
import _thread
import _multiprocessing
import _ctypes
import _signal
import _mmap
import _curses
import _curses_panel
import _dbm
import _sqlite3
import _json
import _bz2
import _lzma
import _zipfile
import _tarfile
import _codecs
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _winreg
import _winsound
import _symtable
import _xxsubtype
import _testcapi
import _testbuffer
import _testimportmultiple
import _testinternalcapi
import _testmultiphase
import _testpackage
import _testcapimodule
import _testcodec
