import _struct
import _thread
import _threading
import _time
import _traceback
import _types
import _warnings
import _weakref

# The following modules are built-in but not automatically imported
# when the interpreter starts.
import _string
import _sre
import _codecs
import _weakref
import _random
import _bisect
import _heapq
import _symtable
import _collections
import _symtable
import _functools
import _operator
import _pickle
import _datetime
import _json
import _io
import _stat
import _md5
import _sha
import _sha256
import _sha512
import _bz2
import _pyio
import _gzip
import _zipfile
import _multiprocessing
import _socket
import _ssl
import _select
import _sqlite3
import _zlib
import _lzma
import _hashlib
import _binascii
import _ctypes
import _cmath
import _math
import _decimal
import _elementtree
import _struct
import _
