import _struct
import _sys
import _test
import _thread
import _time
import _unicodedata
import _warnings
import _weakref
import _weakrefset
import abc
import array
import atexit
import base64
import binascii
import bisect
import cmath
import codecs
import collections
import copyreg
import copy
import datetime
import dis
import enum
import errno
import fcntl
import filecmp
import fileinput
import fnmatch
import functools
import glob
import gc
import getopt
import getpass
import gettext
import grp
import hashlib
import heapq
import hmac
import html
import http
import idlelib
import imaplib
import imp
import inspect
import io
import itertools
import json
import keyword
import lib2to3
import linecache
import locale
import logging
import lzma
import macpath
import macurl2path
import mailbox
import mailcap
import math
import mimetypes
import mmap
import modulefinder
import msilib
import msvcrt
