import _struct
import _thread
import _threading
import _time
import _timeit
import _token
import _tokenize
import _traceback
import _tracemalloc
import _tty
import _turtle
import _types
import _typing
import _uu
import _uuid
import _warnings
import _weakref
import _webbrowser
import _winreg
import _winsound
import _wsgiref
import _xdrlib
import _xml
import _xmlrpc
import _zipapp
import _zipfile
import _zipimport
import _zlib
import abc
import aifc
import antigravity
import argparse
import ast
import asynchat
import asyncore
import base64
import bdb
import binascii
import binhex
import bisect
import builtins
import bz2
import cProfile
import cPickle
import cStringIO
import calendar
import cgi
import cgitb
import chunk
import cmd
import code
import codeop
import codecs
import codeop
