import _struct
import _sys
import _thread
import _time
import _traceback
import _types
import _warnings
import _weakref

# Import the built-in modules.
import __builtin__
import _codecs
import _collections
import _csv
import _functools
import _hashlib
import _heapq
import _io
import _json
import _locale
import _random
import _socket
import _sre
import _string
import _struct
import _symtable
import _warnings
import _weakref

# Import the standard modules.
import _codecs
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _collections
import _csv
import _functools
import _hashlib
import _heapq
import _io
import _json
import _locale
import _lsprof
import _md5
import _multibytecodec
import _random
