import _struct
import _glob
import _operator
import _collections
import _weakref
import _new
import _ast
import _string
import _sysconfigdata
import _heapq
import _pickle
import _collections_abc
import _overlapped
import _random
import _posixsubprocess
import _winreg
import _functools
import _abc
import _py_abc
import _weakrefset
import _codecs
import _sitebuiltins
import _enum
import _bisect
import _bytesio
import _hashlib
import _sha1
import _sha256
import _sha512
import _md5
import _imp
import _contextvars
import _stat
import _operator
import _json
import _io
import _fileio
import _pyio
import _textio
import _bufferedio
import _cmemodule
import _io_popen
import _io_textiowrapper
import _io_stringio
import _io_bytesio
import _io_bufferedreader
import _io_bufferedwriter
import _io
