import _struct
import _thread
import _threading
import _time
import _traceback
import _types
import _warnings
import _weakref
import _weakrefset
import _winreg

import _asynciomodule
import _bisectmodule
import _codecsmodule
import _collectionsmodule
import _csvmodule
import _datetimemodule
import _functoolsmodule
import _heapqmodule
import _impmodule
import _io
import _json
import _locale
import _lsprofmodule
import _md5module
import _multibytecodecmodule
import _multiprocessing
import _opcode
import _operator
import _pickle
import _posixsubprocess
import _random
import _sha1module
import _sha256module
import _sha512module
import _signalmodule
import _socket
import _sre
import _ssl
import _stat
import _string
import _struct
import _symtablemodule
import _threadmodule
import _tracemalloc
import _weakref
import _weakrefset
import _win
