import _struct
import _sys
import _thread
import _time
import _traceback
import _types
import _warnings
import _weakref

# Import the builtin modules.
import __builtin__
import exceptions
import gc
import imp
import marshal
import posix
import pwd
import signal
import sys
import thread
import time
import traceback

# Import the standard modules.
import __future__
import __main__
import _ast
import _bisect
import _codecs
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _collections
import _csv
import _functools
import _heapq
import _io
import _locale
import _lsprof
import _md5
import _multibytecodec
import _random
import _sha
import _sha256
import _sha512
import _sre
import _string
import _struct
import _symtable
