import _struct
import _json
import _io
import _time
import _random
import _collections
import _thread
import _sys
import _math

# some of the standard library modules are not available on micropython
try:
    import _hashlib
except ImportError:
    _hashlib = None
try:
    import _binascii
except ImportError:
    _binascii = None

# this is a list of the modules that are available on micropython
# it is used to determine which modules are available on micropython
# and which modules are not
#
# the list is generated by running the following command on a micropython
# installation:
#
# find . -name \*.py | sed 's/^\.\///' | sed 's/\.py$//' | sort
#
# this list is only used for the purpose of testing
#
# the following modules are not available on micropython:
#
#    _ssl
#    _hashlib
#    _binascii
#    _cmath
#    _ctypes
#    _
