import _struct
import _time
import _thread
import _weakref
import _weakrefset
import _winapi
import _weakref
import _weakrefset
import _winapi
import _winreg
import _winsound
import _xmlrpc
import _zipfile
import _zlib
import _random
import _bisect
import _heapq
import _collections
import _socket
import _ssl
import _asyncio
import _asynciomodule
import _asynciosubprocess
import _asynciosocket
import _asynciodns
import _asynciotools
import _asynciotime
import _asynciowinreg
import _asynciowinsound
import _asynciowinbase
import _asynciowinerror
import _asynciowinconsole
import _asynciowinpipe
import _asynciowinprocess
import _asynciowinsecurity
import _asynciowinstream
import _asynciowinapi
import _asynciowinfile
import _asyn
