import _struct as struct
import _csv as csv
import _random as random
import _heapq as heapq
import _bisect as bisect
import _hashlib as hashlib
import _hmac as hmac
import _itertools as itertools
import _collections as collections
import _ssl as ssl
import _thread as thread
import _locale as locale
import _codecs as codecs
import _io as io
import _zipfile as zipfile
import _gzip as gzip
import _bz2 as bz2
import _lzma as lzma
import _crypt as crypt
import _json as json
import _base64 as base64
import _uu as uu
import _binascii as binascii
import _pickle as pickle
import _dbm as dbm
import _sqlite3 as sqlite3
import _syslog as syslog
import _hotshot as hotshot
import _xmlrpc as xmlrpc
import _curses as curses
import _curses_panel as curses_panel
import _readline as readline
