import _struct
import _thread
import _threading
import _time
import _traceback
import _types
import _warnings
import _weakref

# These modules are not builtin, but are included with Python.
import _abc
import _ast
import _bisect
import _blake2
import _codecs
import _codecs_cn
import _codecs_hk
import _codecs_iso2022
import _codecs_jp
import _codecs_kr
import _codecs_tw
import _collections
import _collections_abc
import _contextvars
import _csv
import _datetime
import _decimal
import _functools
import _hashlib
import _heapq
import _imp
import _io
import _json
import _locale
import _lsprof
import _lzma
import _md5
import _multibytecodec
import _opcode
import _operator
import _pickle
import _posixsubprocess
import _random
import _sha1
import _sha256
import _sha3
