import _struct
import _threading
import _time
import _timeit
import _types
import _warnings
import _weakref
import _webbrowser
import _winreg
import _xml
import _xmlrpclib
import _zipfile
import _zlib
import abc
import aifc
import antigravity
import anydbm
import argparse
import ast
import asynchat
import asyncore
import atexit
import audiodev
import audioop
import base64
import bdb
import binascii
import binhex
import bisect
import bsddb
import bz2
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import collections
import colorsys
import commands
import compileall
import contextlib
import Cookie
import cookielib
import copy
import cPickle
import cProfile
import crypt
import csv
import ctypes
import ctypes.util
import curses
import curses.ascii
import curses.panel
import curses.textpad
