import _struct
import _tkinter
import _warnings
import _weakref
import _weakrefset
import abc
import aifc
import antigravity
import argparse
import ast
import asyncio
import asynchat
import asyncore
import atexit
import base64
import bdb
import binascii
import binhex
import bisect
import builtins
import bz2
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import collections
import colorsys
import compileall
import concurrent
import configparser
import contextlib
import copy
import copyreg
import cProfile
import crypt
import csv
import ctypes
import curses
import dataclasses
import datetime
import dbm
import decimal
import difflib
import dis
import distutils
import dl
import doctest
import dummy_threading
import email
import encodings
import enum
import errno
import faulthandler
import fcntl
import filecmp
import fileinput
import fnmatch
import form
