import _struct
import _thread
import _threading
import _time
import _traceback
import _types
import _warnings
import _weakref
import _weakrefset
import _winreg
import _winxptheme
import _xmlrpclib
import _zipfile
import _zlib
import array
import atexit
import audioop
import binascii
import bsddb
import bz2
import cPickle
import cStringIO
import calendar
import cgi
import cgitb
import chunk
import cmd
import code
import codecs
import codeop
import commands
import compiler
import contextlib
import cookielib
import copy
import copy_reg
import csv
import ctypes
import curses
import datetime
import dbhash
import decimal
import difflib
import dircache
import dis
import distutils
import doctest
import dumbdbm
import dummy_thread
import dummy_threading
import email
import encodings
import errno
import exceptions
import filecmp
import fileinput
import fnmatch
import formatter
import fpformat
