import _struct
import _thread
import _threading
import _time
import _traceback
import _types
import _warnings
import _weakref
import _weakrefset

# These modules are written in Python.
import abc
import aifc
import antigravity
import argparse
import ast
import asynchat
import asyncore
import base64
import bdb
import binascii
import bisect
import builtins
import bz2
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import collections
import colorsys
import compileall
import concurrent
import configparser
import contextlib
import copy
import copyreg
import crypt
import csv
import ctypes
import curses
import dataclasses
import datetime
import dbm
import decimal
import difflib
import dis
import distutils
import doctest
import dummy_threading
import email
import encodings
import ensurepip
import enum
import filecmp
import fileinput
import fnmatch
import formatter
import fractions

