import _struct
import _thread
import _threading_local
import _tracemalloc
import _tracemalloc_test
import _tracemalloc_test_embedded
import _tracemalloc_test_standalone
import _warnings
import _weakref
import _weakrefset
import abc
import aifc
import antigravity
import anydbm
import argparse
import ast
import asynchat
import asyncore
import atexit
import audioop
import base64
import bdb
import binascii
import binhex
import bisect
import builtins
import bz2
import cProfile
import calendar
import cgi
import cgitb
import chunk
import cmath
import cmd
import code
import codecs
import codeop
import collections
import colorsys
import compileall
import concurrent
import configparser
import configparser_tests
import contextlib
import contextlib_tests
import contextvars
import copy
import copyreg
import cProfile
import crypt
import csv
import ctypes
import curses
import dataclasses
import datetime
import d
