import _struct
# Test _struct.Struct()
_struct.Struct('hhl')
_struct.Struct(b'hhl')
# Test _struct.calcsize()
_struct.calcsize('hhl')
_struct.calcsize(b'hhl')
# Test _struct.pack()
_struct.pack('hhl', 1, 2, 3)
_struct.pack(b'hhl', 1, 2, 3)
_struct.pack('hhl', *[1, 2, 3])
_struct.pack(b'hhl', *[1, 2, 3])
b''.join([_struct.pack('hhl', 1, 2, 3)])
b''.join([_struct.pack(b'hhl', 1, 2, 3)])
# Test _struct.unpack()
_struct.unpack('hhl', b'\x00\x01\x00\x02\x00\x00\x00\x03')
