import _struct

_DOTSTAR_START = 0x50
_DOTSTAR_END = 0x51

_DOTSTAR_BRIGHTNESS = 0xE0
_DOTSTAR_CLEAR = 0xE1
_DOTSTAR_FILL = 0xE2
_DOTSTAR_SHOW = 0xE3
_DOTSTAR_SET_PIXEL = 0xE4
_DOTSTAR_GET_PIXEL = 0xE5

_DOTSTAR_GET_BRIGHTNESS = 0xE6
_DOTSTAR_SET_BRIGHTNESS = 0xE7
_DOTSTAR_AUTO_WRITE = 0xE8
_DOTSTAR_GET_AUTO_WRITE = 0xE9

_DOTSTAR_COLOR = 0xEA
_DOTSTAR_GET_COLOR = 0xEB

_DOTSTAR_SHIFT = 0xEC
_DOTSTAR_GET_SHIFT = 0xED

_DOTSTAR_SPEED_HZ = 0xEE
