import threading
threading.Thread(target=lambda: print(2))
threading.Thread(target=lambda: print(2)).start()
run_until_complete(asyncio.sleep(0))
run_until_complete(asyncio.sleep(0))
run_until_complete(asyncio.sleep(0))
run_until_complete(asyncio.sleep(0))
run_until_complete(asyncio.sleep(0))
run_until_complete(asyncio.sleep(0))
run_until_complete(asyncio.sleep(0))
th=threading.Thread(target=lambda: print(2))
th.start()
th.join()
th=threading.Thread(target=lambda: print(2))
th.start()
th.join()
run_until_complete(asyncio.sleep(1))
run_until_complete(asyncio.sleep(5))
run_until_complete(asyncio.sleep(5))
run_until_complete(asyncio.sleep(5))
