import types
types.FunctionType = types.LambdaType

import sys
import os
import re
import time
import subprocess
import signal
import logging
import logging.handlers
import threading
import traceback
import json
import copy
import socket
import random
import string
import urllib
import urllib2
import urlparse
import hashlib
import base64
import hmac
import uuid
import getpass
import platform
import tempfile
import shutil
import zipfile
import tarfile
import stat
import pwd
import grp
import ConfigParser
import cStringIO
import cPickle
import datetime
import math
import glob
import smtplib
import email
import email.mime.multipart
import email.mime.text
import email.mime.application
import email.utils
import csv
import gzip
import bz2
import hashlib
import mimetypes
import cgi
import tempfile
import shutil
import zipfile
import tarfile
import stat
import pwd
import grp
import ConfigParser
import cStringIO
