import types
types.new_class('S')
del types.S
SSL_ST_INIT = 5
SSL_ST_CONNECT = 4
SSL_ST_ACCEPT = 3
SSL_ST_MASK = 7
SSL_ST_INIT = 5
SSL_ST_BEFORE = 4
SSL_ST_OK = 3
SSL_ST_RENEGOTIATE = 2
SSL_FILETYPE_ASN1 = 2
SSL_FILETYPE_PEM = 1
SSL_ERROR_NONE = 0
SSL_ERROR_SSL = 1
SSL_ERROR_WANT_READ = 2
SSL_ERROR_WANT_WRITE = 3
SSL_ERROR_WANT_X509_LOOKUP = 4
SSL_ERROR_SYSCALL = 5
SSL_ERROR_ZERO_RETURN = 6
SSL_ERROR_WANT_CONNECT = 7
