import weakref

import numpy as np

from . import _pyglet
from . import gl
from . import glu
from . import gl_info
from . import clock
from . import event
from . import image
from . import resource
from . import font
from . import sprite
from . import text
from . import window
from . import app
from . import config
from . import compat_platform
from . import compat_os
from . import compat_set
from . import compat_stat
from . import compat_urllib
from . import media
from . import resource
from . import sprite
from . import text
from . import window
from . import media
from . import resource
from . import sprite
from . import text
from . import window
from . import media
from . import resource
from . import sprite
from . import text
from . import window
from . import media
from . import resource
from . import sprite
from . import text
from . import window
from . import media
from . import resource
from . import sprite
from . import text
from . import window
from . import media
