import weakref

from . import _util
from . import _py2to3
from . import _compat
from . import _errors
from . import _types
from . import _constants
from . import _lib
from . import _ffi
from . import _cdata
from . import _rawffi
from . import _callbacks
from . import _buffer
from . import _functions
from . import _class
from . import _objects
from . import _cffi_backend
from . import _embedding
from . import _cffi1_cdef
from . import _cffi1_module
from . import _cffi1_types
from . import _cffi1_misc
from . import _cffi1_verifier
from . import _cffi1_include
from . import _cffi1_parse
from . import _cffi1_build
from . import _cffi1_dynamic
from . import _cffi1_target_cpy
from . import _cffi1_target_x86
from . import _
