import weakref

from . import _core
from . import _util
from . import _compat
from . import _errors
from . import _types
from . import _constants
from . import _version
from . import _lib
from . import _ffi
from . import _cdata
from . import _callbacks
from . import _functions
from . import _class
from . import _objects
from . import _pyobject
from . import _weakref
from . import _refcount
from . import _buffer
from . import _pycapsule
from . import _typeobject
from . import _pystate
from . import _pyerrors
from . import _pytypes
from . import _pytime
from . import _pymem
from . import _pydebug
from . import _pyarena
from . import _pystate
from . import _codecs
from . import _warnings
from . import _pyhash
from . import _pygc
from . import _pytraceback
from . import _pyframe
from . import _pycodec
from . import _pyio
