import weakref

from . import _lib
from . import _ffi
from . import _core
from . import _util
from . import _errors
from . import _compat
from . import _constants
from . import _types
from . import _version

from . import _lzma
from . import _stream
from . import _filter
from . import _check
from . import _index
from . import _container
from . import _fileio
from . import _fileobj
from . import _streamreader
from . import _streamwriter
from . import _fileobjreader
from . import _fileobjwriter
from . import _filereader
from . import _filewriter
from . import _fileobjthread
from . import _filethread
from . import _fileobjlock
from . import _filelock
from . import _fileobjbuffer
from . import _filebuffer
from . import _fileobjcopy
from . import _filecopy
from . import _fileobjcopythread
from . import _filecopythread
from . import _fileobjcopybuffer
from . import _filecopybuffer
from . import _file
