import weakref

from . import _core
from . import _util
from . import _types
from . import _errors
from . import _constants
from . import _compat
from . import _lib
from . import _ffi
from . import _cdata
from . import _rawffi
from . import _buffer
from . import _callbacks
from . import _make
from . import _pointer
from . import _primitive
from . import _taggedpointer
from . import _typeof
from . import _unions
from . import _structures
from . import _variables
from . import _arrays
from . import _pointers
from . import _functions
from . import _enums
from . import _bitfields
from . import _classes
from . import _strings
from . import _lazily
from . import _cffi_backend
from . import _cffi_include
from . import _cffi_errors
from . import _cffi_ext
from . import _cffi_opcode
from . import _cffi_parse
