import weakref

from . import _core
from . import _util
from . import _widget
from . import _window
from . import _dialog
from . import _image
from . import _text
from . import _layout
from . import _style
from . import _event
from . import _graphics
from . import _app
from . import _menu
from . import _clipboard
from . import _dragdrop
from . import _gl
from . import _gl2
from . import _gl3
from . import _gl4
from . import _gl_ext
from . import _gl_ext2
from . import _gl_ext3
from . import _gl_ext4
from . import _gl_ext5
from . import _gl_ext6
from . import _gl_ext7
from . import _gl_ext8
from . import _gl_ext9
from . import _gl_ext10
from . import _gl_ext11
from . import _gl_ext12
from . import _gl_ext13
from . import _gl_ext14
from . import _gl_
