import weakref

from pygame.rect import Rect
from pygame.sprite import Sprite
from pygame.surface import Surface

from pygame.locals import K_LEFT, K_RIGHT, K_UP, K_DOWN, K_SPACE

import constants
from game_state import GameState
from game_object import GameObject
from game_object import GameObjectGroup
from game_object import GameObjectManager
from game_object import GameObjectManagerGroup
from game_object import GameObjectManagerCollisionHandler
from game_object import GameObjectManagerCollisionHandlerGroup

from game_object_manager import GameObjectManager
from game_object_manager import GameObjectManagerGroup

from game_object_manager_collision_handler import GameObjectManagerCollisionHandler
from game_object_manager_collision_handler import GameObjectManagerCollisionHandlerGroup

from game_object_manager_collision_handler_group import GameObjectManagerCollisionHandlerGroup

from game_object_manager_group import GameObjectManagerGroup

from game_object_group import GameObjectGroup

from game_state import GameState
