import weakref

from . import _core
from . import _util
from . import _errors
from . import _types
from . import _lib
from . import _ffi
from . import _compat
from . import _version
from . import _constants
from . import _cdata
from . import _cffi_backend
from . import _cffi_include
from . import _cffi_errors
from . import _cffi_ext
from . import _cffi_opcode
from . import _embedding
from . import _backend
from . import _callbacks
from . import _cffi_setup
from . import _cffi_printer
from . import _cffi_errors
from . import _cffi_parse
from . import _cffi_build
from . import _cffi_cdef
from . import _cffi_include
from . import _cffi_types
from . import _cffi_unions
from . import _cffi_common_h
from . import _cffi_errors
