import weakref

from . import _core
from . import _util
from . import _errors
from . import _types
from . import _constants
from . import _compat
from . import _lib
from . import _ffi
from . import _cdata
from . import _rawffi
from . import _callbacks
from . import _buffer
from . import _make
from . import _pointer
from . import _primitive
from . import _unions
from . import _structures
from . import _variables
from . import _lazy
from . import _containers
from . import _pointers
from . import _arrays
from . import _streams
from . import _cffi_backend
from . import _cffi_errors
from . import _cffi_include
from . import _cffi_utils
from . import _cffi_setup
from . import _cffi_cdef
from . import _cffi_exports
from . import _cffi_mallocs
