import weakref

from . import _core
from . import _util
from . import _widget
from . import _container
from . import _dialog
from . import _window
from . import _image
from . import _graphics
from . import _text
from . import _layout
from . import _style
from . import _event
from . import _font
from . import _app
from . import _menu
from . import _timer
from . import _clipboard
from . import _dragdrop
from . import _gl
from . import _webview
from . import _sound
from . import _media
from . import _data
from . import _http
from . import _socket
from . import _xml
from . import _json
from . import _zip
from . import _process
from . import _shell
from . import _log
from . import _settings
from . import _system
from . import _test
from . import _test2
from . import _test3
from . import _test4
