import weakref

from . import _core
from . import _util
from . import _errors
from . import _types
from . import _constants
from . import _compat
from . import _lib
from . import _ffi
from . import _cdata
from . import _rawffi
from . import _callbacks
from . import _buffer
from . import _weakref
from . import _pyctypes
from . import _pointer
from . import _cffi1_backend
from . import _cffi_include
from . import _embedding
from . import _backendutil
from . import _cffi_errors
from . import _cffi_ext
from . import _cffi_opcode
from . import _cffi_parse
from . import _cffi_setup
from . import _cffi_test
from . import _cffi_unpacker
from . import _cffi_utils
from . import _cffi_include
from . import _cffi_errors
from . import _cffi_ext
