import weakref

from . import _core
from . import _util
from . import _compat
from . import _types
from . import _errors
from . import _functions
from . import _constants
from . import _enums
from . import _classes
from . import _objects
from . import _structs
from . import _wrappers
from . import _callbacks
from . import _variants
from . import _interfaces
from . import _dispatch
from . import _automation
from . import _safearray
from . import _rawcom
from . import _combase
from . import _comtypesbase
from . import _comtypes_util
from . import _comtypes_testcases
from . import _comtypes_gen
from . import _comtypes_builtin
from . import _comtypes_ext
from . import _comtypes_startup
from . import _comtypes_support
