import weakref

from . import _lib
from . import _ffi
from . import _errors
from . import _util
from . import _compat
from . import _constants
from . import _types
from . import _cdata
from . import _enums
from . import _functions
from . import _classes
from . import _class_types
from . import _objects
from . import _methods
from . import _signals
from . import _properties
from . import _signalhelper
from . import _importer
from . import _mainloop
from . import _version
from . import _versionhelper
from . import _overrides
from . import _api
from . import _gobject
from . import _gi
from . import _gi_cairo
from . import _gi_gdk
from . import _gi_glib
from . import _gi_gobject
from . import _gi_pango
from . import _gi_atk
from . import _gi_gtk
from . import _gi_girepository
from . import _gi_gio
