import weakref

from . import _core
from . import _util
from . import _ffi
from . import _lib
from . import _libuv
from . import _loop
from . import _tcp
from . import _udp
from . import _pipe
from . import _tty
from . import _timer
from . import _prepare
from . import _check
from . import _idle
from . import _async
from . import _signal
from . import _fs
from . import _work
from . import _getaddrinfo
from . import _dns
from . import _threadpool
from . import _poll
from . import _process
from . import _fs_event
from . import _fs_poll
from . import _handle
from . import _stream
from . import _tcp_shutdown
from . import _connect_req
from . import _shutdown_req
from . import _write_req
