import weakref

from . import _lib
from . import _ffi
from . import _util
from . import _constants
from . import _errors
from . import _compat
from . import _types
from . import _version
from . import _cdata
from . import _cdata_helpers
from . import _cdata_structs
from . import _cdata_protocols
from . import _cdata_functions
from . import _cdata_types
from . import _cdata_arrays
from . import _cdata_pointers
from . import _cdata_enums
from . import _cdata_unions
from . import _cdata_bitfields
from . import _cdata_variants
from . import _cdata_callbacks
from . import _cdata_callbacks_retain
from . import _cdata_callbacks_helpers
from . import _cdata_callbacks_protocols
from . import _cdata_callbacks_structs
from . import _cdata_callbacks_unions
from . import _cdata_callbacks_
